lib/action_view/component.rb, test/action_view/component_test.rb
This PR addresses https://github.com/github/actionview-component/issues/19 where template changes were not reflected when reloading a page in development.
It also corrects an error message that referenced the now-removed inline template functionality.
The `modify_file` test helper is shamelessly adapted from `rails/actionview/test/template/compiled_templates_test.rb`.
cc @metade @mikker
=> Do not use compiled template outside of production

lib/action_view/component/base.rb, test/action_view/integration_test.rb, test/app/components/partial_component.html.erb
It's possible to render a partial by calling render with the partial string, i.e. without using the partial keyword argument.
Updating ActionView::Component::Base#render to handle this.
=> Fix implicit partial rendering from components

lib/action_view/component/base.rb, test/action_view/component_test.rb, test/app/components/css_sidecar_file_component.css, test/app/components/css_sidecar_file_component.html.erb, test/app/components/css_sidecar_file_component.rb
This PR tightens our template file lookup logic so that non-template files do not trigger the multiple-sidecar-files error.
[Fixes #55]
=> Allow sidecar CSS files

CHANGELOG.md, lib/action_view/component/base.rb, lib/action_view/component/test_helpers.rb, test/action_view/component_test.rb, test/app/components/request_component.html.erb, test/app/components/request_component.rb
In order for certain helpers (such as those from `devise`) to work, we need to have access to the `request`. 
cc @cjbottaro
=> allow access to request in component

actionview-component.gemspec, lib/action_view/component/version.rb, test/action_view/component_test.rb
Adding these constants enables consumers to programmatically access the version with ease, e.g.
```rb
unless ActionView::Component::VERSION::STRING == '1.3.4'
raise 'Remove this patch when upgrading ActionView::Component'
end
```
or
```rb
if ActionView::Component::VERSION::MAJOR == 1
else
end
```
=> Add ActionView::Component::VERSION constants

README.md, lib/action_view/component/test_helpers.rb, test/action_view/component_test.rb
Let Nokogiri point directly at the rendered component instead of requiring the
knowledge about the fact that it's rendered in the context of an HTML document.
A deprecation cycle shouldn't be necessary the change is compatible with the former use (as ensured by the two tests).
=> Preselect the rendered component in render_inline

Gemfile.lock, actionview-component.gemspec, lib/action_view/component/base.rb
This PR gives a more clear example in the argument format deprecation warning.
cc @breim
[Fixes #88]
=> Deprecation example

.github/workflows/ruby_on_rails.yml, README.md
Actions removed support for Ruby 2.3, and we've not seen this check fail yet, so I think we're OK to remove it for the sake of momentum.
=> remove ruby 2.3 support, as Actions has removed it

lib/action_view/component/base.rb
Our existing implementation of looking up sibling template files
split the source_location path on '.', assuming that the .rb
file extension was the only place a period was used in the entire
file path. This meant that any component file in a path that contained
other periods failed to find its sibling templates.
I did not include a test here as it seemed difficult to impossible to write one.
[Fixes: #83]
Co-Authored-By: Anton <profox.rus@gmail.com>
=> explicitly remove extension from path vs splitting on '.'

lib/action_view/component/base.rb, test/action_view/component_test.rb, test/app/components/helpers_proxy_component.html.erb, test/app/components/helpers_proxy_component.rb, test/app/helpers/message_helper.rb
Adds a `#helpers` method that works as a proxy for components to access helper methods through.
Before this PR you'd have to include helpers on a per-module basis:
```ruby
module IconHelper
def icon name
tag.i data: { feather: name.to_s.dasherize }
end
end
UserComponent < ActionView::Component::Base
include IconHelper
def profile_icon
icon :user   
end
end
```
Now they can be referenced directly through the `#helpers` proxy:
```ruby
UserComponent < ActionView::Component::Base
def profile_icon
helpers.icon :user   
end
end
```
Or delegated, if you prefer:
```ruby
UserComponent < ActionView::Component::Base
delegate :icon, to: :helpers
def profile_icon
icon :user   
end
end
```
---
The proxy pattern makes all helpers available for "free" and prevents our component classes from bloating with …
=> Add helpers proxy

lib/action_view/component/base.rb, test/action_view/component_test.rb, test/app/components/translations_component.html.erb, test/config/locales/en.yml
Rails default for translation shortcut paths do not include the parent folder where the translations are used.
For instance, when you use `t('.success')` in a controller, the translation key does not include the `controllers` folder.
Therefore, the word `components` get removed from the virtual path of components.
This will allow us to use `t('.title')` in components and expect the translation key not to include the `components` key as the top level key in the translation yml file.
What happens when the developer uses a different folder for components? The virtual path will just be the location of the file, in other words, the output of `Class#source_location`.
=> Removing "components" from virtual path

README.md, lib/rails/generators/component/USAGE, lib/rails/generators/component/component_generator.rb, lib/rails/generators/component/templates/component.rb.tt, lib/rails/generators/test_unit/component_generator.rb, lib/rails/generators/test_unit/templates/component_test.rb.tt
Closes #110.
This PR does two things:
1. While going through the README I realized that the desire is for components to be suffixed with component (for class and file names). My apologies, I missed that in the initial implementation. The first commit adds the component suffix to all files and classes.
2. Adds the Quick start section for creating a component using the generator.
=> Add component suffix to generator

lib/rails/generators/test_unit/templates/component_test.rb.tt
This PR includes a missing module to generated test cases
I noticed the test helpers aren't included in the generator test case template. I went ahead and included the module, as `render_inline` is defined in  `ActionView::Component::TestHelpers`.
=> Include test helpers in generator template

lib/action_view/component/base.rb
As we move to make ActionView::Component::Base behave more like a template, I'm looking to see if we can remove the DummyTemplate class.
=> Remove DummyTemplate

lib/action_view/component/base.rb, lib/action_view/component/preview.rb, lib/action_view/component/railtie.rb, test/action_view/component_test.rb, test/test_helper.rb
This PR refactors our require structure to better
mimic how the gem is required in applications.
@kaspermeyer this might be of use in your work on compiling on init.
=> explicitly require actionview/component/base in tests

lib/rails/generators/component/component_generator.rb
Issue
======
ComponentGenerator creates component with broken parameters leaving off a `:` on the last attribute. For example `rails g component Example hello world` generates:
```ruby
class ButtonComponent < ActionView::Component::Base
def initialize(hello:, world)
.....
```
Solution
======
@dylnclrk and I altered the `#map` method in `ComponentGenerator#initialize_signature` to append the `:` and then join the array with `, `.
_NOTE_: We did not add a test for this case since there are no established patterns for testing the generators.
=> Fix issue with generating component initiatilze_signature from attributes

README.md, lib/action_view/component.rb, lib/action_view/component/base.rb, lib/action_view/component/monkey_patch.rb, test/config/application.rb
In trying to setup component previews in the
actionview-component-demo repo, I realized that we were
requiring users of this gem to explicitly require the railtie
in order for them to work.
This PR moves us towards a more typical gem structure
where a single entry file, lib/action_view/component.rb,
loads the rest of the gem.
This big of a change should probably prompt us to make a minor release version bump.
cc @kaspermeyer @juanmanuelramallo
=> consolidate require's into a single loader file for the gem

lib/action_view/component/railtie.rb
This PR removes eager loading registration that caused Rails to raise an exception on application boot when eager loading was turned on.
=> Remove eager loading registration

lib/action_view/component/railtie.rb
- Thanks to @franciscoj for sharing the fix
- It was failing in Rails 6 due to updating a frozen array
- Updated railties class to work with Rails 6 (source: https://github.com/rails/rails/blob/master/actionmailer/lib/action_mailer/railtie.rb)
=> [#122] Fix railtie

lib/action_view/component/railtie.rb
This PR disables an initializer that crashes when eager loading is enabled.
Since attempts to eager load are already disabled for now (https://github.com/github/actionview-component/commit/6dc979793d5eb29478f3fcbfd7408405e767254a) I think it makes sense to disable this initializer as well. When its intent has been sorted out and I get started working on strategies to enable eager/autoloading, it'll probably make sense to enable it again.
Resolves: #126
=> Disable initializer `action_view_component.eager_load_actions`

README.md, lib/rails/generators/rspec/component_generator.rb, lib/rails/generators/rspec/templates/component_spec.rb.tt
The component generator does not support RSpec. 
When a project is configured to use RSpec and the component generator is run, no spec is created.
@rdavid1099 and I added an RSpec hook to the component generator to create a corresponding spec. We also added some instructions to the README about configuring RSpec to include test helpers like `#render_inline`. 
* Does this functionality belong in actionview-component?
* This seems useful to include, as establishing patterns for testing components with RSpec will be valuable for a number of users.
* However, the RSpec generators and configuration should probably be moved in to rspec-rails when actionview-component is provided by Rails, as rails does not include RSpec generators.
* How can we test changes like this to generators? 
* I'm not …
=> Add rudimentary RSpec support to the component generator

lib/action_view/component/railtie.rb
Having these requires at the top of the file broke our local
dev environment. I found it hard to write a test for this, but it
worked locally for me.
=> require controllers as part of setting autoload paths

.github/workflows/ruby_on_rails.yml, .gitignore, Gemfile, Gemfile.lock, test/app/models/application_record.rb, test/app/models/post.rb, test/config/application.rb, test/config/database.yml, test/test_helper.rb
In #129, `to_component_class` support was added, to allow an Active Model instance to be conveniently rendered using an associated component class.
However, this work initially targeted ActiveRecord, which necessitated a dependency on sqlite for testing. This dependency can be eliminated by using Active model (instead of ActiveRecord) in the tests.
=> Eliminate sqlite dependency

lib/rails/generators/test_unit/templates/component_test.rb.tt, test/action_view/generator_test.rb, test/action_view/test_unit_generator_test.rb
Test was created with `render_inline(Thing)` which should be `render_inline(ThingComponent)`.
Also created very basic testcase for generator.
=> Generate test with new naming convention

lib/action_view/component/base.rb, test/action_view/component_test.rb
Shout out to @asgerb; this is practically a clone of #142, but with one commit from me that moves the logic to `ActionView::Component::Base.call_method_name` per [Joel's comment](https://github.com/github/actionview-component/pull/142#discussion_r354556290).
=> Variant template fallback

lib/action_view/component/test_helpers.rb, test/action_view/component_test.rb, test/action_view/integration_test.rb, test/test_helper.rb
The main thrust of this change is to avoid dropping elements by using
`.css("body > *")`, which will strip out some elements in some
situations and produce unexpected test results. At the same time, we'll
clean up some tests to ensure that whitespace stripping is more
consistent and test arguments are given in a more consistent order.
Fixes #145.
=> Avoid dropping elements in the render_inline test helper and adjust tests

lib/action_view/component/base.rb, test/action_view/component/base/unit_test.rb
Problem
=======
I encountered an edge case when trying to use variants. My local development environment has an additional `.` in it (`/example/fake.user/path/to/actionview-component`). The extracting the variant from the `source_location` assumes the path only has `.` in the respective files (`path.split(".").second.split("+")[1]&.to_sym`).
Solution
=======
Using similar patterns to how Rails extracts the variants from views (https://github.com/rails/rails/blob/d2e8b839d2e7236b5f85797f239b01ca2e783024/actionview/lib/action_view/template/resolver.rb#L272), I altered the extraction of the variants in `ActionView::Component::Base#templates`.
_Note_: I did not add any tests for this edge case since, at first, four tests dealing with variants were failing in my local environment. The fix …
=> Fix edge case issue with extracting variants from less conventional source_locations

lib/action_view/component/preview.rb, test/action_view/integration_test.rb, test/app/components/preview_component.html.erb, test/test/components/previews/preview_component_preview.rb
Allow component previews to use content that is passed to the `render` function as a block.
=> feat(previews): pass content block when rendering

lib/action_view/component/preview.rb, test/action_view/preview_test.rb, test/test/components/previews/no_layout_preview.rb
Fixes the bug that specifying `layout false` in a Preview was ignored because of a truthy check rather than a nil check. 
Also added the ability to override the layout in Preview.call. This allows for other integration options in particular setting the layout to false so we can build controllers that return just the component html without the layout chrome. For example a Rails backend for Storybook #159.
=> Allow Previews to have no layout 

.github/ISSUE_TEMPLATE, .github/PULL_REQUEST_TEMPLATE
Add rudimentary issue and PR templates, adapted from the [templates in Rails](https://github.com/rails/rails/blob/master/.github/). This is probably overkill, but it would be nice to see something to start with when opening a new PR or issue.
Adding this will complete this checklist I see in the [community profile](https://github.com/github/actionview-component/community), which I feel compelled to complete 😆.
=> Add GitHub issue and PR templates

.gitignore, lib/action_view/component/base.rb, lib/action_view/component/railtie.rb
This should fix the Uninitialized Constant error. 
Its standard practice to include the entire "gem" in a Railtie and we changed that with 1.6.0
See:
https://github.com/rails/rails/blob/master/actionmailer/lib/action_mailer/railtie.rb#L4
https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/railtie.rb#L4
=> Fix Uninitialized Constant error #163

lib/action_view/component/base.rb, test/action_view/component_test.rb, test/app/components/conditional_render_component.html.erb, test/app/components/conditional_render_component.rb
This pull request introduces a new method, `#render?`, which indicates if the component should render at all (defaults to `true`).
What problem does this solve?
Our application has a handful of components that should only be displayed in certain scenarios. Some examples are banners that appear at the top of the page:
- "Your free trial ends in {x} days"
- "Your account is past due"
- "Please confirm your email address"
In order to show/hide these components, we had to either include logic in the view:
```erb
<% if subscription.past_due? %>
<%= render(PastDueAlertComponent, subscription: subscription) %>
<% end %>
```
or in the component itself:
```erb
<% if subscription.past_due? %>
<p>Your account is past due.</p>
<% end %>
```
This isn't _terrible_, but our team began to dislike having …
=> Add `#render?` hook to easily allow components to be no-ops

lib/action_view/component/base.rb, lib/action_view/component/preview.rb, lib/action_view/component/railtie.rb, lib/railties/lib/rails.rb, lib/railties/lib/rails/component_examples_controller.rb, lib/railties/lib/rails/components_controller.rb, lib/railties/lib/rails/templates/rails/components/preview.html.erb, lib/railties/lib/rails/templates/rails/examples/show.html.erb, test/action_view/preview_test.rb
Remove ComponentExamplesController in favor of inline the ComponentsController itself doing the rendering.
One less moving part for this gem to contain AND we don't have to include the TestHelpers in Preview
=> Remove the unneeded ComponentExamplesController and simplify preview rendering

.gitignore, .rubocop.yml, lib/rails/generators/component/component_generator.rb, lib/rails/generators/rspec/component_generator.rb, lib/rails/generators/test_unit/component_generator.rb, test/generators/component_generator_test.rb
When generating namespaced components, the generated class names are correct, but the generated files are placed in the root `app/components` directory, and not in the namespace subdirectory.
This means running `rails g component admins/user` will correctly generate `Admins::UserComponent`, but the generated files look like this:
* generated: `app/components/user_component.rb`
should be: `app/components/admins/user_component.rb`
* generated: `app/components/user_component.html.erb` 
should be: `app/components/admins/user_component.html.erb`
* generated: `test/components/user_component_test.rb`
should be: `app/components/admins/user_component_test.rb`
This PR fixes that by adding the `class_path` to the generated file path and adds a test for the generator.
If/when this gets merged I've …
=> Fix generator placing namespaced components in the root directory

CHANGELOG.md, README.md, lib/action_view/component/base.rb, test/action_view/component_test.rb, test/app/components/conditional_render_component.rb
It's useful to be able to rely on component input validation within a `render?` method, so that you can use input variables to derive your rendering decision. This changes the order of rendering to perform validation _first_, then check `render?` just before performing the actual render.
=> Validate components before checking for conditional rendering

.github/workflows/ruby_on_rails.yml
PR #174 introduces a feature that requires Ruby 2.7. In order to test this feature, need to run CI against 2.7.  
Let's update our workflow configuration accordingly.
Note that the version of bundler used in the workflow was updated to match our Gemfile.lock. It was pinned to 1.14 in #35, but seems to be OK to update (and the old version was causing issues with 2.7).
=> Update workflow config to include Ruby 2.7

CHANGELOG.md, README.md, lib/action_view/component/base.rb, test/action_view/component_test.rb, test/action_view/integration_test.rb, test/action_view/invalid_components_test.rb, test/app/components/missing_initializer_component.html.erb, test/test_helper.rb
As discussed in github#93, Ruby 2.7 introduces [`#const_source_location`](https://ruby-doc.org/core-2.7.0/Module.html#method-i-const_source_location) to find the location of constants. This means that we no longer have to find the location of components through the location of their `#initialize` method, and we can remove the initializer requirement for Ruby 2.7+.
* Use `#const_source_location` in `ActionView::Component::Base::source_location`, when it's available. 
* Move the initializer-less component test out of invalid, and in to a proper component test. Test it still throws the error for Rubies < 2.7.
* Change eager-loading logic for Ruby 2.7+
(The old todo, `Test eager loading change`, is no longer necessary.)
=> Remove initalizer requirement for Ruby 2.7+

.github/workflows/ruby_on_rails.yml, README.md
It looks like CI isn't too happy after we merged https://github.com/github/actionview-component/pull/200. 
I'm going to poke around on this PR and see if we can get something working, as this is blocking us from merging PRs.
=> We're seeing some issues with CI. I'm going to see if this fixes it

CHANGELOG.md, Gemfile.lock, actionview-component.gemspec
We depend on an older version of Capybara. Hopefully
this change will allow us to proceed without
having to update our dependencies.
=> relax capybara dependency

lib/action_view/component/base.rb
`render_in` has no use for `*args`. Let's remove it.
=> Render in args

.github/ISSUE_TEMPLATE
I just open issue about ruby 2.7 and realize that issue template miss gem version. So, adding.
=> Add gem version to ISSUE_TEMPLATE

lib/action_view/component/base.rb, test/action_view/component_test.rb, test/app/components/no_validations_component.html.erb, test/app/components/no_validations_component.rb
After speaking with @rainerborene, @jonspalmer, and several folks here at work, we think it's best to move forward with removing validations from the library in `v2`.
In this PR, we'll start this process by moving the call to `validate!` to a before_render_check method, which can be subclassed to be a no-op.
After this, we will introduce the new `ViewComponent::Base` class, we will remove the `validate!` call and the inclusion of `ActiveModel::Validations`.
=> Before render

CHANGELOG.md, README.md, lib/action_view/component/base.rb, test/action_view/component_test.rb, test/action_view/integration_test.rb, test/action_view/invalid_components_test.rb, test/test_helper.rb
=> revert: Remove initializer requirement for Ruby 2.7+

CHANGELOG.md, README.md, lib/action_view/component/base.rb, test/action_view/invalid_components_test.rb, test/app/components/exception_in_template_component.html.erb, test/app/components/exception_in_template_component.rb
Currently `__FILE__` and `__LINE__` are the arguments passed to
`class_eval` which means when an exception is raised in the template it
will point back to the component instead of the correct line of the
template.
This updates the filepath and line number arguments passed to
`class_eval` to point to the template instead of the component.
resolves https://github.com/github/actionview-component/issues/85
Here's some screenshots displaying the difference:
Before:
After:
=> Set template filepath and line number for better backtraces

CHANGELOG.md, lib/action_view/component.rb, lib/action_view/component/engine.rb, lib/action_view/component/rendering_monkey_patch.rb, test/action_view/integration_test.rb, test/app/components/controller_inline_component.html.erb, test/app/components/controller_inline_component.rb, test/app/controllers/integration_examples_controller.rb, test/app/views/integration_examples/_controller_inline.html.erb, test/config/routes.rb
This change introduces the ability to render components from
controllers, mimicking the behavior introduced in
https://github.com/rails/rails/pull/37919.
[Fixes: #38]
=> add rudimentary support for rendering components from controllers

.github/PULL_REQUEST_TEMPLATE, CONTRIBUTING.md, README.md, actionview-component.gemspec
This PR updates some comments to reference our new repository name, `github/view-component` 🎊
=> use new repo name

CHANGELOG.md, README.md, lib/view_component/preview.rb, test/test/components/previews/preview_component_preview.rb, test/view_component/integration_test.rb
Make `ActionView::Helpers::TagHelper` available in
`ViewComponent::Previews`:
```ruby
def with_html_content
render(MyComponent.new) do
tag.div do
content_tag(:span, "Hello")
end
end
end
````
This commit includes [`ActionView::Helpers::TagHelper`][tag-helper] into
`ViewComponent::Preview` base class, which provides the [`tag`][tag] and
[`content_tag`][content_tag] view helper methods.
[tag-helper]: https://api.rubyonrails.org/classes/ActionView/Helpers/TagHelper.html
[tag]: https://api.rubyonrails.org/classes/ActionView/Helpers/TagHelper.html#method-i-tag
[content_tag]: https://api.rubyonrails.org/classes/ActionView/Helpers/TagHelper.html#method-i-content_tag
=> Make `TagHelper` available in Previews

CHANGELOG.md, lib/view_component/render_monkey_patch.rb, lib/view_component/rendering_monkey_patch.rb
This change disables the monkey patch when the Rails version
is at least 6.1.
This change confirms the compatibility of the library with Rails 6.1.
=> bypass monkey patch on Rails 6.1 builds.

CHANGELOG.md, lib/action_view/component/test_case.rb, lib/action_view/component/test_helpers.rb, lib/view_component.rb, lib/view_component/test_helpers.rb, test/view_component/action_view_component_test.rb, test/view_component/view_component_test.rb
This module should not have been removed in #239, as doing so
was a breaking change.
This change re-introduces the module and moves render_component,
which will be removed in v2.0.0, to the module.
Thanks to @jcoyne for the report!
[fixes: #254]
=> re-introduce ActionView::Component::TestHelpers

CHANGELOG.md, README.md, lib/view_component/base.rb, test/app/components/inline_component.rb, test/view_component/view_component_test.rb
This is useful feature when it comes to create little widgets, toggle buttons, badges, and so on. It removes the need of an extra template file with one single line of code.
=> Allow components to be rendered without a template file

lib/view_component/base.rb
This line breaks when this library is a dependency of a ruby gem (such as the case of building a third party component library)
Refs #231 Support for this library as a dependency of third-party component libraries
=> Check for Rails before invocation

CHANGELOG.md, README.md, lib/view_component/test_helpers.rb, test/view_component/view_component_test.rb
This PR introduces the `refute_component_rendered` test helper.
[Finishes: #261]
=> 261 no render

CHANGELOG.md, lib/rails/generators/component/component_generator.rb, lib/rails/generators/component/templates/component.rb.tt, lib/rails/generators/erb/component_generator.rb, lib/rails/generators/erb/templates/component.html.erb.tt, lib/rails/generators/haml/component_generator.rb, lib/rails/generators/haml/templates/component.html.haml.tt, lib/rails/generators/slim/component_generator.rb, lib/rails/generators/slim/templates/component.html.slim, lib/rails/generators/slim/templates/component.html.slim.tt, lib/rails/generators/test_unit/templates/component_test.rb.tt, test/generators/component_generator_test.rb, test/generators/erb_generator_test.rb, test/generators/haml_generator_test.rb, test/generators/slim_generator_test.rb, test/view_component/test_unit_generator_test.rb
This PR changes the component generators to not accept `requires_content`, as this option was creating components that use validations, something the library no longer supports out of the box.
cc @asgerb
=> ViewComponent generators should not have content validation

CHANGELOG.md, actionview-component.gemspec
This PR sets in motion our migration to `view_component` 🎊 . I've already published `v1.16.0` under the new name. 
With this change, the next release will be the last to be made under `actionview-component`.
=> add post-install message about name change

.github/workflows/ruby_on_rails.yml, README.md
Fixes #209 
Update the `ruby_on_rails` action to re-add testing against Ruby 2.4.
To accomplish this, we need to run `gem update --system`, but we don't
want to do this on any version except `2.4.x` to save build time.
This commit uses the context and expression syntax for GitHub actions to
check if the Ruby versions starts with `2.4`, and update the system gems
in the event that we have a match.
=> Support Ruby 2.4 in CI

test/app/components/conditional_render_component.rb, test/view_component/view_component_test.rb
This is a small PR that removes a component validation for at test since we are moving away from those. It also replaces the use of `attr_reader` in favor of the instance variable. 🎉
=> Removed validation on should_render test

CHANGELOG.md, lib/view_component/base.rb, test/config/application.rb, test/config/environments/test.rb, test/view_component/better_html_test.rb, test/view_component/integration_test.rb, test/view_component/view_component_test.rb
This PR introduces support for `config.action_view.annotate_template_file_names`, which is coming in Rails 6.1: https://github.com/rails/rails/pull/38848.
=> Add support for config.action_view.annotate_template_file_names

lib/view_component/base.rb, test/app/components/child_component.html.erb, test/app/components/child_component.rb, test/app/components/parent_component.rb, test/view_component/view_component_test.rb
Given an ApplicationComponent that re-defines `inherited`,
we were failing to find the correct template for the child
component, as we were looking at the top frame in the
call stack.
This change ignores any definitions of `inherited` in
the call stack, avoiding the issue.
[Fixes: #280]
=> ignore redefinitions of inherited when inspecting caller locations

README.md
This is a first draft of adding info on sidecar frontend assets to the README (related to #168). I need to test out the examples more to make sure they're bug-free and some of the wording could be streamlined, but I wanted your overall feedback before tweaking it too much.
I feel like this might be a good candidate for adding to a separate .md docs file somewhere, as I'm not quite sure it integrates holistically into the existing README flow. Let me know what you think.
=> Sidecar frontend readme docs

CHANGELOG.md, lib/view_component/base.rb
For now, we need to set the format of ViewComponents to :html,
as there are other latent assumptions in the library that we
will only use it to build HTML.
This change unblocks better support for template annotations
in Rails.
cc @github/view-component-reviewers
=> All ViewComponents have an :html format

README.md
The information about the migration from `ActionView::Component` to `ViewComponent` is not relevant for newcomers. To that end, it doesn't seem necessary to continue taking up a large portion of the beginning of the `README` with that information. Instead, we can link to the associated issue and the old description from the README's history.
=> Replace the ActionView::Component migration description in README with some links

view_component.gemspec
The view_component gem is currently bundling more files than actually needed/used by the applications where it's installed. 
Using version 2.0.0, after running `ls /Users/{whoami}/.gem/ruby/2.6.3/gems/view_component-2.0.0`, we get:
```
CHANGELOG.md           
CONTRIBUTING.md        
Gemfile.lock           
README.md              
app                    
lib                    
view_component.gemspec
CODE_OF_CONDUCT.md     
Gemfile                
LICENSE.txt            
Rakefile               
docs                   
script
```
After this change, we'll get:
```
CHANGELOG.md 
LICENSE.txt  
README.md    
app          
lib
```
Why only those files? Well they are the ones the final user would actually care about, and those are files being used in other gems: …
=> Updating gemspec files attribute

CHANGELOG.md, app/controllers/rails/view_components_controller.rb, test/view_component/integration_test.rb
Resolves #289 
- Updated view_components_controller to only prepend application's view paths when rendering a given preview
- Preview index views will use rails' default application layout
- Added integration tests for this new behaviour
=> Making rails application layout the default for preview index views

CHANGELOG.md, Gemfile, Gemfile.lock, README.md, lib/view_component/test_helpers.rb, view_component.gemspec
This is a potential solution for the issue brought up in #292.
`ViewComponent::TestHelpers` was the only module that used `capybara`, and that module is for the test environment. Thus, requiring `capybara` in the production environment is unnecessary. Furthermore, since it's still possible to test components using the return value of `render_inline`, applications that don't already have their own `capybara` dependency could still use `view_component` and test their components without the `capybara` assertions. On the other hand, any rails app that already depends on capybara (including any app that uses [Rails System Tests](https://guides.rubyonrails.org/testing.html#system-testing)) will automatically be able to use capybara assertions in their component tests.
=> Make Capybara optional

CHANGELOG.md, lib/view_component.rb, lib/view_component/engine.rb
Some of the modules we were `autoload`ing are internal modules. Unlike `Base`, `Preview`, `TestCase`, and `TemplateError`, we don't intend for users to directly use the `Previewable`, `TestHelpers`, `RenderMonkeyPatch`, or `RenderingMonkeyPatch` modules (AFAIK). So I've removed those modules from the gem's `autoload`s.
=> Only autoload public API

CHANGELOG.md, Gemfile.lock, view_component.gemspec
We're requiring activesupport in several places:
https://github.com/github/view_component/blob/060275c1927f4d7a5a5949866838a880ea896d2a/lib/view_component.rb#L3
https://github.com/github/view_component/blob/060275c1927f4d7a5a5949866838a880ea896d2a/lib/view_component/base.rb#L4
https://github.com/github/view_component/blob/060275c1927f4d7a5a5949866838a880ea896d2a/lib/view_component/preview.rb#L3
https://github.com/github/view_component/blob/060275c1927f4d7a5a5949866838a880ea896d2a/lib/view_component/previewable.rb#L3
https://github.com/github/view_component/blob/060275c1927f4d7a5a5949866838a880ea896d2a/lib/view_component/test_case.rb#L3
Thus, we should declare a formal dependency on it. Since we support Rails 5.0.0 through Rails 6.x, we've declared the dependency as `>= 5.0.0, < 7.0`. …
=> Declare dependency on activesupport

CHANGELOG.md, README.md, app/controllers/rails/view_components_controller.rb, lib/view_component/preview.rb, test/test/components/previews/preview_component_preview.rb, test/view_component/integration_test.rb
This is helpful when you want to show dynamic values on the component preview.
One use case is integrating [Storybook](https://storybook.js.org/) and the [Knobs addon](https://github.com/storybookjs/storybook/tree/master/addons/knobs), which allows to tweak the values directly from the component's page.
We can take those values and pass them down as params to the Rails preview page, which will then be used to set the values on the component.
I've been briefly playing with the repo from #159 and adding this would allow us to have something like:
=> Allow to access params in preview examples

CHANGELOG.md, lib/view_component/collection.rb
After running our test suite today with the latest version of `view_component` I got the following message:
> ActionView::Template::Error: undefined method `counter_argument_present?' for Courses::Card:Class
This is an edge case. If you're running a test or development environment and never rendered that specific component individually, then you will face the same problem. So, this pull request fixes this problem. In other words, `Courses::Card` is only rendered through collections, and isn't compiled at this point yet.
=> Compile component before rendering collection

lib/view_component/base.rb, lib/view_component/collection.rb
This PR is a preliminary pass at making our source code easier to understand for developers new to the project.
I:
- Added a healthy number of comments describing the function of specific lines/methods, often by deleting the code and seeing what tests failed 😱 
- Removed the `compile!` method, as it was only used twice. I think having the call sites use `compile(raise_errors: true)` is easier to understand.
- Moved a couple methods to be inside the `class << self` block.
This set of changes is non-breaking.
=> Annotations & Cleanups

README.md
The `assert_selector` API signature requires the `text:` keyword argument (https://www.rubydoc.info/github/teamcapybara/capybara/master/Capybara%2FNode%2FMatchers:assert_selector).
This simply updates the README to use it.
=> Update assert_selector API signature in README

CHANGELOG.md, README.md, lib/view_component/test_helpers.rb, test/view_component/view_component_test.rb
As discussed in https://github.com/github/view_component/issues/304#issuecomment-629468829, this PR renames `@raw` to `@rendered_component` and exposes a `rendered_component` reader.
With this method, it becomes possible to write the following expectation in an rspec-rails view spec:
```rb
expect(rendered_component).to have_css("header h1", text: "Buy milk")
```
which mirrors the example code from Capybara's README:
https://github.com/teamcapybara/capybara/blame/3.32.1/README.md#L235
I also backfilled some test coverage for the return value of `render_inline`. This seemed appropriate given that we started documenting it in the README in https://github.com/github/view_component/commit/18d4569721457a34ae4c2096cb2b0a0c36570637. (I should've added this test when I was working on …
=> Add rendered_component method to ViewComponent::TestHelpers

CHANGELOG.md, README.md, coverage/coverage.txt, lib/view_component/base.rb, test/app/components/no_validations_component.html.erb, test/app/components/no_validations_component.rb, test/app/components/old_validations_component.html.erb, test/app/components/old_validations_component.rb, test/view_component/view_component_test.rb
`before_render_check`, an API we never documented,
is a confusing name for this lifecycle method.
`before_render` matches the naming conventions
for Rails callbacks.
Related issue: https://github.com/github/view_component/issues/346
=> Add `before_render`, deprecating `before_render_check`

CHANGELOG.md, README.md, coverage/coverage.txt, lib/view_component/base.rb, lib/view_component/compile_cache.rb, lib/view_component/engine.rb, test/test_helper.rb, test/view_component/integration_test.rb, test/view_component/view_component_test.rb
This is the same strategy as followed by ActionView.
Closes: #345
ViewComponent will on development never cache templates, and thus they are always recompiled. If a given component is rendered in a loop (imagine a component that is rendered on a table), the recompile time starts to add up.
OTOH, ActionView caches, but when ActionView::Resolver.caching? is false, it registers a callback to clear the cache on each request:
https://github.com/rails/rails/blob/3cd1b19ff2e49642191c598d620b87ffe5ec6cda/actionview/lib/action_view/railtie.rb#L96-L99
Thus, the optimal solution would be to do something similar: invalidate the cache on each request.
I'm creating as draft because:
1. ~I have yet to test this.~
2. There is a test failure:
```
Failure: …
```
=> Enabling caching in development, and discard on each request.

CHANGELOG.md, README.md, coverage/coverage.txt, lib/view_component/base.rb, test/app/components/product_reader_oops_component.html.erb, test/app/components/product_reader_oops_component.rb, test/view_component/view_component_test.rb
I ran into this fun today when I left a trailing comma on an `attr_reader`
If the Ruby class is invalid, the library should not fail with `initializer must accept ...` ArgumentErrors. Instead it should throw an error better explaining the issue.
Open question: is it valid to initialize a class for a view component without an initialize parameter? It seems like it should be 🤔 .
=> Ruby parse errors throw confusing error

CHANGELOG.md, README.md, coverage/coverage.txt, lib/view_component/base.rb, test/app/components/container_component.rb, test/view_component/view_component_test.rb
As reported in #321, global Rails helpers are not accessible within
nested components. This is because their view context is the parent
component, where global helpers are not available.
=> Fix issue with inaccessible helpers from nested components

CHANGELOG.md, README.md, coverage/coverage.txt, lib/view_component/base.rb, test/app/components/rails_config_component.html.erb, test/app/components/rails_config_component.rb, test/view_component/view_component_test.rb
ViewComponent::Base initializes its own `config` that is empty
by default, and thus overrides the `view_context.config` values which
contain all of the `Rails.configuration` values we know and love.
This commit ensures that components (and various helpers that may access
the `config` attribute) are able to access the Rails configuration
values. By delegating calls to `config`, we are able to access Rails
configuration values.
=> Ensure Rails configuration values are accessible in components

coverage/coverage.txt
Running `bundle exec rake` on fe8b6f24aa0635115e20920353a40b683b76cef7 (the current `HEAD` of the `master` branch) produced these changes in `coverage.txt` (despite there being no changes in my working directory).
It seems that 12e86669b8acf645ac565a674cdd736063636566 (the last commit of https://github.com/github/view_component/pull/358) removed 3 lines from `base.rb` which meant the line numbers in the coverage report were off by three for that file.
=> Align coverage.txt with the latest changes

CHANGELOG.md, lib/view_component/test_helpers.rb
https://github.com/github/view_component/issues/304#issuecomment-651419797 mentioned being annoyed by the warning about a missing capybara dependency in an application which uses view_component but not capybara.
My first instinct was to simply remove the warning. However, it still seems helpful for users who want to use the capybara assertions but are getting errors because they don't have a capybara dependency.
So, in this PR, I've adjusted it such that the warning is silenced unless the `DEBUG` environment variable is set. This seemed like a good compromise, since it seems reasonable that running tests with `DEBUG=1` may result in additional output for debugging purposes.
That said, I realize we aren't using the `DEBUG` environment variable elsewhere in the gem, so if we'd rather avoid …
=> Avoid printing the missing capybara dependency warning by default

lib/view_component/slotable.rb
In GitHub and in these tests the slots_component takes keyword
arguments, not `args`. The `args` variable needs to be double splatted
in the initalization caller.
The warnings can be seen when running the tests before this change was
introduced.
Fixes:
```
view_component/lib/view_component/slotable.rb:98: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
view_component/test/app/components/slots_component.rb:18: warning: The called method `initialize' is defined here
```
cc/ @joelhawksley
=> Fix kwargs in slotable

CHANGELOG.md, README.md, coverage/coverage.txt, lib/view_component/test_helpers.rb
Using `render_component` in the the `render_inline` test helper instead of `render` allows tests to pass on any version of Rails (>= 6.1 and < 6.1 with or without monkey patch always pass.
Without this fix, when running Rails < 6.1 without the monkey patch, using `render_inline`would result in tests failure.
Closes https://github.com/github/view_component/issues/396
=> Use render_component in render_inline test helper

CHANGELOG.md, README.md, app/controllers/view_components_controller.rb, coverage/coverage.txt, lib/view_component.rb, lib/view_component/preview.rb, lib/view_component/preview_template_error.rb, test/test/components/previews/inline_component_preview.rb, test/test/components/previews/inline_component_preview/inside_form.html.erb, test/test/components/previews/inline_component_preview/outside_form.html.erb, test/test/components/previews/inline_component_preview/with_haml.html.haml, test/test/components/previews/inline_component_preview/with_params.html.erb, test/test/components/previews/my_component_preview.rb, test/test/components/previews/my_component_preview/inside_banner.html.erb, test/test/components/previews/non_standard_path/test_template.html.haml, test/test/components/previews/non_standard_path/with_non_standard_template.html.erb, test/view_component/integration_test.rb
Fixes #338 (or at least trying to)
- Updated preview object to know about preview example templates
- Updated controller to render the actual preview example template if any
- Added specs
An example of usage would be:
`test/components/previews/cell_component_preview.rb`
```ruby
class CellComponentPreview < ViewComponent::Preview
def normal
render_with_template
end
end
```
`test/components/previews/cell_component_preview/normal.html.erb`
```erb
<table class="table">
<%= render CellComponent.new %>
</table>
```
Then the CellComponent preview would be available at the same path, but it will actually render the normal template.
=> [338] Previewing examples with contextual HTML

CHANGELOG.md, README.md, lib/rails/generators/erb/component_generator.rb, lib/rails/generators/haml/component_generator.rb, lib/rails/generators/slim/component_generator.rb, test/generators/erb_generator_test.rb, test/generators/haml_generator_test.rb, test/generators/slim_generator_test.rb
When generating a component using the `--sidecar` flag, the template will be placed in the sidecar directory.
This option is false (disabled) by default.
=> Add `--sidecar` to erb, haml and slim generators.

CHANGELOG.md, coverage/coverage.txt, lib/view_component/slotable.rb, test/view_component/integration_test.rb
While building a component that leveraged Slots,
we ran into an issue where it was difficult to not introduce
unintended whitespace in the rendered HTML for the component.
This change strips the rendered HTML for slots, so that
we don't end up with unintentional whitespace in the rendered
output.
Co-authored-by: Jason Long <jasonlong@github.com>
=> Slots return stripped HTML

CHANGELOG.md, coverage/coverage.txt, lib/view_component/slotable.rb, test/app/components/empty_slot_component.rb, test/app/views/integration_examples/empty_slot.html.erb, test/config/routes.rb, test/view_component/integration_test.rb
When rendering a slot with an empty block, capturing the block
returns nil, which does not respond_to `strip`.
This bug was introduced in https://github.com/github/view_component/pull/414, part of v2.17.0.
=> Fix bug where rendering Slot with empty block resulted in error.

CHANGELOG.md, README.md, coverage/coverage.txt, lib/view_component/base.rb
I don't think this will vary per instance but I'm really not familiar
with Rails' view rendering.
My, possibly flawed, micro-benchmarking suggests this'll get
ViewComponent a 5 time speed up. Those same benchmarks suggest this
takes ViewComponent from being a bit faster than partials to being much
faster :D. **N.B** This'll only have an impact when a view is rendering
many instances of the same component. Though now I say that ... it
might have an impact over time when class caching is turned on
in production mode, I haven't tested that.
Setup
=====
This is a sketch of what we've been using to bench:
require "benchmark/ips"
class ViewComponentPerformanceRenderer
def initialize
@controller = ViewComponent::Base.test_controller.constantize.new
@controller.request = …
=> Calculate virtual_path once for all instances

CHANGELOG.md, README.md, app/controllers/view_components_controller.rb, coverage/coverage.txt, lib/view_component/previewable.rb, test/test_helper.rb, test/view_component/default_preview_layout_integration_test.rb, test/view_component/integration_test.rb
I was digging a ton into component previews on a new project today, and I found myself wanting to use a custom layout (in my case `component_preview`) for all of the index pages as well as component preview pages. I started by monkey patching Rails::ApplicationController, but then realized I should simply adjust what's going on in ViewComponentsController, which gave me the idea for a configuration option and hence this PR.
This makes no behavioral change at all out-of-the-box. Everything will work as before. The only difference is if that `default_preview_layout` config option is set, the preview indices and components will pull that in rather than use the Rails internal app layout. Of course individual previews can still override the layout, including setting it to nil. (I also ended up …
=> Add default layout option in order to use app/views/layouts

CHANGELOG.md, README.md, coverage/coverage.txt, lib/view_component/engine.rb
Currently, the Rails server has to be manually restarted in order to pick up changes to view_component preview files. This is a bug. Auto-loading for previews worked before, but I believe it was inadvertently broken in e45338f.
This PR restores the auto-loading behavior for previews. Now if you make a change to a preview `.rb` file, the changes take effect without a server restart.
=> Fix auto-loading of previews

CHANGELOG.md, Gemfile.lock, lib/view_component/version.rb
=> Release v2.18.0

README.md
The configuration example for `default_preview_layout` was missing the `view_component` namespace.
Bumped into this when configuring previews. Thanks for a wonderful gem!
=> Fix default_preview_layout configuration example

README.md, lib/view_component/base.rb
Hi guys! 👋  
This time it's a small PR updating the Readme on having the component main class inside the same folder as other assets. As pointed out [here](https://github.com/github/view_component/pull/441#issuecomment-670805497)
The overall idea is to provide a small note to some folks trying to organize all their component code inside the same folder.
There's a [bonus commit](https://github.com/github/view_component/commit/c44ed5f13f4ea975fe04694e9d5d351364b4b474) fixing 2 small typos on `ViewComponent::Base#matching_views_in_source_location`
I'm always happy to work on feedback 😄
=> Update Readme for Component class inside Sidecar folder

README.md
This was returning the footer object rather than its content.
=> Fix Slot example template

README.md
This makes a small update to the slot example in the readme. I thought when trying to work with slots that the Header#class_names method was like the [helper `class_names`](https://blog.bigbinary.com/2020/02/04/rails-6-1-introduces-class_names-helper.html), so maybe I could use `super` in it, but this isn't the case. This renames the method and parameter so it's clear they're not connected to the `class_names` helper.
=> Update readme to improve slot example

.github/workflows/ruby_on_rails.yml
This PR changes our CI workflow to run rubocop before
running our test matrices, as:
1) It's unnecessary to run `rubocop` for each of our
FOURTEEN matrices!
2) If a workflow is going to fail due to linters, it's
a nicer developer experience to have that failure happen as quickly
as possible.
cc @manuelpuyol
=> lint before running tests

CHANGELOG.md, README.md, lib/view_component/base.rb, test/view_component/base_test.rb
As we only set view context during render, we cannot call into any view-context
objects like helpers or controllers.
Unfortunately the error is really obtuse, so this adds a proper exception to tell
the developer exactly what is going on
=> Raise errors if helpers/controller are called before render

.github/stale.yml
I'd like to be able to exempt more issues/PRs from stalebot.
Let's add these labels to do so.
=> add more exempt labels to stalebot

CHANGELOG.md, lib/view_component/version.rb
Bumps the version to 2.18.2
* Raise an error if controller or view context is accessed during initialize as they are only available in render.
*Julian Nadeau*
* Collate test coverage across CI builds, ensuring 100% test coverage.
*Joel Hawksley*
=> Bump to v2.18.2

CHANGELOG.md, lib/view_component/collection.rb
Fixes https://github.com/github/view_component/issues/461
When eager_load is disabled on Rails 6.1, `with_collection` will fail with the error `uninitialized constant ActionView::PartialIteration`. This was caused by Rails 6.1 moving ActionView::PartialIteration to `lib/action_view/renderer/collection_renderer.rb` which broke the autoloading
Since eager_load is typically enabled in production and tests, this error did was not reproducible in CI.
=> Fix uninitialized constant error from with_collection when eager_load is disabled

.github/lint/markdown.json, .github/workflows/ci.yml, CHANGELOG.md, CODE_OF_CONDUCT.md, README.md, docs/case-studies/jellyswitch.md
Add `markdownlint` to keep our markdown documents in tip-top shape, automatically!
Our README is getting pretty big, and I'd love to make it easier to keep it in good shape ❤️
=> lint markdown files

CHANGELOG.md, README.md
Extends the documentation for using Stimulus within view_component sidecar directories.
When using sidecar directories for your components, you might overlook the fact that Stimulus maps namespaced controllers using two dashes in its stimulus controller identifier.
=> Extend documentation for using Stimulus within sidecar directories

.github/workflows/ci.yml, Gemfile.lock, test/test_helper.rb
This PR changes our `simplecov` configuration to only run in CI, as our coverage is collated across our matrix of builds. It does so by checking for the `MEASURE_COVERAGE` environment variable, allowing coverage measurement to be flagged on locally if desired.
=> only run simplecov in CI

README.md, lib/rails/generators/test_unit/templates/component_test.rb.tt, test/view_component/default_preview_layout_integration_test.rb, test/view_component/integration_test.rb, test/view_component/test_unit_generator_test.rb
This PR standardizes our test syntax to use method names.
=> use def test_method_name syntax for tests

lib/view_component/preview.rb
Fixes a deprecation warning from Rails.
Previews [using templates](https://github.com/github/view_component#preview-templates) were passing a pathname with extensions causing
Rails to trigger a deprecation warning.
This PR fixes those deprecation warnings by removing the extensions from
the pathname of the template rendered in the controller.
The regex used can be read as:
1. `\.` an escaped dot character
2. `.*` anything after the previous dot
3. `$`  it must be at the end of the string
More info about the deprecation here https://github.com/rails/rails/commit/dd9991bac598bb5da312278a749cf85e19b027cc
=> Fixing deprecation warnings from Rails

CHANGELOG.md, lib/view_component/engine.rb
This prevents a non-existent directory from being added to `ActiveSupport::Dependencies.autoload_paths` when show_previews is enabled, which causes the following seemingly unrelated issue:
```
** ERROR: directory is already being watched! **
Directory: [omitted]
is already being watched through: [omitted]
MORE INFO: https://github.com/guard/listen/wiki/Duplicate-directory-errors
[...]
```
=> Don't add /test/components/previews preview path unless the directory exists

lib/view_component.rb, lib/view_component/base.rb, lib/view_component/compiler.rb, test/view_component/base_test.rb
This extracts the template compiling logic from the base class to help reduce
`ViewComponent::Base`s public API. This should hopefully make it easier to
modify the template compilation logic by separating it from the base class
logic.
There may be a breaking change or two hidden in this PR, such as
`ViewComponent::Base` no longer having `variants` defined on it. I don't think
that many components would have relied on that method being callable, but worth
discussing if it should be supported.
=> Extract template compiler from base

CHANGELOG.md, Gemfile.lock, lib/view_component/engine.rb
This PR disables the compiling of components on application initialization if `eager_load` is false.
cc @jhawthorn
=> Eager load compile

CHANGELOG.md, docs/index.md, lib/view_component/base.rb, test/app/components/inline_component.rb, test/view_component/view_component_test.rb
Resolves #319 
While rendering inline components without template files, unable to render variant `call` methods -- eg. `call_email` -- using the `#render :variants` option.
Non working example: 
```ruby
render(InlineComponent.new, variants: [:email])
```
Introduces the `#with_variant` instance method, which sets the variant to be rendered inline (with and without template).
=> Inline component variant bug

lib/view_component/base.rb
This changes `render` to always delegate to the current `view_context` for rendering. This allows us to use `view_context` for helpers instead of going through `view_context.controller` and instantiating a new view context.
This should help improve performance when rendering components that use helpers.
=> Always use current view context for helpers

lib/view_component/base.rb
Reverts github/view_component#519
In testing v2.22.0 with `primer_view_components`, this change caused the entire test suite to fail due to captured content being rendered out of place. 
Let's revert it so we can ship a stable build while we investigate further.
=> Revert "Always use current view context for helpers"

docs/index.md
Updates the `docs/index.md` to point to the correct link for the `benchmarks.rb`
=> Update doc link on benchmarks

docs/index.md
cc @jasonrudolph
Per @jasonrudolph, this PR adds an example of using `assert_text` to the docs.
=> add assert_text example

lib/view_component/base.rb
This fixes a warning that is thrown in Ruby 2.6 but not 2.7.
Extracted from the slots v2 branch.
=> Fix Ruby 2.6 variant warning

CHANGELOG.md, lib/rails/generators/component/templates/component.rb.tt
@joelhawksley how do you feel about this? I certainly can't think of a reason not to do. Perhaps not everyone adds this?
It's been around a while https://bugs.ruby-lang.org/issues/8976
=> Add frozen_string_literal to Component template

lib/view_component/base.rb, test/app/components/partial_component.html.erb, test/view_component/view_component_test.rb
Rendering partials inside a component, with an object as argument, fails in specific cases:
`render some_object`
What happens is, we fall into the else case here because the argument is an object.
https://github.com/github/view_component/blob/bbe48fc73ff85c1565f92575be6460aef474269c/lib/view_component/base.rb#L104-L110
This tries to render the partial, but within the context of the component. This works, but not if the server already rendered that partial in normal context. In that case, the template is found, but the compiled template method is defined on the original context as seen here:
https://github.com/rails/rails/blob/6f9d4a000b4394bb13daacb30003bc4010a60d23/actionview/lib/action_view/template.rb#L151-L158
```ruby
def render(view, locals, buffer = ActionView::OutputBuffer.new, …
```
=> Default to original view_context for anything that is not a ViewComponent

CHANGELOG.md, lib/view_component/version.rb
* Add `ActionView::SlotableV2`
* `with_slot` becomes `renders_one`.
* `with_slot collection: true` becomes `renders_many`.
* Slot definitions now accept either a component class, component class name, or a lambda instead of a `class_name:` keyword argument.
* Slots now support positional arguments.
* Slots no longer use the `content` attribute to render content, instead relying on `to_s`. e.g. `<%= my_slot %>`.
* Slot values are no longer set via the `slot` method, and instead use the name of the slot.
*Blake Williams*
* Add `frozen_string_literal: true` to generated component template.
*Max Beizer*
=> Bump to version 2.23.0

CHANGELOG.md, lib/view_component/slot_v2.rb, test/app/components/title_component.html.erb, test/app/components/title_component.rb, test/app/components/title_wrapper_component.html.erb, test/app/components/title_wrapper_component.rb, test/view_component/slotable_v2_test.rb
This resolves an issue where slots could be rendered out-of-order,
with similar results as the form object issue.
This resolves the issue by wrapping the component in a `capture` to
ensure no output is written to the output buffer at the wrong time.
Fixes https://github.com/github/view_component/issues/548
=> Fix out-of-order rendering issue with slots v2

.github/pull-request-template.md, CHANGELOG.md, CONTRIBUTING.md, docs/index.md
In the interest of using `welcoming and inclusive language` (see [CONTRIBUTING](https://github.com/github/view_component/blob/main/CODE_OF_CONDUCT.md#our-standards)), this PR updates our docs to reference `main` instead of `master`, as I've renamed our default branch as such ❤️
=> Rename `master` branch to `main`.

CHANGELOG.md, test/app/components/conditional_content_component.rb, test/view_component/view_component_test.rb
In #558 / #559, @virolea is proposing changes to how capturing content and `render?` work together. 
After reading the proposed changes, I realized that we have a conflicting use case in the GitHub.com codebase, where we have components that check for the presence of `content` in `render?`.
While I'm open to the proposed changes, I felt the need to document our current usage of this API so as to not accidentally introduce a breaking change.
=> add test case for rendering component only if content is provided

docs/index.md
This PR:
- Adds a note about how the `call_*` methods must be defined
Why?
- Lots of the methods that we define in components are private. This makes sure that we specifically note that they must be defined publicly.
=> Add note for defining `call_*` methods publicly to docs

docs/index.md
The benchmarks link on the GitHub Pages site at https://viewcomponent.org doesn't work as expected. It goes to https://viewcomponent.org/performance/benchmark.rb which 404s.
This branch makes the link go to the blob on the `main` branch instead: 
https://github.com/github/view_component/blob/main/performance/benchmark.rb
This seems like the simplest solution, but open to others if there's a preferred approach.
=> docs/index.md: Fix benchmarks link

lib/view_component/compiler.rb
While pairing with @joelhawksley , he noticed that there was a `nocov` block and we decided to try to remove it and fix the coverage gap. Looks like CI passes without it so 🔥 .
=> Remove no-cov from compiled_template call

CHANGELOG.md, lib/rails/generators/component/component_generator.rb, lib/rails/generators/component/templates/component.rb.tt, lib/rails/generators/erb/component_generator.rb, test/generators/component_generator_test.rb
added --inline as an option to generator which prevents creation of default erb template and adds a #call method to component 
Fixes #536
=> add --inline to generator to prevent default erb template creation

test/app/components/product_reader_oops_component.rb, test/view_component/integration_test.rb
When running `bundle exec rake` Ruby emits over a dozen lines of warnings which is pretty distracting.
This PR aims to clean up some if not all of those warnings.
=> Fix various warnings in test

docs/index.md
Link to the original slots v1 api docs was a 404. Hopefully this fixes it 🍔
=> Fix broken link to slots v1 docs

CHANGELOG.md, lib/view_component/base.rb, lib/view_component/compiler.rb, test/app/components/invalid_named_parameters_component.erb, test/app/components/invalid_named_parameters_component.rb, test/app/components/invalid_parameters_component.erb, test/app/components/invalid_parameters_component.rb, test/view_component/view_component_test.rb
Closes https://github.com/github/view_component/issues/580
Adds a validation on compile time that checks if any blacklisted arguments are used on the component `initialize`. At the moment, the only invalid argument name is `content` but it can be expanded
=> Validate component arguments

docs/index.md
There are quite a few occurrences of `TestComponent` and `MyComponent` in the docs.
To avoid confusion with the word "test" in the context of testing the components (which is mentioned in the docs as well), I suggest we always use `ExampleComponent` instead.
It also makes some of the paths (such as `test/components/previews/test_component_preview.rb`) easier to understand when using "example": `test/components/previews/example_component_preview.rb`
=> Docs: replace "test" and "my" with "example"

docs/index.md
Dot should be escaped in regular expressions, else it matches any character.
Also, variables are usually in camelCase.
=> Docs: escape dot in regexp + use camelCase in JS

CHANGELOG.md, docs/index.md, lib/view_component/base.rb, lib/view_component/compiler.rb, test/app/components/after_compile_component.rb, test/view_component/view_component_test.rb
This PR introduces the `after_compile` hook, allowing for components to define logic that should be executed when the component is compiled.
The compilation step is a critical part of the ViewComponent architecture that has previously been more or less invisible to the developer. I'm hoping that this hook is the first step towards allowing developers to leverage this powerful feature in new and exciting ways.
=> Call `.after_compile` class method after a component is compiled.

.github/workflows/ci.yml, docs/index.md
This PR adds a small note about using `assert_selector` with hidden elements, as its behavior has bit a few developers enough to warrant a warning here.
=> add note about assert_selector visibility

docs/index.md
The documentation (https://viewcomponent.org/) still references old preview path (`/rails/components` instead of `/rails/view_components`
=> fix: docs references to old preview path

docs/index.md
I noticed that ViewComponent no longer has validation support built-in, but [it's easily added](https://github.com/github/view_component/issues/206#issuecomment-602715364). I didn't see this in the documentation, so I added it.
Also, side-note: The docs are very difficult to read currently. I would recommend using something like [Gitbook](https://www.gitbook.com/) or similar to make them easier to navigate
=> Add docs for how to add validations

adr/0001-record-architecture-decisions.md
This adds a basic document that describes how we might make architectural decisions, and record such decisions for future reference.
=> docs(adr): add 001 Record Architecture Decisions

lib/view_component/collection.rb
This removes a call to `ViewComponent::Base#compile` from
`ViewComponent::Collection` since components should already be compiled
when their `render_in` method is called.
This saves us a decent amount of time when rendering a large number of
components.
=> Don't call compile in collections

CHANGELOG.md, lib/rails/generators/haml/component_generator.rb, lib/rails/generators/slim/component_generator.rb, test/generators/haml_generator_test.rb, test/generators/slim_generator_test.rb
In order to have feature parity for all supported templating languages, this add `--inline` support to Slim and Haml generators.
Close #625
=> Add support for `--inline` flag when generating Slim and Haml

CHANGELOG.md, lib/view_component/base.rb, lib/view_component/slotable.rb, lib/view_component/slotable_v2.rb, test/app/components/content_areas_predicate_component.rb, test/app/components/sleep_component.rb, test/app/components/slots_v2_render_predicate_component.rb, test/app/components/title_component.html.erb, test/app/components/title_component.rb, test/app/components/title_wrapper_component.html.erb, test/app/components/title_wrapper_component.rb, test/view_component/slotable_v2_test.rb, test/view_component/view_component_test.rb
This changes `content` to load only when a component's `render?`
predicate method returns true. The `render?` method can still access
`content`, which will cause it to be evaluated.
~This shouldn't be a breaking change for components themselves, but
attempting to access a slot in `before_render` or `render?` may no
longer work.~
This is an alternative approach to https://github.com/github/view_component/pull/559 (but doesn't remove the value of the conversation happening there, imo) and may at least partially close https://github.com/github/view_component/issues/558
=> Lazily evaluate content instead of eagerly evaluating it

lib/view_component/slot_v2.rb, test/app/components/slots_v2_without_content_block_component.html.erb, test/app/components/slots_v2_without_content_block_component.rb, test/view_component/slotable_v2_test.rb
When a slot was called without a content block, it raised a warning `warning: instance variable @_content_block not initialized`
This PR removes that warning by only passing the content_block to the slot if it is defined.
| Before | After |
|--------|--------|
| ![image](https://user-images.githubusercontent.com/11280312/108881934-74991d80-75c9-11eb-9eb2-961cc07a7c41.png) | ![image](https://user-images.githubusercontent.com/11280312/108881957-7b279500-75c9-11eb-9f74-1cc78d757c16.png) |
=> Remove warning when slot does not receive a content block

CHANGELOG.md, lib/view_component/base.rb, lib/view_component/compiler.rb, test/view_component/view_component_test.rb
This change removes the logic that removed and recreated the
`collection_parameter`, `collection_counter_parameter`, and
`counter_argument_present?` methods on each compile from the compiler.
I don't know the history behind this logic living in the compiler, but
it looks like we may be able to define these as class methods on
`ViewComponent::Base` directly.
Thanks to @mejackreed for reporting the issue and helping write a
failing test.
closes https://github.com/github/view_component/issues/642
=> Decouple collection parameters from compilation

CHANGELOG.md, docs/index.md, lib/rails/generators/preview/component_generator.rb, test/generators/component_generator_test.rb, test/test_helper.rb
First of all, I want to thank you all for this lovely gem. We have recently started adopting it over at Litmus and we are thrilled with what it enables our team with.
Something minor that we've noticed is that when generating components with the `--preview` flag, the preview file isn't placed in a custom preview path directory that we've defined.
e.g. With the following configuration:
```ruby
module MyProjectName
class Application < Rails::Application
config.load_defaults 6.0
config.view_component.preview_paths << Rails.root.join("spec", "components", "previews")
end
end
```
,,,we'd love for the file to be placed in `spec/components/previews/` when running something like:
```
$ bin/rails generate component Test --preview
```
I realized that the `preview_paths` config option could possibly …
=> Generate preview at overriden path if one exists when using `--preview` flag

CHANGELOG.md, docs/index.md, lib/view_component/base.rb, lib/view_component/test_helpers.rb, test/app/components/custom_test_controller_component.rb, test/app/controllers/custom_test_controller_controller.rb, test/view_component/view_component_test.rb
Sorry this took me so long to get back to @joelhawksley! Finally was able to spend some time here during the long weekend.
If you have different namespaces within your application, or possibly public and authenticated controllers, which change component functionality in specific ways, you can now configure a different controller in component tests.
Closes #440.
=> Allow customization of the controller used in component tests

docs/index.md
This PR adds a note about why nested URL helpers need their options to be provided explicitly, a source of confusion internally ❤️
=> add docs note about nested URL helpers

docs/content_areas.md, docs/index.md
As a step towards shipping ViewComponent V3, this PR updates our documentation to recommend the current implementation (V2) of Slots, moving the documentation for content_areas to a separate file.
=> update docs to feature Slots

CHANGELOG.md, lib/view_component/engine.rb
Given an application with a catchall route, previews are inaccessible, as they are _appended_ to the application's routes file.
_Prepend_ them instead.
I'd be curious if folks think this is worth testing. Doing so could be a bit of a hassle, but I'm up for the challenge 😅
=> Prepend preview routes instead of appending

CHANGELOG.md, docs/index.md, lib/view_component/base.rb, performance/components/slots_v2_component.rb, test/app/components/nested/slots_v2_component.rb, test/app/components/slim_renders_many_component.rb, test/app/components/slots_v2_before_render_component.rb, test/app/components/slots_v2_component.rb, test/app/components/slots_v2_delegate_component.rb, test/app/components/slots_v2_render_predicate_component.rb, test/app/components/slots_v2_with_pos_arg_component.rb, test/app/components/slots_v2_without_content_block_component.rb, test/app/components/title_component.rb, test/view_component/slotable_v2_test.rb
As a step towards deprecating `content_areas` and `Slots` v1, this change includes SlotableV2 by default.
=> include SlotableV2 in Base

CHANGELOG.md, lib/view_component/slotable_v2.rb, test/app/components/slots_v2_block_component.html.erb, test/app/components/slots_v2_block_component.rb, test/view_component/slotable_v2_test.rb
Currently blocks given to a lambda slot aren't always captured which can
cause them to be rendered incorrectly in certain rendering situations.
This fix resolves the issue by ensuring the block passed to the lambda
slot is always captured.
=> Ensure blocks passed to slots are captured

lib/view_component/base.rb
Just fixing `virutal` to `virtual` in a comment!
=> Fix a small typo in a comment in base.rb

CHANGELOG.md, Gemfile.lock, docs/index.md, lib/view_component/compiler.rb, test/app/components/jbuilder_component.json.jbuilder, test/app/components/jbuilder_component.rb, test/config/application.rb, test/view_component/view_component_test.rb, view_component.gemspec
I had the crazy idea of trying to use ViewComponent with a Jbuilder template today and noticed fairly quickly that it doesn't work, but not for any reason I would've thought.
Rails ships builder as an included template handler and with jbuilder installed that means that both `.builder` and `.jbuilder` are valid template extensions. ViewComponent will look for template files with either extension but will find any jbuilder template twice, because it matches both `*builder` and `*jbuilder`. Because it finds the template twice it raises an error and doesn't render.
In this pull request I add a call to uniq to ensure that ViewComponent continues with a list of template paths that doesn't have any duplicates. I use jbuilder as an example, but any template handler whose extension is a sub …
=> Fix handling of jbuilder templates

CHANGELOG.md, lib/view_component/base.rb, lib/view_component/compiler.rb, test/view_component/base_test.rb
This has been extracted from #660 but can actually be useful for supporting other types of sidecar assets.
The original method in the compiler was only referencing the component class, which is a good hint this method should rather live there.
=> Add Base.sidecar_files to fetch sidecar paths

CHANGELOG.md, docs/content_areas.md, docs/guide/slots.md, lib/view_component/base.rb
In anticipation of removing `with_content_areas` in ViewComponent v3, this PR adds a deprecation warning that encourages consumers to use slots (https://viewcomponent.org/guide/slots.html) instead.
=> deprecate `with_content_areas`

docs/guide/slots.md
When I am not include the `ViewComponent::SlotableV2` module，It raises the renders_many/renders_one method not found exception.
=> include ViewComponent::SlotableV2 module

docs/guide/slots.md
Since 2.28.0 slots are included by default, so this removes the `include
ViewComponent::SlotableV2` call in the docs and adds a note about
versions that will need to include the module.
=> Add note about when including slotable is necessary

docs/guide/slots.md
When I use renders_many by pass through slots, I got something like " [#<ViewComponent::SlotV2:0x000055a3482eb5f8 ....>]". My view_component's version was updated to 2.30.0
=> update renders_many in pass through slots

docs/content_areas.md
Hey there 👋 , I just discovered that the documentation for `content_areas.md` had a broken link.
=> fix link to "Slots" in content_areas.md

CHANGELOG.md, docs/guide/slots.md, lib/view_component/slotable.rb
Closes https://github.com/github/view_component/issues/621
Deprecates `with_slot` in favor of the new slots API https://viewcomponent.org/guide/slots.html
=> Deprecate `with_slot` API

CHANGELOG.md, lib/view_component/slotable_v2.rb, test/view_component/slotable_v2_test.rb
When registering a slot, it's possible to use an invalid name like
`:content` that can cause misleading behavior in components.
This change checks slot names when they're registered and raises if
they're invalid.
This adds `:content` as the only invalid slot name.
=> Prevent method name conflicts when using slots

CHANGELOG.md, lib/view_component/base.rb, test/app/components/asset_component.html.erb, test/view_component/view_component_test.rb
`ActionView::Helpers::AssetUrlHelper#compute_asset_host` will try to access the request with `respond_to?(:request)`, but since `#request` was defined as private and the protocol option is forced to be `:request` inside AV `#asset_url` it ended up trying to ask for a protocol on `nil`.
This only happens if the asset_host is set to a hostname without a defined protocol.
Ref:
- https://github.com/rails/rails/blob/v6.1.3.1/actionview/lib/action_view/helpers/asset_url_helper.rb#L277
- https://github.com/rails/rails/blob/v6.1.3.1/actionview/lib/action_view/helpers/asset_url_helper.rb#L231
We got a weird <code>undefined method `protocol' for nil:NilClass</code> error in production that pointed to a webpacker asset tag helper, the PR was migrating some partials to view_component.
It was pointing …
=> Ensure Base#request is available to ActionView asset helpers

CHANGELOG.md, lib/view_component/translatable.rb, performance/components/translatable_component.rb, performance/translatable_benchmark.rb, test/app/components/translatable_component.yml, test/config/locales/en.yml, test/view_component/translatable_test.rb
* Improve feature parity with Rails translations
* Don't create a translation backend if the component has no translation file
* Mark translation keys ending with `html` as HTML-safe
* Always convert keys to String
* Support multiple keys
While migrating from shared translations to `Translatable` in an application we run into problems related to the missing support for translation keys ending in `_html`.
Also we're including `Translatable` inside `ApplicationComponent`, doing this shouldn't affect memory after this change.
=> Increase feature-parity between Translatable and ActionView's TranslationHelper

.github/pull-request-template.md
This is partly reverting changes introduced in the commit 42a35a5. The link is broken since the commit d3288ea.
I've noticed this when opening my previous PR (#870).
=> Fix broken link (404) in pull request template

CHANGELOG.md, docs/guide/testing.md, lib/view_component/test_helpers.rb, test/app/components/url_for_component.html.erb, test/app/components/url_for_component.rb, test/view_component/view_component_test.rb
Hello dear ViewComponent people 👋
I think this is a bug, or I may use `link_to` the wrong way. Please let me know.
(See failing test)
Use `url_for` in a Rails `link_to` method:
```ruby
<%= link_to "Home", url_for(key: "value") %>
```
Should render something like this:
```html
<a href="/?key=value">Home</a>
```
It throws an error:
```
ViewComponentTest#test_render_link_to_with_url_for:
ActionController::UrlGenerationError: No route matches {:key=>"value"}
```
**Rails version**: 6.1.3.1
**Ruby version**: 3.0.1
**Gem version**: 2.30.0 (resp. master)
=> component with `link_to` with `url_for` throws `ActionController::UrlGenerationError`

CHANGELOG.md, docs/index.md, lib/view_component/compiler.rb
this was changed in https://github.com/github/view_component/pull/875/commits/6799a29af7daff334c34ccb0c6b26d2afd9d0e13,
but that causes deprecations when compiling ViewComponent::Base, which is
still allowed to call the before_render_check method
Fixes https://github.com/github/view_component/issues/886
Let me know if this seems good and needs a CHANGELOG entry.
=> move the deprecation warning below the template_errors check

.gitignore, CONTRIBUTING.md, Gemfile.lock, Rakefile, docs/api.md, lib/view_component/base.rb, view_component.gemspec
We don't have API-focused documentation. This PR aims to give us a basic system for generating it from YARD code comments, inspired by a similar approach we've taken in Primer ViewComponents.
=> Add basic API docs for instance methods, powered by YARD

test/app/components/display_inline_component.html.erb, test/app/components/display_inline_component.rb, test/test/components/previews/display_inline_component_preview.rb, test/test/components/previews/display_inline_component_preview/with_newline.html.erb, test/view_component/integration_test.rb
Test case for #913 
Adds a failing test that renders the same component twice in sequence to ensure they're not separated by a newline.
=> Add test for rendering component from template without newline

CHANGELOG.md, docs/api.md, lib/view_component/base.rb, test/app/components/after_render_component.rb, test/app/views/view_components/_inline.html.erb, test/view_component/view_component_test.rb
This PR adds an experiment `_after_render` method, as proposed in https://github.com/github/view_component/pull/677/files, for the sake of internal testing.
=> Add experimental `_output_postamble` method

docs/guide/previews.md
I thought it would be nice to present the command line argument to generate a preview again before the first examples for localhost are listed in case someone new comes directly to Previews before reading https://viewcomponent.org/guide/#quick-start.
I put the list of localhost URLs in a list
I fixed a typo where `the` should come after `preview`
=> Add preview command line, format change, fix typo

CHANGELOG.md, docs/index.md, lib/view_component/test_helpers.rb
Rails 7.0 deprecated writing to a session when the session is disabled
and defaults a session to a disabled session. https://github.com/rails/rails/pull/42231
In the past, ActionDispatch::TestRequest.create would set the
TestSession explicitly but this is not the case anymore and the default
session is used. With the PR mentioned above, this raises an exception
when testing view components that implement sessions.
=> Ensure session is set on request

.github/workflows/ci.yml
PVC hasn't passed consistently in a while which I think may be due to
not having the correct node modules installed.
This installs node in the pvc workflow, caches the `node_modules`
directory, and installs node modules to hopefully make the PVC tests
pass more consistently.
=> Install node modules for PVC test runs

CHANGELOG.md, lib/view_component/base.rb, test/app/components/empty_component.rb, test/view_component/view_component_test.rb
If a component or slot is empty and the rendering of the component returns `nil`, we would attempt to add the postamble to `nil`, which throws an exception:
```
undefined method `+' for nil:NilClass
```
Now we are explicitly coercing the result of the render to a string, to ensure it can be appended to.
Closes #937.
=> Coerce rendered component to a string even if nothing is rendered

.github/workflows/ci.yml
This PR ensures that there's a call to generate previews in the pvc workflow before the tests are run.
We [recently made updates in pvc](https://github.com/primer/view_components/pull/603) to auto-generate view component previews, which are used in one of our tests for accessibility.
=> Add previews generation to pvc workflow

CHANGELOG.md, docs/guide/collections.md, lib/view_component/base.rb, lib/view_component/collection.rb, test/app/components/collection_iteration_component.html.erb, test/app/components/collection_iteration_component.rb, test/app/components/product_component.html.erb, test/app/components/product_component.rb, test/view_component/view_component_test.rb
Closes #939
This adds support for a `{collection_name}_iteration` named parameter for the component initializer. It will automatically be populated with the current collection iteration object, which responds to methods: `first?`, `last?`, `index`, and `size`.
This keeps things more in line with Rails' own partial collection rendering, which exposes both a `{collection_name}_counter` and a `{collection_name}_iteration` local variable to the partials being rendered.
I added docs and a changelog entry in separate commits in case they weren't wanted.
=> Add `_iteration` parameter support to get access to collection iteration

docs/compatibility.md
Bridgetown v0.21 has been released, so this updates the link to the relevant documentation and slightly tweaks the description.
=> Update Bridgetown link in documentation

CHANGELOG.md, app/views/test_mailer/test_email.html.erb, lib/view_component/base.rb, test/app/components/mailer_component.html.erb, test/app/components/mailer_component.rb, test/app/mailers/test_mailer.rb, test/config/application.rb, test/config/environments/test.rb, test/view_component/mailer_test.rb
Fix for #940 - Error when using a component in a mailer view
ActionMailer controllers don't have a `#request`, so check to see that it exists before calling it.
=> Check for `#request` on the controller before attempting to call it

docs/api.md, lib/view_component/base.rb, test/generators/component_generator_test.rb, test/generators/erb_generator_test.rb, test/generators/haml_generator_test.rb, test/generators/slim_generator_test.rb, test/view_component/test_unit_generator_test.rb, test/view_component/view_component_test.rb
This PR adds documentation and a (missing 😱) test for `#with_variant`.
I also took the liberty of reconfiguring the generator specs to not create a `tmp` directory in the `test` folder, as it resulted in `bundle exec rake` running the generated tests on my machine.
=> add docs, test for #with_variant

CHANGELOG.md, docs/guide/instrumentation.md, docs/index.md, lib/view_component.rb, lib/view_component/engine.rb, lib/view_component/instrumentation.rb, test/app/components/instrumentation_component.html.erb, test/app/components/instrumentation_component.rb, test/view_component/instrumentation_test.rb
Closes #893
This PR adds a new configuration option `config.view_component.instrumentation_enabled`. When set true, ActiveSupport notification event `render.view_component` is enabled.
=> Add instrumentation

.github/workflows/ci.yml, CONTRIBUTING.md, Gemfile.lock, docs/compatibility.md, view_component.gemspec
I think it's time for us to move to Bundler v2. Having both
v1 and v2 in our CI workflow has been a source of headaches
and friction for some time. Seeing it trip up @boardfish
in https://github.com/github/view_component/pull/958 was
the last straw for me.
There are also now security concerns around Bundler v1
that to my knowledge are unresolved.
Removing Bundler v1 means that we can't easily test
Ruby 2.4 in CI. I'm OK with this, as we've never had a 2.4
compatibility issue caught by running against it.
=> use Bundler v2

CONTRIBUTING.md
In the interest of encouraging folks to contribute to ViewComponent,
I've outlined the current roles people generally fall into on the
project, along with some basic guidelines for how I think it might
make sense to manage membership of the project.
=> Add basic description of roles on the ViewComponent project

.yardopts, CHANGELOG.md, Gemfile.lock, Rakefile, docs/api.md, lib/view_component/base.rb, lib/view_component/compiler.rb, lib/view_component/previewable.rb, lib/yard/mattr_accessor_handler.rb, view_component.gemspec
This PR adds documentation for configuration options, generated using YARD.
I've reused some code @khiga8 wrote for Primer ViewComponents to extract `mattr_accessor`s.
I also took the liberty of sorting the existing instance methods alphabetically.
[Closes #953]
=> Dynamically generate configuration docs using YARD

docs/guide/sidecar_assets.md
When bootstrapping an app with `rails new --minimal` and installing Stimulus via `stimulus-rails`, this is the path to the file that needs to be changed.
There's not a linked issue for this - I saw the change and decided to propose it.
```
rails new --minimal -T=stimulus
```
=> Update Stimulus controller load folder reference

docs/CHANGELOG.md, docs/api.md, lib/rails/generators/abstract_generator.rb, lib/rails/generators/component/component_generator.rb, lib/rails/generators/erb/component_generator.rb, lib/rails/generators/haml/component_generator.rb, lib/rails/generators/slim/component_generator.rb, lib/view_component/base.rb, test/test_helper.rb
Another little refactor proposal that came up while working on #980...
Exposes the (recently added) `view_component_path` option as an attribute on `ViewComponent::Base`. This clarifies the config option as the single source of truth for the components path and makes it more readily accessible from other parts of the engine (it's currently only used in generators, but would be useful elsewhere). It also makes the value slightly easier to modify in tests, because it's not tied to initialization.
=> Add view_component_path option to ViewComponent::Base

Gemfile.lock, docs/CHANGELOG.md, view_component.gemspec
=> lock method_source at 1.0 to avoid open-ended dependency

Gemfile.lock, docs/CHANGELOG.md, view_component.gemspec
We already test view_component against edge rails (i.e. rails 7 alpha), but the `< 7.0` constraint (which is satisfied by `7.0.0.alpha` but not by `7.0.0`) would prevent the gem from being installed once the official rails 7.0.0 release comes out. Since we intend to support view_component on rails 7, let's bump the gemspec constraint to allow it.
=> Increase activesupport upper bound from `< 7.0` to `< 8.0`

.github/pull-request-template.md, README.md, docs/CHANGELOG.md, docs/CONTRIBUTING.md, view_component.gemspec
We moved these files into `docs/` in https://github.com/github/view_component/pull/972 but there were a few lingering references that still assumed they were in the repository root, including the `files` list in the gemspec which would've bundled a broken symlink instead of the actual CHANGELOG with the gem.
=> Fix references to documentation files that were moved into `docs/`

docs/CHANGELOG.md, lib/view_component/slotable_v2.rb, test/view_component/slotable_v2_test.rb
If `renders_many :contents` is called, you'd have to use the slot like this:
```html.erb
<%= render Component.new do |c| %>
<% c.content %>
<% end %>
```
Calling `content` here calls the private method `content` that already exists on the component.
Related to #976
=> Raise error on renders_many :contents

docs/CHANGELOG.md, lib/view_component/slotable_v2.rb, test/view_component/slotable_v2_test.rb
Rendering slot collections doesn't return the array of slots. This is asymmetric with the singular slot rendering and make it impossible to call methods like `with_content` on the rendered slots.
With this fix we can do things like this which previously would have raised an exception
```ruby
component.items([{ highlighted: false }, { highlighted: true }, { highlighted: false }])
.each_with_index do |slot, index|
slot.with_content("My Item #{index+1}")
end
```
=> Rendering slot collections returns the array of slots

docs/CHANGELOG.md, test/sandbox/app/components/controller_inline_with_block_component.html.erb, test/sandbox/app/components/controller_inline_with_block_component.rb, test/sandbox/app/controllers/integration_examples_controller.rb, test/sandbox/config/routes.rb, test/view_component/integration_test.rb
As part of investigation into #909, I wrote a failing test case. It checked that a block passed when rendering a component from the controller is used in the final render output.
We've got a workaround now by calling `#tap` on the component instance itself, so this test serves as documentation of that.
As mentioned on #909, the ability to use blocks in controller rendering was removed in 473beedb342bafc53557383f5a8c840c94645917. It's likely that this was why it wasn't then supported by Rails when it was implemented over there.
=> Add test case for controller rendering with block

docs/CHANGELOG.md, lib/view_component/slotable_v2.rb, test/view_component/slotable_v2_test.rb
Add three helper methods that allow introspection on what slots the component renders
```ruby
class SlotsV2Component < ViewComponent::Base
renders_one :header
renders_many :items
end
```
```ruby
SlotsV2Component.renders_one?(:header) # -> true
SlotsV2Component.renders_one?(:items) # -> false
SlotsV2Component.renders_one?(:item) # -> false
SlotsV2Component.renders_many?(:header) # -> false
SlotsV2Component.renders_many?(:items) # -> # true
SlotsV2Component.renders_many?(:item) # -> # false
SlotsV2Component.renders_many_item?(:header) # -> false
SlotsV2Component.renders_many_item?(:items) # -> # false
SlotsV2Component.renders_many_item?(:item) # -> # true
```
=> Add slot_type slotable helpers

docs/guide/templates.md
cc @paul
I've added a note to the Templates documentation to clarify that `variant` refers to ActionPack variants: https://guides.rubyonrails.org/layouts_and_rendering.html#the-variants-option.
=> add note about variants to templates docs

docs/CHANGELOG.md, docs/frequently-asked-questions.md, docs/index.md
In reviewing our internal documentation at GitHub, I found a
couple sections that I thought would be nice to add to the
framework documentation.
=> Update landing page to incorporate internal documentation

docs/CHANGELOG.md, docs/index.md
Fix a typo of the h1 end tag in documentation.
=> Fix typo in documentation

adr/0002-naming-conventions-for-view-components.md, docs/CHANGELOG.md, docs/guide/getting-started.md
This PR captures our decision in https://github.com/github/view_component/pull/1005 to not changing the naming conventions for ViewComponents.
=> Document decision not to change naming conventions

docs/CHANGELOG.md, docs/index.md, performance/benchmark.rb, performance/components/content_areas_component.rb, performance/components/global_i18n_component.rb, performance/components/name_component.rb, performance/components/slot_component.html.erb, performance/components/slot_component.rb, performance/components/slots_v2_component.rb, performance/components/translatable_component.rb, performance/slotable_benchmark.rb, performance/translatable_benchmark.rb
Fixes #1025 
Since the test sandbox application was moved, the benchmark scripts have not been working. This fixes the scripts by requiring files from the new location, as well as namespacing the components so that the classes do not conflict with components defined in the sandbox.
`bundle exec rake benchmark`:
```
Warming up --------------------------------------
component:    14.902k i/100ms
partial:     1.814k i/100ms
Calculating -------------------------------------
component:    149.116k (± 4.0%) i/s -      1.490M in  10.011986s
partial:     17.640k (± 9.2%) i/s -    175.958k in  10.068436s
Comparison:
component::   149115.6 i/s
partial::    17639.6 i/s - 8.45x  (± 0.00) slower
```
`bundle exec rake translatable_benchmark`:
```
Warming up --------------------------------------
global …
```
=> Fix benchmark scripts

docs/CHANGELOG.md, docs/index.md, performance/benchmark.rb, performance/components/inline_component.rb
After trying to run some benchmarks to compare components that use an ERB file with components that use a `call` method, I discussed the results here: https://github.com/github/view_component/discussions/1014
It was then considered if we should add this example to the benchmark script, so I have raised this PR in case you want it included.
Here are the benchmark results after this change:
```
Warming up --------------------------------------
component:    14.495k i/100ms
inline:    13.457k i/100ms
partial:     1.770k i/100ms
Calculating -------------------------------------
component:    150.094k (± 4.5%) i/s -      1.507M in  10.064767s
inline:    184.791k (± 4.5%) i/s -      1.857M in  10.071958s
partial:     18.655k (± 4.8%) i/s -    187.620k in  10.081517s
Comparison:
inline:: …
```
=> Add inline template example to benchmark script

docs/CONTRIBUTING.md
Leading "/" required in the link to search parent directory for LICENSE.txt.
LICENSE.txt lives in /main. Without the leading "/" in the link to the license, it's searching the /main/docs/ folder. No current GitHub issues to reference.
=> Fixed link to project's open source license

Gemfile.lock, docs/CHANGELOG.md, lib/view_component/version.rb
* Add `--stimulus` flag to the component generator. Generates a Stimulus controller alongside the component.
* Add config option `config.view_component.generate_stimulus_controller` to always generate a Stimulus controller.
*Sebastien Auriault*
=> release 2.38.0

docs/CHANGELOG.md, lib/view_component/base.rb
Deprecates `Base#with_variant`. Variants are an often misunderstood feature that use the Action Pack variant information present in the request (i.e. phone, tablet, etc) to render a component differently depending on the requesting device. Normally one passes in a list of acceptable variants in an Action View template, eg:
```ruby
render(MyComponent.new, variants: [:phone, :tablet])
```
The variant can be overridden by calling `#with_variant` on the component, eg:
```ruby
class MyComponent < ViewComponent::Base
def call
render(OtherComponent.new.with_variant(:tablet))
end
end
```
It's important to note that these are two distinct `render` functions (the second does not accept a `:variants` option). Since components don't have access to the request object, it doesn't really make sense for …
=> Deprecate Base#with_variant

docs/CHANGELOG.md, docs/guide/collections.md, docs/guide/conditional_rendering.md, docs/guide/generators.md, docs/guide/getting-started.md, docs/guide/helpers.md, docs/guide/index.md, docs/guide/instrumentation.md, docs/guide/javascript_and_css.md, docs/guide/lifecycle.md, docs/guide/previews.md, docs/guide/slots.md, docs/guide/templates.md, docs/guide/testing.md, docs/guide/translations.md
This PR:
1) Renames `sidecar assets` to `Javascript and CSS` to make it easier to find.
2) Renames `Building ViewComponents` to `Guide` to match the URL for this section. It also doesn't cover much about actually building ViewComponents, something we should try to improve in future documentation.
=> Docs cleanups

.github/workflows/ci.yml, docs/CHANGELOG.md
Regenerating the API docs can be easily forgotten whenever creating/updating YARD comments. With the CI, this can be prevented.
I based the new job on the existing `benchmark` job.
Committing the changes in the API docs could be done, but I think it's better to let the PR submitter handle this since it can vary from a PR to another depending on the number of commits.
=> Error out in the CI if docs/api.md has to be regenerated

docs/CHANGELOG.md, docs/guide/testing.md
This re-frames the anti-pattern section of the docs as best practices. I think this may help convey the intentions behind the documentation.
=> Replace antipatterns with best practices

docs/CHANGELOG.md, lib/view_component/slot_v2.rb, test/sandbox/app/components/empty_slot_v2_with_slim_component.html.slim, test/sandbox/app/components/empty_slot_v2_with_slim_component.rb, test/sandbox/app/views/integration_examples/empty_slot_v2_with_slim.html.slim, test/sandbox/config/routes.rb, test/view_component/integration_test.rb, test/view_component/slotable_v2_test.rb
Closes #1044 
When using `slim-rails` (and probably other temple-based languages), it's possible that a block defined in a Slim view evaluates to `nil`. When that block gets processed in a SlotV2's `to_s` method, that `nil` from the block can end up as the return value.
Returning `nil` from a call to `to_s` doesn't make sense and causes errors to be raised when rendering the view, so this patch prevents that from happening and instead returns an empty string.
I don't think the test I included is a good way to test this, but I can't think of a way to get the "real" issue to happen. `render_inline` doesn't raise an error like a Rails app using Slim will, because the temple gem used by Slim is what's raising the actual error I'm seeing in our app.
Perhaps instead of the test, I can include a …
=> Prevent nil from being returned from a Slot V2's to_s method

.github/lint/markdown.json, Rakefile, docs/CHANGELOG.md, docs/api.md, lib/view_component/test_helpers.rb
This PR introduces preliminary API documentation for `ViewComponent::TestHelpers`.
=> Add basic documentation for test helpers

docs/CHANGELOG.md, docs/guide/testing.md, docs/index.md, lib/view_component/test_helpers.rb, test/sandbox/app/components/url_for_component.html.erb, test/view_component/view_component_test.rb
Query parameters were ignored when using the `with_request_url` test helper. With these changes, that's no longer the case :smile:.
My knowledge of the internals of Rails routing is very limited, so if there's a more elegant solution than using `set_header` and `parse_query`, please let me know! :wink:
=> Allow query parameters in `with_request_url`

docs/CHANGELOG.md, docs/frequently-asked-questions.md
It's not obvious that you cannot use `render` or `render_to_string` to render a ViewComponent from inside a controller action.
The `#render_in` method is private, but I can't find any other way to achieve this. I think it's a good idea to mention this in the FAQ (especially to help people debug `AbstractController::DoubleRenderError`), but maybe add a disclaimer? Or consider making the method public?
=> Add "how to render a component to a string" to FAQ

docs/CHANGELOG.md, docs/api.md, lib/view_component/base.rb
Removed the `@private` YARD tag in order for the `#render_in` instance method to appear in the API docs.
Continued from https://github.com/github/view_component/pull/1068?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDI0MDIyMDE5MjE6Mzg1MjQ%3D#issuecomment-918589884
=> Add #render_in to API docs

docs/CHANGELOG.md, docs/guide/testing.md, docs/index.md
This PR add an explanation to the docs about accessing Devise's helper methods in component specs. It is based on an issue https://github.com/github/view_component/issues/70
=> Update testing docs with explanation about Devise

lib/rails/generators/component/component_generator.rb, lib/view_component/base.rb, test/generators/component_generator_test.rb
(Continued from #1073)
I found an edge case: when you both have `ApplicationComponent` defined in your project and configure a `component_parent_class`, `ApplicationComponent` was always used.
I added more tests, fixed the issue and refactored `ComponentGenerator#parent_class`.
=> Generator --parent option: add more tests and fix edge case

docs/guide/previews.md
I suggest we add a link to Lookbook in the docs, as it's a great Ruby alternative to Storybook.
- [Lookbook](https://github.com/allmarkedup/lookbook)
- [Discussion about Lookbook](https://github.com/github/view_component/discussions/1006)
=> Preview docs: add link to Lookbook

docs/CHANGELOG.md, lib/view_component/slot_v2.rb
It looks like Ruby is warning about the indentation of this file in my editor. This can also be seen via running `ruby -w lib/view_component/slot_v2.rb`
=> Fix indentation of end in slot_v2.rb

docs/CHANGELOG.md, lib/view_component/engine.rb
See related issue #1112 
The call to `ActionDispatch::MiddlewareStack#insert_before` expected an instance of `ActionDispatch::Static` being present in the middleware stack.
Calling `ActionDispatch::MiddlewareStack#use` instead will instead append `ActionDispatch::Static`-middleware to the "end" of the middleware stack without any dependency.
=> engine.rb: Change ActionDispatch::MiddlewareStack#insert_before -> #use

docs/CHANGELOG.md, docs/guide/getting-started.md, lib/view_component.rb
Currently anyone using the framework has to require `view_component/engine` manually, usually by putting `gem "view_component", require: "view_component/engine"` in the Gemfile or requiring it specifically in application.rb. Forgetting to do so can lead to weird reloading problems and other subtle issues as evidenced in #560.
This PR adds the relevant `require` to avoid these issues.
=> Require engine automatically

docs/CHANGELOG.md, lib/rails/generators/stimulus/component_generator.rb, test/generators/stimulus_generator_test.rb
<details><summary>
Running `bin/rails generate stimulus:component` results in an error:
</summary>
```bash
> bin/rails g stimulus:component
Running via Spring preloader in process 54655
[WARNING] Could not load generator "rails/generators/stimulus/component_generator". Error: uninitialized constant ViewComponent::AbstractGenerator
Did you mean?  AbstractController.
/Users/peter/Code/view_component/lib/rails/generators/stimulus/component_generator.rb:8:in `<class:ComponentGenerator>'
/Users/peter/Code/view_component/lib/rails/generators/stimulus/component_generator.rb:7:in `<module:Generators>'
/Users/peter/Code/view_component/lib/rails/generators/stimulus/component_generator.rb:6:in `<module:Stimulus>'
/Users/peter/Code/view_component/lib/rails/generators/stimulus/component_generator.rb:5: …
```
=> Add require to load AbstractGenerator for Stimulus generator

.github/CODEOWNERS, docs/CHANGELOG.md
This PR adds a CODEOWNERS file to auto-request reviews for a few key feature areas built by ViewComponent committers.
=> add CODEOWNERS file

docs/CHANGELOG.md, lib/view_component/polymorphic_slots.rb
Like regular slot getters, polymorphic getters don't take any arguments and therefore don't need a call to `ruby2_keywords`. The warning emitted is causing CI issues in github/github.
=> Remove unnecessary ruby2_keywords in polymorphic slots code

docs/CHANGELOG.md, docs/index.md
Adds Litmus to list of teams using ViewComponent with a link to the Litmus Engineering blog (currently being redesigned into a more comprehensive site about how we work, job openings, etc).
=> Add Litmus to users

docs/CHANGELOG.md, lib/view_component/engine.rb
Currently, we can show preview codes in component previews if it enables `show_previews_code` option.
However, the change of preview class's code is not applied to screen without app server restart.
It's not convenient, isn't it?
So I configured to clear cache in `MethodSource` per request using `to_prepare` block.
For example, suppose you have a code like the following:
```ruby
class FooComponentPreview < ViewComponent::Preview
def default
render(FooComponent.new)
end
end
```
In preview, it will display like this:
Then, change the code while the server is running. 
```diff
class FooComponentPreview < ViewComponent::Preview
def default
+     # This is comment
render(FooComponent.new)
end
end
```
Unfortunately, this change will not apply until we restart the server.
With this fix, the code …
=> Clear cache in MethodSource to apply the change of preview code without app server restart

docs/CHANGELOG.md, test/generators/component_generator_test.rb, test/generators/erb_generator_test.rb, test/generators/haml_generator_test.rb, test/generators/slim_generator_test.rb, test/generators/stimulus_generator_test.rb
`require "rails/generators/test_case"` is called from rails/test_help on railtie gem. So we don't need to call them on each test files, removed them.
https://github.com/rails/rails/blob/5-2-stable/railties/lib/rails/test_help.rb#L11
---
In the process of following up on #1147, I noticed it while reading the code and opened a pull request. If you feel this is just like cosmetic change, would you please close it :pray:
=> Remove `require "rails/generators/test_case"` in generator tests

docs/CHANGELOG.md, docs/guide/slots.md
I emailed @joelhawksley after discovering #1031 with @ollie-nye, since I'd identified some patterns in how folks are using slots. The aim of this PR is to make it clearer that slots render content and don't pass data.
This might make the docs a little more verbose and revert some of #956 by reintroducing passthrough slots as an official term, but I think that's important to make the distinction.
I also removed the comment under lambda slots stating that they "render the returned string". This isn't 100% true, because a component can also be the return value of a lambda slot's lambda, and that gets rendered in.
=> Increase clarity around purpose and use of slots

docs/CHANGELOG.md, docs/index.md
Adding [Orbit](https://orbit.love) to the list of teams using ViewComponent
Hey! We’re very happy users of ViewComponent at Orbit.
We’ve been using them for about a year and wrote about our [ViewComponent/Storybook setup](https://orbit.love/blog/building-a-component-library-in-rails-with-storybook) as well as a [primer on Storybook for Rails developers](https://orbit.love/blog/im-a-rails-developer-what-the-heck-is-storybook-and-should-i-care). We’re now in the process of building a design system with it, and the Primer repository as well as [this Rails Conf talk](https://youtu.be/QoetqsBCsbE) by Joel have been an invaluable help!
=> Add Orbit to the list of teams using ViewComponent

docs/CHANGELOG.md
PR #1162 was merged in d24b26ae2697685e930d863839d7f8834b9ca4a3 which was released in [v2.46.0], but its `CHANGELOG.me` entry had not been moved above the `## v2.45.0` entry in https://github.com/github/view_component/commit/a5f6463f36639e7385a9c905801e18e41b6b6538. Thus, it was incorrectly listed as being included in [v2.45.0].
Let's make sure it's listed under the correct version in `CHANGELOG.md`. And based on #1180, let's make it clear in the release notes what folks need to do to
resolve the deprecation warning after they upgrade.
[v2.45.0]: https://github.com/github/view_component/releases/tag/v2.45.0
[v2.46.0]: https://github.com/github/view_component/releases/tag/v2.46.0
=> Move changelog entry for #1162 to the right version

docs/CHANGELOG.md, docs/known_issues.md, test/sandbox/app/components/default_form_builder_component.html.erb, test/sandbox/app/components/default_form_builder_component.rb, test/sandbox/app/controllers/default_form_builder_controller.rb, test/view_component/view_component_test.rb
When form helpers are called directly, the default form builder is not used and must be specified. For example, calling this:
```
<%= fields do |f| %>
<%= f.text_field :hello_world %>
<% end %>
```
does not use the default form builder. Either manually specifying the `builder:` argument to `fields` or calling `helpers.fields` (as I have in the tests here) works, though.
I feel that this is a little unintuitive - it's odd that form helpers do work directly within ViewComponent but do not inherit the default form builder specified by the controller. I feel that they should either raise an error or be delegated to `helpers` by default.
=> Add failing test for default form builder

docs/CHANGELOG.md, docs/CONTRIBUTING.md
When debugging #971, I found the `CONTRIBUTING.md` docs to be lacking instructions on how to run tests locally for a specific version of Rails. I tried to improve this.
=> Improve instructions on how to run tests

.github/workflows/lint.yml, docs/CHANGELOG.md
Vale action output contains a warning:
```
Warning: User-specified path (**/*) is invalid; falling back to 'all'.
```
Default is already `all`: https://github.com/errata-ai/vale-action#files-default-all
I removed the `files` options which is not needed.
=> Remove broken `files` options from vale config

docs/CHANGELOG.md, docs/index.md, lib/view_component/test_helpers.rb
I found out my IDE (Intellij IDEA) tells me my code is not compatible with `#render_inline` when I pass an instance of `ViewComponent::Collection`. As far as I see, `#render_inline` seems to allow us to receive an instance of `ViewComponent::Collection` because it defines `#render_in` method internally.
So, I want to add `ViewComponent::Collection` to `@param` of `#render_inline`.
I updated `docs/CHANGELOG.md` and `docs/index.md`, following [Submitting a pull request](https://github.com/github/view_component/blob/d7bf301fe90d169bc2ff96dff7dd4dbc5454398a/docs/CONTRIBUTING.md#submitting-a-pull-request).
=> Add ViewComponent::Collection to @param of #render_inline

docs/CHANGELOG.md, docs/guide/generators.md
In CI, Vale complains about the use of `in order to` and recommends replacing it with `to`.
That's it.
=> Fix style in generator docs

Appraisals, docs/CHANGELOG.md, docs/index.md, gemfiles/rails_6.0.gemfile, gemfiles/rails_6.1.gemfile, gemfiles/rails_7.0.gemfile, gemfiles/rails_head.gemfile, lib/rails/generators/tailwindcss/component_generator.rb, lib/rails/generators/tailwindcss/templates/component.html.erb.tt, test/generators/component_generator_test.rb, test/generators/tailwindcss_generator_test.rb
This commit adds support for [tailwindcss-rails](https://github.com/rails/tailwindcss-rails) engine.
This is my first contribution so I hope I did this correctly.
I've spinend up demo app with `view_component` and `tailwindcss-rails`and it works.
But, I may have missed something :)
=> Support component generator for tailwindcss-rails

docs/CHANGELOG.md, docs/resources.md
This PR adds a link to [Lookbook](https://github.com/allmarkedup/lookbook) into the Resources page in the documentation.
People seem to be finding it useful but it would be great to get more people trying it out, so a link from here would be much appreciated :-)
=> Add Lookbook to Resources docs page

docs/CHANGELOG.md, docs/resources.md
The GOV.UK Components library now has a guide, the old page has been removed.
=> Update the GOV.UK Components URL to new guide

.github/workflows/ci.yml
This was broken due to a change in Primer ViewComponents which now
requires running yarn in the docs directory to build the docs.
See https://github.com/primer/view_components/pull/970
[Example failed run](https://github.com/github/view_component/runs/4801553969?check_suite_focus=true)
=> Fix PVC CI

docs/CHANGELOG.md, docs/CONTRIBUTING.md
The test files are in `test/view_component` now; this fixes the example to reflect that.
=> Correct path in example test command

Gemfile.lock, docs/CHANGELOG.md, lib/view_component/version.rb
```
* Correct path in example test command in Contributing docs.
*Mark Wilkinson*
* Update link to GOV.UK Components library in the resources list.
*Peter Yates*
* Add Lookbook to Resources docs page.
*Mark Perkins*
* Add blocking compiler mode for use in Rails development and testing modes, improving thread safety.
*Horia Radu*
* Add generators to support `tailwindcss-rails`.
*Dino Maric*, *Hans Lemuet*
* Add a namespaced component example to docs.
*Hans Lemuet*
* Setup `Appraisal` to add flexibility when testing ViewComponent against multiple Rails versions.
*Hans Lemuet*
* Return correct values for `request.path` and `request.query_string` methods when using the `with_request_url` test helper.
*Vasiliy Matyushin*
* Improve style in generators docs.
*Hans Lemuet*
* Correctly type Ruby …
```
=> release 2.48.0

docs/CHANGELOG.md, docs/guide/previews.md, docs/index.md
When trying to get previews working I didn't realize that the `preview_paths` config setting had to be updated when working with rspec. I eventually found this on the `testing` page but I thought it would be better to colocate this with the preview docs because at this point I wasn't at the testing stage.
=> Updating preview page of docs to mention rspec

docs/CHANGELOG.md, lib/view_component/translatable.rb
Closes #1264 
This appears to be because efforts were taken to stop `i18n` unnecessarily calling `deep_symbolize_keys`.
=> Ensure i18n_scope is a symbol to protect lookups

docs/CHANGELOG.md, lib/view_component/translatable.rb, test/view_component/translatable_test.rb
Previously the default value would have taken precedence over the
global translation fallback.
=> Fix support for the `default:` option for a global translation

docs/CHANGELOG.md, lib/view_component/base.rb, test/view_component/base_test.rb
This prevents getting a nil absolute_path for code executed inside of an eval
Absolute path is not always available on your callers, but path is more likely to be available. This especially fixes files that are evaluated which in ruby 3.1 never have absolute paths after this change in ruby: https://github.com/ruby/ruby/commit/64ac984129a7a4645efe5ac57c168ef880b479b2
=> Use path instead of absolute_path for inside eval

.github/CODEOWNERS, Rakefile, docs/CHANGELOG.md, docs/api.md, docs/guide/generators.md, lib/rails/generators/abstract_generator.rb, lib/rails/generators/component/component_generator.rb, lib/rails/generators/locale/component_generator.rb, lib/view_component/base.rb, lib/view_component/docs_builder_component.html.erb, lib/view_component/docs_builder_component.rb, lib/view_component/rails/tasks/view_component.rake, test/generators/locale_generator_test.rb, test/test_helper.rb, test/view_component/view_component_test.rb
Closes #1229 by placing all config options linked to generators under the `generate` config option. Behind the scenes, this uses [`ActiveSupport::OrderedOptions`](https://api.rubyonrails.org/classes/ActiveSupport/OrderedOptions.html), which inherits from `Hash` to provide method accessors. Like `Hash`, this can be initialized with a default value, which has been set to `false` to reflect the existing behavior - all config options are `false` except for `component_path`.
TODO:
=> Place all generator options under `generate` config option

docs/CHANGELOG.md, lib/rails/generators/preview/templates/component_preview.rb.tt, lib/rails/generators/rspec/templates/component_spec.rb.tt, lib/rails/generators/test_unit/templates/component_test.rb.tt
As @boardfish evoked in https://github.com/github/view_component/pull/1194#issuecomment-1036405220:
> it's relatively safe to say that generated components will be new code in new apps, which are likely to default to `frozen_string_literal: true`
Here are the generated .rb files updated to comply with ViewComponent self coding style.
=> Add frozen_string_literal statement to all generated .rb files

.rubocop.yml, app/helpers/preview_helper.rb, docs/CHANGELOG.md, lib/view_component/preview.rb, lib/view_component/slotable_v2.rb, test/sandbox/app/components/jbuilder_component.json.jbuilder, test/view_component/slotable_v2_test.rb, test/view_component/tasks_test.rb
This fixes the following warnings that are output when running the tests:
```
/home/runner/work/view_component/view_component/lib/view_component/slotable_v2.rb:279: warning: shadowing outer local variable - args
/home/runner/work/view_component/view_component/app/helpers/preview_helper.rb:30: warning: shadowing outer local variable - template
/home/runner/work/view_component/view_component/test/sandbox/app/components/jbuilder_component.json.jbuilder:1: warning: `frozen_string_literal' is ignored after any tokens
/home/runner/work/view_component/view_component/test/view_component/slotable_v2_test.rb:481: warning: shadowing outer local variable - c
/home/runner/work/view_component/view_component/test/view_component/tasks_test.rb:16: warning: ambiguous first argument; put parentheses or a …
```
=> Fix shadowing outer local variable and other warnings

.rubocop.yml, docs/CHANGELOG.md, lib/view_component.rb, lib/view_component/base.rb, lib/view_component/compiler.rb, lib/view_component/content_areas.rb, lib/view_component/deprecation.rb, lib/view_component/engine.rb, lib/view_component/polymorphic_slots.rb, lib/view_component/slotable.rb, script/release, test/sandbox/app/components/jbuilder_component.json.jbuilder, test/test_helper.rb
This should allow consumers to see deprecation warnings that correctly mention the next version of VC.
Silencing is already a feature of AS::Deprecation
Closes #586 and closes #1273 (this was built starting from those PRs).
=> Add ViewComponent::Deprecation

docs/CHANGELOG.md, docs/guide/slots.md, lib/view_component/slotable_v2.rb, test/sandbox/app/components/slots_v2_component.html.erb, test/view_component/slotable_v2_test.rb
This implements predicate methods for slots, as described in #1275.
- Do you think it's possible / a good idea to try to warn users when they define a `#{slot_name}?` method themselves, so they notice that the library now provide this feature?
Close #1275
=> Predicate methods for slots

docs/CHANGELOG.md, docs/api.md, lib/rails/generators/component/component_generator.rb, lib/rails/generators/preview/component_generator.rb, lib/rails/generators/preview/templates/component_preview.rb.tt, lib/view_component/base.rb, test/generators/component_generator_test.rb, test/generators/preview_generator_test.rb
This PR allows the preview generator to get the provided component generator attributes.
Why?
Because, the default generated preview when passing attributes is not valid and fails tests, and it's not cool to generate failing tests files. ;)
This PR move preview generator tests to its own file as for other generators.
A config option has been added too, in order to enable project-wide preview generation.
=> Allow passing component attributes to preview generator

docs/CHANGELOG.md, performance/benchmark.rb, performance/components/inline_component.rb, performance/components/name_component.html.erb, performance/components/name_component.rb, performance/components/nested_name_component.html.erb, performance/components/nested_name_component.rb, performance/views/benchmarks/_nested.html.erb, performance/views/benchmarks/_partial.html.erb
Previously we would render a single component or a single partial from a
controller context to benchmark performance. This is valid, but isn't as
realistic as rendering more components/partials inside the rendering
path.
This updates the benchmarks to render multiple of the renderer type
being benchmarked in an attempt to get closer to simulating a real page
load.
* Updates both components to render another component 50 times
* Updates partial to render another partial 50 times
=> Update benchmarks to render more than a single time

docs/CHANGELOG.md, lib/view_component/translatable.rb, test/sandbox/app/components/translatable_component.yml, test/view_component/translatable_test.rb
When i18n finds a YAML array as a value, it returns the Array as is. ActionView allows this, and the `#translate` helper in AV will correctly handle "HTML-safe" keys when the value is an Array, by calling `#html_safe` on each element.
However, ViewComponent assumes translations can only be strings, and raises an error when this is not the case.
This PR lifts the code from ActionView to handle HTML-safe translations so we can correctly escape both strings and arrays, to avoid surprising anyone that is extracting components from existing views that depend on this AV behavior.
=> Support returning arrays from translations

docs/CHANGELOG.md, lib/view_component/base.rb, test/view_component/view_component_test.rb
Fixes #1315
The performance improvement introduced in #1302 moves template compilation to the `#render_template_for` method, which runs the compiler and calls the re-defined version of `#render_template_for` the compiler creates. However, because the original implementation resides on `ViewComponent::Base`, parent classes that are rendered before their children will hide the version of `#render_template_for` that performs the compilation. Rendering any subsequent child instances actually renders the parent's template instead.
It's worth noting that this problem will only appear if Rails eager loading is disabled, i.e. when using "lazy loading." Eager loading is turned on by default in production environments, so the problem only affects the development and test environments.
This PR makes …
=> Fix inheritance when lazy loading

Appraisals, docs/CHANGELOG.md
Appraisal does not set the Ruby version, allowing developers to
run our tests with incompatible combinations of Ruby and Rails.
This change opts Rails 5.2 out of Ruby >=3.0.
Closes #1326.
Co-authored-by: Blake Williams <blakewilliams@github.com>
Co-authored-by: Cameron Dutro <camertron@github.com>
=> Fix bug where Appraisal ran incompatible combination of Ruby and Rails

.github/workflows/ci.yml, docs/CHANGELOG.md, lib/view_component/base.rb, lib/view_component/slotable_v2.rb, test/test_helper.rb
This adds support for a new env variable, `RAISE_ON_WARNING` which when
set to true causes warnings emitted in the test environment to raise
an exception.
This also enables RAISE_ON_WARNING in CI.
closes https://github.com/github/view_component/issues/1351
=> Raise when ViewComponent causes a warning

docs/CHANGELOG.md, docs/guide/templates.md, lib/view_component/base.rb, test/sandbox/app/components/super_base_component.html.erb, test/sandbox/app/components/super_base_component.rb, test/sandbox/app/components/super_component.html.erb, test/sandbox/app/components/super_component.rb, test/view_component/view_component_test.rb
Although perhaps not a common pattern, it is possible to call `super` in a derived component to render the parent's template:
```html+erb
<%# base_component.html.erb %>
<div>Content from base component</div>
<%# derived_component.html.erb %>
<div>Content from derived component</div>
<% super %>
```
```ruby
class BaseComponent < ViewComponent::Base
end
class DerivedComponent < BaseComponent
end
```
Rendering `DerivedComponent` results in the following, as expected:
```html
<div>Content from derived component</div>
<div>Content from base component</div>
```
Unfortunately however it is very tempting to echo the result of `super` out to the page, eg. `<%= super %>` instead of `<% super %>`, which leads to double rendering both components.
This PR introduces a new `render_parent` method that …
=> Add render_parent helper method to avoid double-rendering hijinks

docs/CHANGELOG.md, docs/index.md
From conversation during RailsConf22, adding G2 to the list of ViewComponent users.
Followed previous approaches, small style/content change, but open to suggestions for better implementation (I'm assuming we are shooting for alphabetical sorts in the contribs/companies that use section).
=> Add g2 to ViewComponent Users

docs/CHANGELOG.md, docs/index.md, lib/view_component/test_helpers.rb, test/sandbox/test/rendering_test.rb
Hey, when using the `#with_request_url` test helper, nested parameters are currently parsed as a string key:
**Current Behaviour**
```ruby
with_request_url "/?order[id]=asc" do
assert_equal request.parameters["order[id]"], "asc"
end
```
The common behaviour in e.g. Rails is to parse the nested URL parameters into hashes. I ran into this issue today, since it's different to how the params are parsed in the actual request.
**New behaviour**
```ruby
with_request_url "/?order[id]=asc" do
assert_equal request.parameters["order"], {"id" => "asc"}
end
```
=> Test helper `#with_request_url` parses nested query parameters

docs/CHANGELOG.md, lib/view_component/base.rb, test/sandbox/app/components/renders_non_component.html.erb, test/sandbox/app/components/renders_non_component.rb, test/sandbox/test/rendering_test.rb
I ran into an issue in [primer/rails_forms](https://github.com/primer/rails_forms) when attempting to render a form inside a component. The form should render in the component's view context instead of the original action_view context. Unfortunately the `render` method in `ViewComponent::Base` renders anything that's not explicitly a view component (i.e. inherits from `ViewComponent::Base`) in the original action_view context.
I modified `ViewComponent::Base#render` to render anything that responds to `render_in` in the component's view context. I also considered adding a flag to `render_in` to specify the desired view context, but I decided against it because it means the caller has to know an awful lot about the architecture of the view layer.
I realize I'm just trading one assumption …
=> Allow anything that responds to render_in to be rendered in the component's view context

docs/CHANGELOG.md, script/release
Currently script/release does not increment versions according to the semver spec. For example, if the current version is 2.56.2 and the developer chooses to release a new minor version, script/release will attempt to release 2.57.2 when it should release 2.57.0.
I modified script/release to reset the patch version to zero if a minor version bump is requested.
=> Fix script/release so it honors semver

docs/CHANGELOG.md, docs/guide/slots.md
I'm trying to fix a silly mistake I made a number of months ago.
I added several missing `do` keywords to the ERB example in the polymorphic slots docs.
=> Fix syntax errors in polymorphic slots docs

docs/CHANGELOG.md, docs/api.md, lib/view_component/base.rb, lib/view_component/collection.rb, test/sandbox/app/components/nested_collection_component.html.erb, test/sandbox/app/components/nested_collection_component.rb, test/sandbox/app/components/nested_collection_wrapper_component.html.erb, test/sandbox/app/components/nested_collection_wrapper_component.rb, test/sandbox/app/components/renders_non_component.rb, test/sandbox/test/rendering_test.rb
Fixes https://github.com/github/view_component/issues/1390
A recent change introduced in https://github.com/github/view_component/pull/1385 broke helper methods when rendering collections, eg:
```erb
<%# app/components/some_parent_component.html.erb %>
<%= render(ProductComponent.with_collection(@products)) %>
```
```erb
<%# app/components/product_component.html.erb %>
<%= helpers.my_helper_method %>
```
PR #1385 changed `ViewComponent::Base#render` to render anything that responds to `#render_in` in the parent component's view context. Collections respond to `#render_in` but, unlike regular view components, don't retain a reference to the original `ActionView::Base` view context. This means that the `helpers` method returns `nil` and leads to `NoMethodErrors`.
I decided anything that …
=> Fix issue causing NoMethodErrors when calling helper methods from components rendered as part of a collection.

docs/CHANGELOG.md, docs/guide/slots.md, lib/view_component/base.rb, lib/view_component/polymorphic_slots.rb, test/sandbox/app/components/polymorphic_slot_component.rb
The polymorphic slots feature has baked for a while and appears to be stable. Pending any concerns raised in [this discussion](https://github.com/github/view_component/discussions/1398), I think it's time to include it in `ViewComponent::Base` by default.
Simply `include`ing the module in `ViewComponent` base does the trick. There's no need to wait for v3 because the changes introduced by polymorphic slots are strictly additive.
=> Include polymorphic slots behavior by default

docs/CHANGELOG.md, lib/view_component/polymorphic_slots.rb
Add a missing space in between words.
I was able to add the space, but I didn't find a matching failing spec. Perusing the specs, this doesn't appear to be the type of requirement which has matching specs, so I have omitted them as well.
**Before**
`DEPRECATION WARNING: polymorphic slot setters like `title_text` are deprecated and will be removed inViewComponent v3.0.0.`
**After**
`DEPRECATION WARNING: polymorphic slot setters like `title_text` are deprecated and will be removed in ViewComponent v3.0.0.`
=> Add a missing space in a deprecation warning message

docs/CHANGELOG.md, docs/guide/getting-started.md, docs/index.md
Added information about working with turbo-rails when rendering from controllers, on getting started guide.
Close #1440 
When using **turbo-rails** with **view_components**, and rendering a `ViewComponent` in the `Controller` on `#create`, the response has content type `text/vnd.turbo-stream.html`. This causes turbo frames to not update.
Just added information to use the `content_type: "text/html"` when working with **turbo-rails**.
=> Docs: add information about turbo-rails

docs/CHANGELOG.md, lib/view_component/slotable_v2.rb
`renders_many` refers to itself as `render_many` in its documentation.
Fixed the typo.
Nope.
=> Fix typo in `renders_many` documentation

Gemfile.lock, docs/CHANGELOG.md, lib/view_component/compiler.rb, test/sandbox/app/components/content_eval_component.rb, test/sandbox/test/rendering_test.rb, view_component.gemspec
Currently there's a deadlock in the compiler due to rendering locking,
which can lead to edgecases where other locks prevent the completion of
rendering and the inability to complete rendering prevents other locks
from releasing as seen in https://github.com/github/view_component/issues/1447
This resolves the issue by replacing `Monitor` with a `ReadWriteLock`.
This allows the same component to render without requiring an exclusive
lock, resulting in concurrent renders.
In summary:
- Compilation will hold a write lock, blocking `#compile` and
`render_template_for` calls.
- `render_template_for` calls will hold a read lock, blocking `#compile`
but allowing other calls to `render_template_for` to check out another
read lock.
See the documentation for `ReadWriteLock` for more details: …
=> Fix compiler deadlock

docs/CHANGELOG.md, lib/view_component/slotable_v2.rb, test/sandbox/test/slotable_v2_test.rb
Before this change it was possible to define Slots with conflicting names, for example:
```ruby
class MyComponent < ViewComponent::Base
renders_one :item
renders_many :items
end
```
=> Raise `ArgumentError` when conflicting slots are defined.

docs/CHANGELOG.md, docs/index.md, lib/view_component/test_helpers.rb, test/sandbox/test/rendering_test.rb
`#with_request_url` is great. It was started in #1058, but later #1221
introduced a tiny regression in the parsing of segments.
When using `#with_request_url` including a query string, the `#path`
helper would now contain the query string segment, when it should not.
This led to `#fullpath` having the query string twice.
I added regression tests to the existing scenarios and then fixed the parsing to make them pass. :)
I love this library. 😍
=> Fix request.path inside with_request_url helper

app/controllers/concerns/view_component/preview_actions.rb, app/helpers/preview_helper.rb, app/views/view_components/preview.html.erb, docs/CHANGELOG.md, lib/rails/generators/abstract_generator.rb, lib/rails/generators/component/component_generator.rb, lib/rails/generators/locale/component_generator.rb, lib/rails/generators/preview/component_generator.rb, lib/view_component/base.rb, lib/view_component/engine.rb, test/sandbox/test/integration_test.rb, test/test_helper.rb
Tests are in place to ensure that `Rails.application.config.view_component` refers to the same thing.
Closes #1464 
It seems that gems that use ViewComponent as a dependency might be doing things before Rails has set up an application. In that case, it makes sense to set up a config on `ViewComponent::Base` and have `Rails.application.config` reference that.
Ideally, we want to be 100% sure that configuring ViewComponent via `Rails.application.config.view_component` and `ViewComponent::Base.config` has the same effect. Gem dependencies should use the latter, while users might want to prefer the former.
=> Use ViewComponent::Base.config as the internal endpoint for config

docs/CHANGELOG.md, lib/view_component/slotable_v2.rb, test/sandbox/test/rendering_test.rb
The current logging for slot name deprecation warnings displays the file in which the deprecation warning is called. To be more useful in finding and correcting deprecations, this PR adjusts the stack trace output to reflect the location of the named slot call.
The [core `ActiveSupport::Deprecation#warn` method implementation](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/deprecation/reporting.rb#L18-L29) includes a call to `caller_locations(2)`. This returns the location of the deprecation call, instead of the location where the slot is used. 
To correct the issue, `caller_locations(3)` is called from within the slotable deprecation check, adding the corrected stack trace to the `Deprecation#warn` call. 
I chose to add two new tests instead of adjusting the …
=> Adjust stack trace in slot name deprecation warning output

README.md
Make the README logo light mode / dark mode friendly (it has initially been done in #1169 but this approach is now deprecated)
The new recommended approach: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to
=> Update logo code in README

README.md
Reverts github/view_component#1475
The logo is not showing in Github mobile app, so let's revert this until this is fixed.
=> Revert "Update logo code in README"

docs/CHANGELOG.md, docs/index.md
We just launched a new version of the product and used VC to build out our design system components (w/ Stimulus + Tailwind)
=> Add Arrows to list of companies using VC

docs/CHANGELOG.md, docs/index.md
On Twitter, @LynxEyes and @chalmagean pointed out that our claims about testability of Rails views are not true: https://twitter.com/Lynx_Eyes/status/1561277373823307777
I think this updated language is more appropriate :heart:
=> clarify wording around testability of rails views

docs/CHANGELOG.md, docs/CODE_OF_CONDUCT.md, docs/CONTRIBUTING.md, docs/adrs/0001-record-architecture-decisions.md, docs/adrs/0002-naming-conventions-for-view-components.md, docs/adrs/0003-polymorphic-slot-definitions.md, docs/adrs/0004-slots-separate-getter-setter.md, docs/adrs/index.md, docs/api.md, docs/compatibility.md, docs/guide/collections.md, docs/guide/conditional_rendering.md, docs/guide/generators.md, docs/guide/getting-started.md, docs/guide/helpers.md, docs/guide/index.md, docs/guide/instrumentation.md, docs/guide/javascript_and_css.md, docs/guide/lifecycle.md, docs/guide/previews.md, docs/guide/slots.md, docs/guide/templates.md, docs/guide/testing.md, docs/guide/translations.md, docs/history.md, docs/known_issues.md, docs/logo.md, docs/resources.md, docs/viewcomponents-at-github.md
I'm re-attempting to land https://github.com/github/view_component/pull/1470, but in a simpler form, exposing our ADRs in the docs.
I moved them to the `docs` folder. I also renamed the sidebar items for clarity.
=> Add ADRs to docs

docs/CHANGELOG.md, docs/index.md
Add [Clio](https://www.clio.com/) to the list of companies using ViewComponent. 🎉 
Opening a PR to the repo is the current recommended way to add to the list of companies.
This maintains alphabetical ordering.
=> Add Clio to the list of companies using ViewComponent

docs/CHANGELOG.md, docs/guide/slots.md
I recently ran into an issue using slots in view components that I think could save other people some time in the future by adding how to solve it to the documentation. Shoutout to @joelhawksley for showing me how to properly accomplish this!
I added an example that I think follows the theme of the rest of the doc to describe how to use before_render.
Can I use class_names in the example here? And is it a good idea to reference the lifecycle.md page as well?
=> Update slots to reference before_render

docs/CHANGELOG.md, docs/CONTRIBUTING.md, docs/guide/previews.md, docs/guide/slots.md, lib/view_component/test_helpers.rb, test/sandbox/app/components/my_component.html.erb, test/sandbox/test/components/my_component_test.rb, test/sandbox/test/components/previews/my_component_preview.rb
I'm adding the ability to pass parameters to `render_preview` so that previews can be better leveraged in unit tests.
I added an optional `params` key to `render_preview`. I opted not to accept bare kwargs as doing so would limit our ability to add other keyword arguments in the future.
=> render_preview can pass parameters to preview

docs/CHANGELOG.md, view_component.gemspec
Since #1472, we cannot confirm source code url from rubygems. So, it added `metadata["source_code_uri"]` in gemspec.
Not in particular.
Not in particular.
=> Add source_code_uri to gemspec

docs/CHANGELOG.md, docs/index.md
The Performance section to the Docs links to a benchmark script. The script was recently renamed to `partial_benchmark.rb`: https://github.com/ViewComponent/view_component/commits/main/performance/partial_benchmark.rb
This PR updates the link!
Edited the markdown with the new link.
Nope!
=> Docs: Update link to benchmark script

docs/CHANGELOG.md, docs/index.md, lib/view_component/slotable_v2.rb, test/sandbox/test/slotable_v2_test.rb
As proposed in #1498, this PR adds a special error message when calling `renders_one :content`. 
The new error message looks like this:
```
ArgumentError: ExampleComponent declares a slot named content, which is a reserved word in the ViewComponent framework.
Content passed to a ViewComponent as a block is captured and assigned to the `content` accessor without having to create an explicit slot.
To fix this issue, either use the `content` accessor directly or choose a different name.
```
`content` is already very similar to a slot, so suggesting to the user that it may do what they want seems like a nice idea to help them improve their code.
I decided to add the special case above the general case in `validate_singular_slot_name`, instead of somehow generalizing it. I also didn't touch …
=> Add special case for `renders_one :content`

docs/CHANGELOG.md, lib/view_component/compiler.rb
We are deprecating support for Ruby < 2.7 in the coming ViewComponent release: https://github.com/ViewComponent/view_component/issues/617
I added a deprecation warning to the component compiler as I thought it would be fairly visible here.
=> Deprecate support for Ruby < 2.7

docs/CHANGELOG.md, docs/guide/generators.md
The documentation about [placing the view in a sidecar](https://viewcomponent.org/guide/generators.html#place-the-view-in-a-sidecar-directory) contains a mistake when describing how to set this as a default. The config documentation contained a underscore where a dot is needed. See also [lib/rails/generators/abstract_generator.rb:45](https://github.com/ViewComponent/view_component/blob/e8365e52c3cf7c84d896eb969e39d1854a27c413/lib/rails/generators/abstract_generator.rb#L45). This pull request fixes the documentation.
=> Fix default sidecar generation documentation

.github/workflows/ci.yml, docs/CHANGELOG.md
Our existing CI configuration runs a 17-build matrix for the main test suite. I think this is overkill for our needs. In my experience, our matrix builds have mainly served us by testing each version of Rails and Ruby we support, *not* every *combination* of Ruby and Rails we support. I think we can get by with just 5 builds.
=> Simplify CI configuration to a single build per Ruby/Rails version.

docs/CHANGELOG.md, docs/index.md
Add PrintReleaf to list of who uses ViewComponent
Added PrintReleaf and link to site to the docs. PrintReleaf started using ViewComponent about a month ago and has already implemented over 20+ components allowing us to remove logic from our views and greatly increase our test coverage.
Thanks for helping us improve our code base with such a great tool!
=> Add PrintReleaf to list of who uses ViewComponent

docs/CHANGELOG.md, lib/view_component/base.rb, lib/view_component/compiler.rb, lib/view_component/translatable.rb, test/sandbox/app/components/after_render_component.rb, test/sandbox/test/base_test.rb, test/sandbox/test/translatable_test.rb
Promote remaining experimental APIs to public methods.
I renamed the existing private APIs for `_sidecar_files` and `_output_postamble` to remove the underscore. As these were experimental/private APIs, this is not a breaking SemVer change.
=> Promote experimental APIs to public

.github/workflows/ci.yml, docs/CHANGELOG.md
I made a [recent change](https://github.com/primer/view_components/pull/1553) to PVC that speeds up our accessibility tests by running them in parallel. To get things running, I had to wrangle access to larger actions runners for the Primer org. The regular actions runners available to free orgs like ViewComponent only have 2 CPU cores, which isn't enough to run even two parallel test workers (2 server processes + test process). To avoid resource contention, view_component should continue to run PVC's accessibility tests in a single process.
This PR effectively disables parallel test execution for PVC tests by setting the `PARALLEL_WORKERS` environment variable to 1.
=> Avoid running PVC tests in parallel

docs/CHANGELOG.md, docs/index.md
Moving an older codebase to use View Component. Works really well together with Tailwind CSS
=> Add startup.jobs to list of ViewComponent users

.github/workflows/ci.yml, docs/CHANGELOG.md
Our PVC test runs have been [failing recently](https://github.com/ViewComponent/view_component/actions/runs/3441193868/jobs/5740477527) in CI. This PR should fix things.
PVC [migrated](https://github.com/primer/view_components/pull/1388) away from Yarn in favor of npm a few months ago, but view_component's CI scripts were never updated. Don't ask me why, but using npm fixes the test issues.
The linting issues should be fixed by [this PR](https://github.com/ViewComponent/view_component/pull/1576).
=> Use npm instead of yarn to install PVC dependencies

.github/workflows/lint.yml
This follows on from [my earlier PR where I applied the updated linting rules](https://github.com/ViewComponent/view_component/pull/1576).
@CamerTron made an excellent point that `bundle install` with a checked-in Gemfile.lock results in laggy feedback about breaking changes in upstream packages.
And @BlakeWilliams made an excellent point that tooling like `standardrb` is not technically "breaking changes."
Theoretically, this should please both Blake and Cameron, as we continue to run `bundle update` in CI as part of the ["Build and test with Rake" github
action](https://github.com/ViewComponent/view_component/blob/2cfe54fdd81f8c2f9f79b7d1e4148a2ce3cfdb9c/.github/workflows/ci.yml#L51-L55), while using `bundle install` in the lint action, thus releasing the `standardrb` canary from it's …
=> Prevent `standardrb` from breaking CI unless its version is bumped directly

docs/CHANGELOG.md, lib/view_component/compiler.rb, test/sandbox/app/components/variants_component.html+mini-watch.erb, test/sandbox/app/components/variants_component.html+mini.watch.erb, test/sandbox/test/rendering_test.rb
Just like we were implementing multitenancy in our application, using variants with subdomain names (see #1570), we're planning to support variants with domain names. However, ViewComponent defines methods dynamically with `def call_#{variant}`, which results in invalid Ruby code if the variant contains a dot.
As mentioned during the [pull request #1570 review](https://github.com/ViewComponent/view_component/pull/1570#discussion_r1024405549), it looks like [Bundler converts dots to triple underscores in environment variables names](https://bundler.io/man/bundle-config.1.html#CONFIGURE-BUNDLER-DIRECTORIES). The same principle was used in #1570 to replace dashes with double underscores.
=> Support variants with dots in their names

docs/CHANGELOG.md, docs/guide/templates.md, lib/view_component.rb, lib/view_component/base.rb, lib/view_component/engine.rb, lib/view_component/test_helpers.rb, test/sandbox/test/base_test.rb, test/sandbox/test/rendering_test.rb
This PR removes more deprecated functionality for V3:
* BREAKING: Remove deprecated support for loading ViewComponent engine manually.
* BREAKING: Remove deprecated `generate_*` methods. Use `generate.*` instead.
* BREAKING: Remove deprecated `with_variant` method.
* BREAKING: Remove deprecated `rendered_component` in favor of `rendered_content`.
=> Remove more deprecations for V3

docs/CHANGELOG.md, docs/guide/testing.md
Adding setup instructions for utilizing the [newly added JS testing approach](https://github.com/ViewComponent/view_component/pull/1061) when using RSpec. Without these configurations, using the `with_rendered_component_path` would not work.
This was sparked by a comment left here - https://github.com/ViewComponent/view_component/pull/1061#issuecomment-1347567212
N/A
This is assuming Capybara is being used in RSpec setup, which is common. This may need some updates once we want to include instructions that don't rely on Capybara.
=> Add documentation to utilize JS testing for RSpec

docs/CHANGELOG.md, lib/view_component/compiler.rb, lib/view_component/engine.rb
Fixes https://github.com/ViewComponent/view_component/issues/1608
Prevent a deprecation notice on every compile of every component.
Move the deprecation notice to the `engine.rb` file. As it already had another deprecation notice (the require thing)
Nope
=> Move Ruby 2.7 deprecation to engine.rb

app/controllers/concerns/view_component/preview_actions.rb, app/controllers/view_components_system_test_controller.rb, docs/CHANGELOG.md, lib/view_component/engine.rb
This PR aims to address an issue discovered in https://github.com/ViewComponent/view_component/pull/1606#issuecomment-1349640678 in which adding authentication to the previews controller causes the JS testing approach to not work. The solution we agreed upon in https://github.com/ViewComponent/view_component/pull/1606#issuecomment-1351728446 is to move the `_system_test_endpoint` into its own controller, since it isn't related to previews.
This approach was taken because it seemed the easiest and safest way to get the desired outcome.
N/A
=> Move system test endpoint out of preview controller to avoid issues when previews have authentication

.standard.yml, docs/CHANGELOG.md, lib/view_component/test_helpers.rb, test/sandbox/test/rendering_test.rb
Our `render_in_view_context` test helper uses `instance_exec` to evaluate the given block in the view context. Since `instance_exec` changes the value of `self`, instance variables, methods, etc defined in the caller's context are not available inside the block, which can be pretty confusing. For example, consider this test:
```ruby
class MyTest < Minitest::Test
def setup
@user = create(:user)
end
def test_my_component
render_in_view_context do
render(MyComponent.new(@user))
end
end
end
```
As a direct result of using `instance_exec`, `@user` will be `nil` inside the block.
Presumably to provide an escape hatch for this problem, `instance_exec` forwards its arguments when calling the block. This PR modifies `render_in_view_context` to forward _its_ arguments to `instance_exec`, so this is …
=> Make render_in_view_context forward its args to the block

docs/CHANGELOG.md, lib/view_component/test_helpers.rb
[This change](https://github.com/rails/rails/pull/46916) was recently merged into Rails main that changes the way `ActionController::Base#response=` works. Unfortunately it breaks our preview controller. This PR should fix it.
The change linked above defines `response=` which explicitly sets `@_response_body` to `true`. Doing so [prevents the controller](https://github.com/rails/rails/blob/2e28ae403d9247181220b8a79273f953a892df69/actionpack/lib/action_controller/metal/rendering.rb#L137) from rendering any other response. This then prevents rendering any previews.
=> Preview controller fix for recent Rails main change

app/controllers/view_components_system_test_controller.rb, docs/CHANGELOG.md, docs/index.md, test/sandbox/app/views/layouts/application.html.erb, test/sandbox/test/view_component_system_test.rb
Fixes #1618
This PR fixes an issue where using the `with_rendered_component_path` helper with a custom layout results in that layout being nested in the body of the [default `Rails::ApplicationController` layout](https://github.com/rails/rails/blob/main/railties/lib/rails/templates/layouts/application.html.erb).
This also fixes another issue where layouts with script or stylesheet tags were being blocked by Content Secure Policy:
...because `Rails::ApplicationController` includes a CSP header, which means that only layouts with inline scripts are allowed by CSP:
```rb
content_security_policy do |policy|
policy.script_src :self, :unsafe_inline
policy.style_src :self, :unsafe_inline
end
```
The approach I took was to have the `ViewComponentsSystemTestController` inherit from …
=> Fix layout nesting in system tests when using `with_rendered_component_path` with custom layouts

.rubocop.yml
This removes errors from rubocop in editors due to `.rubocop.yml` not being present and falling back to defaults.
Here's the before pic:
After looks as expected (no errors on `main`).
=> Add rubocop config

docs/CHANGELOG.md, docs/index.md, lib/view_component/rails/tasks/view_component.rake, test/sandbox/test/rake_tasks_test.rb
Running `rake stats` in a Rails app that's using `view_component` may fail if the app is not bootable in the current environment (e.g. CI). That differs from the behavior of `rake stats` if `view_component` is not installed
The reason is that the gem hooks its own setup task as a dependency of the `stats` task and prepended task itself depends on `environment`, thus introducing `environment` as a transitive dependency of `stats`.
What's more it doesn't seem there's a reason for adding this dependency (at least I can't see one).
My goal is to restore the behavior of stats being runnable even if the app is not bootable.
The specific problem we hit arising from this is that we run `rake stats` as CI step which started breaking once we introduced `view_component` because we have initializers …
=> Remove `evironment` dependency of rake task `view_component:statsetup`

docs/CHANGELOG.md, lib/view_component/base.rb, lib/view_component/engine.rb, test/sandbox/config/application.rb, test/sandbox/config/initializers/zzz_complete_initialization.rb
This un-reverts the revert of #1528. I was unable to reproduce the Sorbet issue that caused us to revert, and there are a lot of good reasons to avoid loading `ActionView::Base` during initialization.
All credit goes to @jdelStrother for the implementation.
=> Avoid loading ActionView::Base during initialization

docs/CHANGELOG.md, lib/view_component/system_test_helpers.rb, lib/view_component/test_helpers.rb, test/sandbox/app/components/render_check_component.html.erb, test/sandbox/app/components/render_check_component.rb, test/sandbox/test/integration_test.rb, test/sandbox/test/rendering_test.rb, test/sandbox/test/test_helper_test.rb, test/test_helper.rb
In #1641, @jacob-carlborg-apoex provided a test case showing how our private #controller method can create confusion when writing tests. This PR renames our private methods to avoid such conflicts. I've opted for a narrower solution than the one proposed in #1646.
Closes #1641, #1646
=> Rename private TestHelpers methods

app/controllers/view_components_system_test_controller.rb, docs/CHANGELOG.md, docs/index.md, lib/view_component/system_test_helpers.rb, test/sandbox/test/integration_test.rb, test/sandbox/test/view_component_system_test.rb
Resolves https://github.com/ViewComponent/view_component/issues/1663. When a file path is passed to `ViewComponentsSystemTestController` it will ensure that the path exists and is within `/tmp/view_components/`. It will also raise an error if run outside of a test environment.
One thing I can't quickly figure out is how to get the test to pass properly 😅 It raises the error as expected, but I think the Rails App is catching the error instead of passing it to Minitest. It says nothing was raised ... then says the test failed because an error was raised.
```
Failure:
ViewComponentSystemTest#test_path_traversal_raises_error:
ArgumentError expected but nothing was raised.
Error:
ViewComponentSystemTest#test_path_traversal_raises_error:
ArgumentError: Invalid file path
```
See …
=> Protect against Arbitrary File Read in System Test Controller

docs/CHANGELOG.md, lib/view_component/system_test_helpers.rb, lib/view_component/test_helpers.rb, test/sandbox/test/rendering_test.rb, test/sandbox/test/test_helper_test.rb
In https://github.com/ViewComponent/view_component/pull/1661, I renamed several private TestHelper methods to indicate that they should not be used by consumers.
However, we depended on the `controller` method in the GitHub.com test suite. I've chosen to reintroduce this method with new name, as we originally made it private due to it conflicting with folks setting a `controller` method name in tests.
=> Add TestHelpers#vc_test_controller

docs/CHANGELOG.md, docs/guide/generators.md
The previous configurations are not working any more. The `generate_....` notation was replaced with a `generate. ...` object.
Fixing the shown configurations.
Only replacing the not working configurations with working ones.
nope
=> Fix generate configuration

docs/CHANGELOG.md, lib/view_component/test_helpers.rb, test/sandbox/test/rendering_test.rb, test/sandbox/test/test_helper_test.rb
In #1661, I renamed several private TestHelper methods to indicate that they should not be used by consumers.
However, we depended on the request method in the GitHub.com test suite. I've chosen to reintroduce this method with a new name, as we originally made it private due to it conflicting with folks setting a request method name in tests.
=> Add TestHelpers#vc_test_request

docs/_sass/custom/custom.scss
Improve the text selection contrast when selecting text in code blocks in the docs.
| **Before** | **After** |
| --- | --- |
| ![Screenshot 2023-03-15 at 21 22 51](https://user-images.githubusercontent.com/6411752/225433398-1bfe4475-04ba-4703-ac64-78e4adfefb7a.png) | ![Screenshot 2023-03-15 at 21 23 02](https://user-images.githubusercontent.com/6411752/225433429-aa4a81e2-aeee-48db-a0ab-13e420d616eb.png) |
I added a new CSS rule for the `.highlight ::selection` selector with the color `#0366D6` which is currently also being used for selecting regular text on the page.
\-
=> docs: Improve contrast for `::selection` style of code blocks

docs/CHANGELOG.md, lib/view_component/capture_compatibility.rb, test/sandbox/test/action_view_compatibility_test.rb
I tried setting `config.view_component.capture_compatibility_patch_enabled = true` in GitHub's monolith today and ran into a `SystemStackError` indicating infinite recursion. After digging in I discovered the `CaptureCompatibility` module is getting `include`d more than once, which causes `alias_method :original_capture, :capture` to be evaluated multiple times. The second time around, the alias makes both `#capture` and `#original_capture` point to the same method (`CaptureCompatibility::InstanceMethods#capture`). This means that when `#capture` calls `#original_capture`, it ends up calling itself 🤦 
I added a single-line `return` statement to bail out if `InstanceMethods` has already been prepended to `ActionView::Base`.
I think the above covers it.
=> Protect against SystemStackError if CaptureCompatibility module is included more than once

docs/CHANGELOG.md, lib/view_component/compiler.rb, test/sandbox/test/inline_template_test.rb
When using inline templates in development we try to compile the superclass of the component when there are no sidecar templates available. When your component inherits from `ViewComponent::Base` this is not a problem. However, when you have another base component that inherits from `ViewComponent::Base` (e.g. `class ApplicationComponent < ViewComponent::Base`) we fail to compile the superclass, `ApplicationComponent`.
However, in the case of `inline_calls` or inline `erb_template` usage, we don't actually want to try and compile the super class.
This PR:
- Adds a failing test to exercise this problem
- Modifies the `should_compile_superclass?` method to not only check for sidecar erb files, but also inline `erb_template` usage.
n/a
=> Fix inline template error in development

.github/workflows/ci.yml, docs/CHANGELOG.md, lib/view_component/slotable.rb
1) Remove unused block arguments in `Slotable`
2) Rename `pvc` build to clarify why the build exists, as folks ask about it on occaision.
=> Two small cleanups

docs/CHANGELOG.md, docs/index.md, docs/resources.md
Fixing the broken links in the documentation. 
One link (ActionView::Components in Rails 6.1, Drifting Ruby - paid content) points to content that is behind a paywall. I'm unsure if that was the case when the link was originally added to the list. I added a note to that listing to be up-front about the availability of that content.
=> Fix broken links in documentation

app/controllers/view_components_system_test_controller.rb, app/helpers/preview_helper.rb, docs/CHANGELOG.md, docs/api.md, lib/view_component.rb, lib/view_component/base.rb, lib/view_component/collection.rb, lib/view_component/compiler.rb, lib/view_component/errors.rb, lib/view_component/inline_template.rb, lib/view_component/preview.rb, lib/view_component/preview_template_error.rb, lib/view_component/slot.rb, lib/view_component/slotable.rb, lib/view_component/template_error.rb, lib/view_component/test_helpers.rb, lib/view_component/translatable.rb, lib/view_component/with_content_helper.rb, test/sandbox/app/components/invalid_with_render_component.rb, test/sandbox/test/base_test.rb, test/sandbox/test/inline_template_test.rb, test/sandbox/test/integration_test.rb, test/sandbox/test/preview_helper_test.rb, test/sandbox/test/rendering_test.rb, test/sandbox/test/slotable_test.rb
The goal of this PR is to add all of our error messages to our docs. In order to do so, I moved all of our errors to an `Errors` module and had YARD look for classes ending in `Error` that have a `MESSAGE` constant.
I also cleaned up a few errors that should have been removed previously. I'll follow up with a review of our error messages themselves.
What do y'all think of the names for these errors?
=> Use custom error classes instead of generic errors

Gemfile, Gemfile.lock, lib/view_component/slot.rb
selenium-webdriver 4.9.1 requires Ruby 3.0, but we support previous versions of ruby.
=> lock gemfile to selenium-webdriver 4.9.0

.github/workflows/ci.yml, app/controllers/concerns/view_component/preview_actions.rb, docs/CHANGELOG.md, lib/view_component/base.rb, test/sandbox/app/controllers/default_form_builder_controller.rb, test/sandbox/app/controllers/integration_examples_controller.rb, test/sandbox/config/environments/test.rb, test/sandbox/config/routes.rb, test/sandbox/test/components/previews/helpers_proxy_component_preview.rb, test/sandbox/test/integration_test.rb, test/sandbox/test/rake_tasks_test.rb, test/sandbox/test/rendering_test.rb, test/sandbox/test/tasks_test.rb, test/test_helper.rb
Helpers don't seem to get reloaded when working with component previews (https://github.com/github/view_component/issues/1069).
This PR adds 2 tests.
[One](https://github.com/github/view_component/compare/main...jdelStrother:helper-reloads?expand=1#diff-c7634fb9ae4108c9cbf3eaebf452a2cdd2d87466586cab6923a007f36f6f34d8R86) demonstrating that helpers _are_ successfully reloaded when components are rendered through a 'normal' controller.
[The other](https://github.com/github/view_component/compare/main...jdelStrother:helper-reloads?expand=1#diff-c7634fb9ae4108c9cbf3eaebf452a2cdd2d87466586cab6923a007f36f6f34d8R109) attempts to do the same via `ViewComponentsController#previews`, but the test fails since the helper isn't reloaded.
Unfortunately I had to set `config.cache_classes=false` to get …
=> Fix helpers not reloading in previews

docs/CHANGELOG.md, docs/api.md, docs/index.md, lib/view_component/config.rb
This fixes some incorrect duplication in the configuration docs for `.capture_compatibility_patch_enabled` and `.default_preview_layout`. The descriptions for both config options were included under both headings. This seems to have been introduced in this commit: https://github.com/ViewComponent/view_component/commit/72830c8cf4aa034570fb2cc3167dedbd69cf7f4b.
=> Fix duplication in configuration docs

docs/CHANGELOG.md, docs/api.md, docs/guide/testing.md, lib/view_component/test_helpers.rb, test/sandbox/app/components/url_for_component.html.erb, test/sandbox/app/components/url_for_component.rb, test/sandbox/test/rendering_test.rb
- This allows testing components that use path helpers that are constrained by a subdomain in routes.rb.
We have routes that are constrained by a subdomain in our routes file. If the requests host does not match the constraint then a `ActionController::RoutingError: No route matches "..."` is raised.
`config/routes.rb`
```ruby
Rails.application.routes.draw do
constraints subdomain: 'app' do
resources: :products
end
end
```
=> Add host option to `with_request_url` test helper

test/sandbox/app/components/partial_haml_component.html.haml, test/sandbox/app/views/integration_examples/nested_haml.html.haml, test/sandbox/test/integration_test.rb
This change fixes a test in our suite broken by
https://github.com/rails/rails/pull/48523.
Before the upstream change, invalid the invalid HTML5 in this test case was parsed without issue. The upstream change switched the Nokogiri parsing mode to HTML5, leading to parsing issues with our test case.
I've converted all of the DOM nodes in this case into divs, preserving the intention of the test case but making it valid HTML5.
=> Update integration test to use valid HTML5

app/controllers/concerns/view_component/preview_actions.rb, docs/CHANGELOG.md, test/sandbox/app/components/unsuffixed.html.erb, test/sandbox/app/components/unsuffixed.rb, test/sandbox/app/components/unsuffixed/other.html.erb, test/sandbox/app/components/unsuffixed/other.rb, test/sandbox/test/components/previews/unsuffixed/other_preview.rb, test/sandbox/test/components/previews/unsuffixed_preview.rb, test/sandbox/test/components/render_preview_test.rb
When using components without the `Component` suffix there can be ambiguous preview paths. For instance, if there is a [`milestone`](https://github.com/reedrolemodel/view_component-bug-replica/blob/master/app/components/milestone.rb) and [`milestone/card`](https://github.com/reedrolemodel/view_component-bug-replica/blob/master/app/components/milestone/card.rb), both are candidates when rendering a [`:with_default_title`](https://github.com/reedrolemodel/view_component-bug-replica/blob/master/test/components/previews/milestone/card_preview.rb) preview. [app/controllers/concerns/view_component/preview_actions.rb#62](https://github.com/ViewComponent/view_component/blob/72b4f7de53d0834f5b9bf1ee83bee5ff79e2a09b/app/controllers/concerns/view_component/preview_actions.rb#L62) always detects the …
=> detect closest match preview path when namespaced previews exist

docs/CHANGELOG.md, lib/tasks/view_component.rake, lib/view_component/codemods/v3_slot_setters.rb, test/sandbox/app/helpers/aliases_helper.rb, test/sandbox/app/views/codemods/_v2_slots_setters_alias.html.erb, test/sandbox/app/views/codemods/_v2_slots_setters_exact.html.erb, test/sandbox/app/views/integration_examples/empty_slot.slim, test/sandbox/test/codemods/v3_slot_setters_test.rb
This PR includes improvements for #1669:
- Adds rake task to detect legacy slots `bin/rails view_component:detect_legacy_slots`
- Adds rake to migrate legacy slots automatically `bin/rails view_component:migrate_legacy_slots`
- Adds component previews to codemods view paths
- Autodetection for Rails view paths
- Improves uncertain matches detection
- Updated changelog
=> Codemod v3 slots improvements

test/sandbox/test/integration_test.rb
This PR updates a test to use the correct syntax for `assert_select`. This has likely been an issue for a while but only recently caused CI to fail due to changes to `rails-dom-testing` to not accept invalid arguments.
=> use correct syntax for assert_select

docs/guide/collections.md, docs/guide/conditional_rendering.md, docs/guide/getting-started.md, docs/guide/templates.md, docs/index.md
This change updates our docs to lean on inline templates as they greatly simplify our example code <3
I've intentionally omitted a changelog.
=> use Inline templates in docs

docs/api.md, lib/view_component/test_helpers.rb
Addresses https://github.com/ViewComponent/view_component/pull/1771#pullrequestreview-1519743265
It looks like this may have been inadvertently deleted by regenerating the API docs. That happened because this example was manually added directly in `api.md` in https://github.com/ViewComponent/view_component/pull/1773, rather than in the corresponding YARD comment. To fix this, we've added the example to the YARD comment and regenerated the API docs.
I did not include a changelog entry since this is just basically just reverting an inadvertent change from the most recent PR.
=> Restore API documentation example for with_request_url's `host` param

docs/CHANGELOG.md, docs/index.md
We've started using ViewComponent since March 2023 and we are extremely satisfied with the experience!
Added Skroutz to the list of ViewComponent users, with a link to our [engineering blog](https://engineering.skroutz.gr/blog/). 🙂
Hi, I read CONTRIBUTING.md but didn't add myself in the list of contributors because I only added a new entry in the list of users of the library. I didn't actually contribute anything else. I'll check the issues and try to help in the future. 🙂
=> Add Skroutz engineering to the list of users

.github/workflows/ci.yml, docs/CHANGELOG.md
A [recent PR](https://github.com/primer/view_components/pull/2193) removed the legacy docsite from the PVC repo, which included the `docs:preview` rake task. We should stop running it in our CI.
I removed the line that runs the offending rake task.
=> Stop running PVC's 'docs:preview' rake task in CI

docs/CHANGELOG.md, docs/guide/testing.md
I'm trying to make a (small) testing bump in the road easy to resolve.
I ran into an issue where a tested component was rendering the passed slot as plain text.  I thought a doc example with `html_safe` might help others with testing.
```rb
component.tap do |c|
c.with_buttons { "<div><button>bigger</button><a href='smaller'>smaller</a></div>" }
end
render_inline(component)
```
Results in the following `page.find('.some-class').native.inner_html`
```html
<div class=\"flex justify-end gap-3 bg-secondary-50 px-6 py-3\">&lt;div&gt;&lt;button&gt;bigger&lt;/button&gt;&lt;a href='smaller'&gt;smaller&lt;/a&gt;&lt;/div&gt;</div>"
```
It's not really worth it to do templating in tests.  This seems like an easy compromise.
Nah, this is straightforward I think.
=> Docs: Add `html_safe` example to testing->slots section

docs/CHANGELOG.md, docs/api.md, lib/view_component/preview.rb
Addresses https://github.com/ViewComponent/view_component/pull/1774#pullrequestreview-1593279882
=> Fix API documentation and revert unnecessary change in `preview.rb`

docs/CHANGELOG.md, docs/index.md, lib/view_component/test_helpers.rb, test/sandbox/test/rendering_test.rb
When using the `#with_request_url` test helper, `request.query_parameters` returns `Hash`, while Rails' `request.query_parameters` returns `ActiveSupport::HashWithIndifferentAccess`.
So I changed the `request.query_parameters` in the `#with_request_url` test helper to also return `ActiveSupport::HashWithIndifferentAccess`.
=> Fix `#with_request_url` to ensure `request.query_parameters` is an instance of ActiveSupport::HashWithIndifferentAccess

docs/CHANGELOG.md, lib/view_component/base.rb, test/sandbox/app/components/references_method_on_helpers_component.html.erb, test/sandbox/app/components/references_method_on_helpers_component.rb, test/sandbox/test/base_test.rb
We identified in #1836 that some things might influence whether the developer is aware of methods provided by the helper layer, particularly in the case where they may have used the help of libraries like Devise and Kaminari to get going. In order to make things easier when you're getting started like this, this PR adds extra context to `NameError`s raised by method calls that mirror something the view context already responds to.
`method_missing` seemed like a natural fit here, but as suggested by @camertron, I've conditionally defined this behaviour for development and test environments only.
Additionally, the source location is removed from the backtrace – this was causing another test to fail.
Worth noting that I needed to `define_instance_method` in order to stub in the test, since …
=> Refer to helpers in `NameError` response in development/test

test/sandbox/test/translatable_test.rb
This replaces the call to a stubbed method with a call to the original
method. This should be more reliable and less likely to break during
CI runs.
=> Fix flaky translation test

docs/CHANGELOG.md, docs/known_issues.md
Closes #1838
References the patch as a solution to the issues it's known to fix, and includes the explanation we have in `CaptureCompatibility`.
=> Document the capture compatibility patch on the Known issues page

docs/CHANGELOG.md, docs/guide/generators.md
I'm trying to update the document so that users can change the `view_component_path`.
I got stuck when I tried to introduce ViewComponent to Rails 7.1 app because changing just `config.view_component.view_component_path` did not work.
Finally I found that `config.eager_load_paths` should also be changed with the same path to get this change work.
I checked the fact with the newly generated Rails 7.1/7.0/6.1 apps.
=> [Docs]Update document for changing view_component_path

.github/workflows/lint.yml, docs/CHANGELOG.md, test/sandbox/test/view_component_system_test.rb, test/test_helper.rb
We're seeing quite a few `Ferrum::ProcessTimeoutError: Browser did not produce websocket url within 10 seconds` errors in CI jobs. I did a little digging and discovered the Cuprite driver we're registering in test_helper.rb is getting overwritten by Rails, so it's not using any of the config options we're passing in.
primer/view_components solved this a while ago by registering a driver with a unique name, so that's what I did here.
=> Attempt to fix Ferrum timeout errors

docs/CHANGELOG.md, lib/view_component/base.rb
I have just discovered a simple optimization on `ViewComponent::Base` that can reduce `UnboundMethod` objects allocation. I have removed other objects from this memory allocation report comparison to keep things simple and clear. These are the results in one of our main Rails endpoints.
Before:
```
allocated memory by class
-------------------------
4080  UnboundMethod
```
After:
```
allocated memory by class
-------------------------
1280  UnboundMethod
```
If you want to test this patch yourself, just do this on your `ApplicationComponent`:
```ruby
class ApplicationComponent < ViewComponent::Base
private
def self.initialize_parameters
@initialize_parameters ||= super
end
end
```
=> fix: reduce UnboundMethod objects by memoizing initialize_parameters

docs/CHANGELOG.md, docs/index.md, lib/view_component/test_helpers.rb, test/sandbox/app/components/request_url_component.rb, test/sandbox/test/components/request_url_component_test.rb
Fixing https://github.com/ViewComponent/view_component/issues/1867
Issue may be a Rails issue here: https://github.com/rails/rails/blob/8e73e620b1072c831b81604449385dfbb60bdb63/actionpack/lib/action_dispatch/http/request.rb#L262
Where `@fullpath` is cached from previous request. To get around this, I have manually set the values of `@fullpath` and `@original_fullpath` in the test helper.
A similar issue was fixed here: https://github.com/ViewComponent/view_component/commit/4241a14be92298852d80b12308bf3da9390d4db5
=> Set request full path with request url

docs/CHANGELOG.md, lib/view_component/base.rb
Fix for the issue described here: https://github.com/ViewComponent/view_component/issues/1891
```
NoMethodError: undefined method `env' for MyProject::Rails:Module (NoMethodError)
if Rails.env.development? || Rails.env.test?
^^^^
/home/circleci/project/vendor/bundle/ruby/3.2.0/gems/view_component-3.7.0/lib/view_component/base.rb:222:in `<class:Base>'
```
The issue started with version `3.6.0`, the code above was introduced with this PR: https://github.com/ViewComponent/view_component/pull/1841
Fix the issue
By specifying the root namespace for `Rails` we avoid the ambiguity. It seems to be the simplest possible fix at hand
=> Search for the Rails module in the root namespace

docs/CHANGELOG.md, docs/index.md, lib/view_component/test_helpers.rb, test/sandbox/app/components/current_page_component.rb, test/sandbox/config/routes.rb, test/sandbox/test/test_helper_test.rb
We have components whose logic varies depending based on the request method, which is not easy to test with the current `with_request_url` helper.
This adds a new `method` option to `with_request_url`. This follows the pattern previously established with the `host` option which exists to similarly specify the `host` associated with the test request.
=> Allow setting method when using the  test helper

docs/CHANGELOG.md, lib/view_component/slotable.rb
I noticed a call to [`String#ends_with?`](https://github.com/rails/rails/blob/939fd3bc41bbb90194e4b93a001c803bdceb592c/activesupport/lib/active_support/core_ext/string/starts_ends_with.rb
), which is an ActiveSupport core `String` extension [introduced](https://github.com/rails/rails/commit/7a4a12aeaa2627008a478059aeec5ea38648c19e) in 2005. 
To reduce dependencies, I suggest using the ruby native `String#end_with?` (notice the missing "s") method instead. It's been in Ruby at least [since 2.7.8](https://ruby-doc.org/2.7.8/String.html#method-i-end_with-3F).
I'm trying to create a gem that has some custom view components. Yet, I found no definite way to define the dependencies for a gem like mine. Some [don't require `rails` at all](https://github.com/betagouv/dsfr-view-components/blob/7b815 …
=> Use native String#end_with?, not the ActiveSupport wrapper

docs/CHANGELOG.md, test/sandbox/config/environments/test.rb
Rails main [recently changed](https://github.com/rails/rails/commit/ec2c2666c255029593dda2f78e89b457cf8509fc) the allowable values for `config.action_dispatch.show_exceptions`. We set it to `false` which is no longer supported. The analogous setting is now `:none`.
=> Fix show_exceptions setting for Rails main

docs/CHANGELOG.md, docs/guide/translations.md, lib/view_component/translatable.rb, test/sandbox/app/components/translatable_subclass_component.rb, test/sandbox/app/components/translatable_subclass_component.yml, test/sandbox/test/translatable_test.rb
Inheriting from a component that uses translations in the template now requires all translations to be replicated in the subclass or it will break. 
I resorted to including all parent translation files in the subclass under the subclass `i18n_scope`, thus allowing subclasses to add or replace translations as they see fit.
=> Allow translations to be inherited and overridden in subclasses

docs/CHANGELOG.md, lib/view_component/rails/tasks/view_component.rake
After #1050, running `rails stats` on a Rails app with `view_component` in its Gemfile will also include the statistics (lines of code, …) for the `ViewComponent` code which, by default, is included in `app/components`.
A Rails app, however, could have the `view_component` library in the Gemfile and not have the matching folder (`app/components` by default). In this scenario, `rails stats` fails:
```
rails stats --trace
** Invoke stats (first_time)
** Invoke view_component:statsetup (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute view_component:statsetup
** Execute stats
rails aborted!
Errno::ENOENT: No such file or directory @ dir_initialize - app/components (Errno::ENOENT)
<internal:dir>:98:in `open' …
```
=> Don't break "rails stats" if app/components is missing

docs/CHANGELOG.md, docs/index.md, lib/view_component/translatable.rb, test/sandbox/config/initializers/i18n.rb, test/sandbox/test/translatable_test.rb
With html translation keys, reserved keys are currently being made html safe, thus converting values like `true` to `"true"`. This is disabling some of these keys.
The existing code tries to match reserved keys using the `::I18n.reserved_keys_pattern`, however they will never match, as the pattern is expecting interpolated strings with the translation value. It will match `%{raise}`, but not `raise`, which is what we want. So these reserved key values are all subsequently html escaped.
This PR uses the `I18n::RESERVED_KEYS` constant directly, and excludes those keys from options that will be considered for escaping.
The key that I chose for testing was `:raise`. This meant that I needed a missing translation, so I've added another locale to the `I18n.available_locales`. This also matched …
=> Exclude I18n reserved keys from html escaping

docs/CHANGELOG.md, lib/view_component/base.rb, lib/view_component/compiler.rb, test/sandbox/app/components/after_render_component.rb, test/sandbox/app/components/custom_test_controller_component.rb, test/sandbox/app/components/deprecated_slots_setter_component.rb, test/sandbox/app/components/inherited_from_uncompilable_component.rb, test/sandbox/app/components/inline_render_component.rb, test/sandbox/app/components/message_component.rb, test/sandbox/app/components/unsafe_component.rb, test/sandbox/app/components/unsafe_postamble_component.rb, test/sandbox/app/components/variant_ivar_component.rb, test/sandbox/app/controllers/integration_examples_controller.rb, test/sandbox/config/routes.rb, test/sandbox/test/collection_test.rb, test/sandbox/test/integration_test.rb, test/test_helper.rb
This is a backport of https://github.com/ViewComponent/view_component/pull/1950 for the v2.x line. Some CI jobs may fail.
=> Backport HTML safety fix for 2.x

.github/workflows/ci.yml, Gemfile.lock, docs/CHANGELOG.md, docs/_data/library.yml, lib/view_component/version.rb
=> release 2.83.0

docs/CHANGELOG.md, docs/guide/helpers.md, lib/view_component/base.rb, test/sandbox/app/components/use_helpers_component.rb
In order to complete #1976 the `#use_helpers` method needs to be added to components by default, so this pr is part of a two part series, hopefully this can bee included with version 4
=> Include `use_helpers` in all components

docs/guide/testing.md
When writing tests, it's helpful to be able to see the full HTML for a component to debug problems. Add a note about the existing `rendered_content` helper to make it easier for folks to find out how to do this.
I had to source dive to find out how to do this, which is a barrier to people new to the library.
=> Add note to testing docs about `rendered_content` helper

docs/guide/instrumentation.md
The modern syntax is shorter and captures CPU time and allocations, see https://github.com/rails/rails/pull/49433
=> Use modern subscribe syntax

lib/view_component/test_helpers.rb
A [recent PR](https://github.com/rails/rails/pull/51150) merged into Rails main a few hours ago has broken the primer/view_component test suite, which now reports the `ActionController::TestSession` constant does not exist. This makes sense because the Rails PR in question removed the following line:
```ruby
require "action_controller/test_case"
```
Along with `ActionController::TestCase`, test_case.rb also defines `ActionController::TestSession`. For most test suites, removing these requires is not a problem, since integration tests inherit from the autoloaded `ActionController::TestCase`. When `TestCase` autoloads, so does `TestSession`.
However, view_component lets you render previews from both integration tests _and_ unit tests. If any of your integration tests run first, …
=> Fix running non-integration tests under Rails main

docs/resources.md
Added [Rails Designer](https://railsdesigner.com/) to resources page under the ViewComponent libraries section. Note that Rails Designer is not OSS, but a commercial product!
=> Added [Rails Designer](https://railsdesigner.com/) to resources page

docs/guide/slots.md
Small change to docs. `we've to` read very strangely to me, so I pulled apart the contraction.
N/A
N/A
=> Fix small grammatical funkiness on ComponentSlot documentation

docs/CHANGELOG.md, docs/index.md, lib/rails/generators/rspec/component_generator.rb, lib/view_component/config.rb, test/sandbox/test/generators/rspec_generator_test.rb
Generally, the path to an RSpec file should match the app path, but substituting `app` for `spec`. If a user changes the generation path for their components, then the generator should use an appropriate path that matches that. In the example where the user changes the generation path from `app/components` to `app/views/components`, the RSpec component spec should be created in `spec/views/components`.
The logic chosen here checks that the component is still being generated into the `app` dir, otherwise it will just fallback on the usual destination of `spec/components`. I've used simple string matching of `start_with?("app#{File::SEPARATOR}")`, but maybe using something in the `File` or `Pathname` classes would be more flexible.
Since this includes the `AbstractGenerator`, we can remove …
=> Use component path for generating RSpec files

docs/CHANGELOG.md, docs/index.md, lib/view_component/base.rb
Fix ViewComponent compilation error that happens on a upstream ruby version.
We need this to make sure templates are being correctly populated in a future ruby release.
The call stack filtering was added by https://github.com/ViewComponent/view_component/pull/281 to correct finding the template for child components. But unfortunately we started to see the following error happening in tests when running against the ruby version https://github.com/ruby/ruby/compare/d4a6c6521aa1a5208939a2cd981a13ca01a07d2a...1232975398a96af3070463292ec0c01e09a06c50:
```
ViewComponent::TemplateError: Couldn't find a template file or inline render method for ApplicationComponent.
vendor/gems/3.4.0/ruby/3.4.0+0/gems/view_component-3.11.0/lib/view_component/compiler.rb:37:in 'ViewComponent::Compiler#compile' …
```
=> Update filter in source_location to use base_label

docs/CHANGELOG.md, docs/resources.md
- https://www.bootrails.com/blog/ruby-on-rails-viewcomponents-tutorial-and-examples/
- https://remoteruby.transistor.fm/125
Remove offline links from `resources.md`
I went through all available links on the resources file to learn more about View Component and noticed some of them were unavailable. It will help keep the resources up to date
=> Remove offline links from resources.md

docs/index.md
At RailsConf (and elsewhere) I got the feedback from folks that inline templates aren't for everyone. In the interest of not scaring newcomers away from the framework, I've opted to revert to using a sidecar template on the landing page of the docs site.
=> use sidecar template on docs landing page

docs/CHANGELOG.md
Before this, the names in some Changelog entries were seen as "verbatim code sections".
Also, one instance of wrong indent fixed.
I pen-edited this on GitHub, using preview to make sure it looked right.
None.
=> CHANGELOG.md: Fix multi-line entries re indent

docs/CHANGELOG.md, test/sandbox/test/rendering_test.rb
Fix the failing Rails main CI tests
Rails added an extra entry in the first position of the `error.backtrace array`
here is an example of the error in the first position of teh array
```
/bundler/gems/rails/railties/lib/rails/engine/route_set.rb:26:in `method_missing’”
```
=> Fix Rails main in CI

test/sandbox/test/rendering_test.rb
It appears as though the change in backtrace behavior we were working around in this test has been removed, so we are OK to revert the test back to its single mode.
=> Remove exception for Rails 8

.github/workflows/ci.yml
In our experience, it's not been useful to have so many permutations
of rails/ruby/etc tested in CI. Let's pare things down to a few
representative combinations <3
https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
I also took the liberty of bumping the Ruby version we use for benchmarks/coverage to 3.3.
=> Streamline CI configuration

docs/CHANGELOG.md, lib/view_component/preview.rb
Enable putting previews (`preview.rb` files) into the sidecar directory.
Organizing components into subdirectories (AKA sidecar) is a helpful way of organizing view components.
The organizing strategy of [view_component-contrib](https://github.com/palkan/view_component-contrib) puts the previews into the sidecar directory, and organizes an example component like this:
```
components/
example/
component.html
component.rb
preview.rb
index.css
index.js
```
Currently, `view_component-contrib` uses an initializer to enable this behavior - making this change would make it possible without an initializer.
Personally, I think it makes sense to organize the test folder in the same extended sidecar way and put the previews in there:
```
spec/
components/
example/
component_spec.rb
preview.rb
``` …
=> Add ability to put previews into sidecar directory

.github/workflows/ci.yml, .github/workflows/lint.yml, Gemfile, Gemfile.lock
While working on resolving some dependabot alerts, I noticed that dependabot could not resolve our Ruby dependency files because it was using Ruby 2.7.6. This PR attempts to set a Ruby version explicitly so that Dependabot does not just use 2.7.6.
=> set default ruby version

.github/workflows/ci.yml, docs/CHANGELOG.md
Closes #1937
Instead of using `actions/cache` directly, defer to the `setup-ruby` and `setup-node` actions' native support, which uses this under the hood.
=> Defer to built-in action caching

docs/CHANGELOG.md, docs/CONTRIBUTING.md, docs/index.md, lib/view_component/slotable.rb, test/sandbox/app/components/slot_name_override_component.html.erb, test/sandbox/app/components/slot_name_override_component.rb, test/sandbox/test/slotable_test.rb
Addresses #2027:
- Define slot methods in a dynamic module so that slot name methods can be overridden with ability to call `super`
- Inspired by ActiveRecord's naming of `GeneratedAttributeMethods`, I am choosing the name `GeneratedSlotMethods`
- Define a new module and set it to the const `self::GeneratedSlotMethods` in the `inherited` hook defined by `ViewComponent::Slotable`, similar to how ActiveRecord creates `<model>::GeneratedAttributeMethods`.
- include `self::GeneratedSlotMethods` in the same inherited hook
- define the `<slot>` and `<slot>?` methods on the module
- ~Added a step in CONTRIBUTING to `bundle install`, with the goal of installing appraisal (otherwise `bundle exec appraisal install` would fail)~
- Running `bundle exec appraisal install` modified the gemfiles and I'm …
=> Add slot methods to a module instead of the component class itself

.github/workflows/ci.yml, docs/CHANGELOG.md, view_component.gemspec
**This PR targets the v4 feature branch**
As time marches on, older versions of Ruby are EOL'd. We should align ourselves with this schedule to ensure our tooling can function properly. For example, we cannot use `dependabot` properly until we make this change.
=> BREAKING: v4 minimum Ruby version should not be EOL

.github/workflows/ci.yml, Gemfile.lock, docs/CHANGELOG.md, view_component.gemspec
Same as https://github.com/ViewComponent/view_component/pull/2086, but for Rails.
=> BREAKING: v4 minimum Rails version should not be EOL

docs/CHANGELOG.md, lib/view_component/test_helpers.rb
In Yard `[ActionController::Base]` means "an instance of `ActionController::Base`, but this method actually wants a subclass. Tools such as RubyMine complain that the expected type is incorrect when that's not true.
Fixed the doc to use `[Class<ActionController::Base>]` which is the correct type signatire for this meythod.
No
=> Update `with_controller_class` type documentation

Gemfile.lock, docs/CHANGELOG.md, test/sandbox/test/rendering_test.rb, test/test_helper.rb, view_component.gemspec
This PR adds basic internal testing tooling for memory allocations, giving us a starting point for optimizing memory usage in the project.
I copied the `assert_allocations` helper from Primer ViewComponents, but modified it to target specific Ruby versions to remove ambiguity.
=> Add basic internal testing for memory allocations

docs/CHANGELOG.md, lib/view_component.rb, lib/view_component/engine.rb, view_component.gemspec
In concert with the work going on to [prep for v4](https://github.com/ViewComponent/view_component/pull/2085), this change clarifies the messaging in `main` around changing support for Ruby and Rails versions.
=> update Rails and Ruby EOL support message

Gemfile.lock, docs/CHANGELOG.md, view_component.gemspec
Suppressing a warning in Ruby 3.3.5 about `ostruct` being removed from the standard library in a future release of Ruby (3.5.0). 
Adding `ostruct` to the gemspec will suppress the warning now and future-proof the project when it is removed from the stdlib. 
No.
=> Add ostruct to gemspec

docs/CHANGELOG.md, lib/view_component/compiler.rb, lib/view_component/errors.rb, test/sandbox/test/rendering_test.rb
In service of helping debug https://github.com/ViewComponent/view_component/issues/2114, this change fleshes out the template error messages to include the current list of templates.
=> Add template information to multiple template error messages.

docs/CHANGELOG.md, lib/view_component/template.rb, test/sandbox/app/controllers/application_controller.rb
- Fix showdown by using OpenStruct, especially with YJIT
- https://github.com/ruby/ruby/blob/master/doc/yjit/yjit.md#code-optimization-tips
- https://www.reddit.com/r/ruby/comments/11wem2c/question_does_anyone_know_why_openstruct_with/
- Should eat less memory and be fast
- Use Struct, because it is implemented on C, while OpenStruct implemented on Ruby
- I am fine to use OpenStruct in tests (that is why nothing changed in its) - it more about convenience for developers to quickly make some tests data
=> Use struct instead openstruct in lib code

docs/CHANGELOG.md, docs/api.md
This PR aims to fix the example provided for #vc_test_request to use "vc_test_request" instead of "request".
This PR fixes a documentation issue, updating  `docs/api.md ` to reflect the correct usage of the #vc_test_request method.
Simple documentation fix.
Check for other references where `request` should be changed to `vc_test_request`.
=> Fix #vc_test_request example

docs/CHANGELOG.md, lib/view_component/compiler.rb, lib/view_component/errors.rb, test/sandbox/test/rendering_test.rb
This change fixes the bug reported where a component will report that it
has both a template and a `call` method defined despite only having an
HTML template.
I was able to reproduce this bug by pulling in Avo (like reported in the
initial bug report) and running `vegeta` (to trigger parallel requests
since I had a hunch this was a race condition):
```
echo "GET http://localhost:3000/avo/resources/cars/1" | vegeta attack -duration=2s
```
This reliably reproduced the error:
```
ActionView::Template::Error (Template file and inline render method found for Avo::CoverPhotoComponent. There can only be a template file or inline render method per component.
Template file and inline render method found for variant '' in Avo::CoverPhotoComponent. There can only be a template file or inline render …
```
=> Fix duplicate template error bug

docs/CHANGELOG.md, lib/view_component/compiler.rb, test/sandbox/test/rendering_test.rb
Currently we only wrap the redefinition of templates with a mutex. This
has largely been fine, but recent changes have highlighted that being
overly specific with the mutex still leads to race conditions that are
complex to debug or test for.
This change wraps the entire compile step with a mutex to help avoid
introducing any race conditions during the compile step.
I tested this change against the last race condition bug and validated
that the demo app I setup locally still runs as expected.
=> Wrap entire compile step with mutex

Gemfile.lock, docs/CHANGELOG.md, test/sandbox/app/components/partial_component.html.erb, test/sandbox/app/controllers/application_controller.rb, test/sandbox/app/controllers/integration_examples_controller.rb, test/sandbox/app/models/coupon.rb, test/sandbox/app/models/partial_model.rb, test/sandbox/app/models/photo.rb, test/sandbox/app/models/product.rb, test/sandbox/test/collection_test.rb, test/sandbox/test/rendering_test.rb, view_component.gemspec
Continue cleanup for OpenStruct - https://github.com/ViewComponent/view_component/pull/2123
Replaced OpenStruct to Struct in tests
=> Remove OpenStruct from codebase

docs/CHANGELOG.md, lib/view_component/base.rb, lib/view_component/instrumentation.rb, test/sandbox/test/base_test.rb
As a follow-up to https://github.com/ViewComponent/view_component/issues/2106, I'm formally exposing `.source_location` as part of the public API, as it seems New Relic could make good use of this feature. (See their fallback in https://github.com/newrelic/newrelic-ruby-agent/blob/dev/CHANGELOG.md#v9150 💔 )
I made `.identifier` public and used the term internally, as `source_location` is a reserved word in Ruby.
=> Expose `.identifier`

.gitignore, docs/CHANGELOG.md, lib/view_component/base.rb, lib/view_component/compiler.rb, lib/view_component/template.rb, test/sandbox/test/rendering_test.rb
This PR refactors the logic for calling `maybe_escape_html` to be embedded in the template call method instead when necessary instead of the existing roundabout approach of trying to determine whether it should be called at runtime.
=> Call maybe_escape_html directly in compiled call method

.gitignore, docs/CHANGELOG.md, docs/index.md, lib/view_component/compiler.rb, lib/view_component/template.rb, test/sandbox/app/components/variants_component.html+mini.watch.erb, test/sandbox/test/rendering_test.rb
This change introduces `ActionView::TemplateDetails` as the primary abstraction for parsing and interpreting formats and variants. In a future PR I'll use this to implement template ordering based on the same logic that Rails uses for tie-breaks.
Discussion in https://github.com/ViewComponent/view_component/issues/2128
Rails already has complex and well-used logic for parsing template file names. ViewComponent's differences do not seem intentional, and using the Rails logic should make it easier for ViewComponents to avoid inconsistencies in the future.
I've split up the logic for the three different template types into separate classes. This helps reduce the conditional logic by using polymorphism instead. I've taken small steps and avoided any structural changes, but this lays the …
=> Use ActionView::TemplateDetails for handling format and variant

docs/index.md
Hello!
We have been using ViewComponent for a while now for a growing number of our components, so thought I should add us to the list of orgs.
Cheers
Steve
=> Add Buildkite to list of organizations that use ViewComponent.

docs/CONTRIBUTING.md
This PR removes inactive committers from the project and simplifies the `committer` guidelines. Thank you for your contributions over the years @elia, @jonspalmer, @juanmanuelramallo, @rmacklin, and @dylanatsmith ❤️
=> Update committers list and guidance

docs/index.md
OpenProject is an open-source project management platform built with Ruby and Rails. We use a fork of GitHub's Primer design system based on ViewComponents: https://github.com/opf/primer_view_components
=> Add OpenProject to list of ViewComponent users

docs/CHANGELOG.md, docs/guide/testing.md
While getting started w/ View Component today, I struggled w/ errors like 'Undefined method `render_inline` for ...
I updated the documentation to include a section referencing https://stackoverflow.com/questions/70041733/integrating-viewcomponent-with-rspec and how to add the view component test helpers
I believe that the comment above this section that mentions `(Capybara matchers are available if the gem is installed)` would indicate that adding `require "capybara/rspec"` or `config.include Capybara::RSpecMatchers, type: :component` is not a requirement to use those matchers. There may be some nuance that I don't fully understand to different setups though!
Welcome to any feedback
I'm happy to update for how to do this for minitest in test_helpers.rb, but I'm unsure if the sytnax is …
=> Documentation Update: Add a section for how to add the render_inline helpers to RSpec tests

docs/CHANGELOG.md, lib/view_component/base.rb, lib/view_component/compiler.rb, lib/view_component/errors.rb, lib/view_component/request_details.rb, lib/view_component/template.rb, lib/view_component/test_helpers.rb, test/sandbox/app/components/turbo_stream_format_component.html+custom.erb, test/sandbox/app/components/turbo_stream_format_component.html.erb, test/sandbox/app/components/turbo_stream_format_component.rb, test/sandbox/test/rendering_test.rb
Rails uses `ActionView::TemplateDetails::Requested` to sort available templates to find the best match for a given `LookupContext`, taking in to account the acceptable content types, variants, locale, and handlers available. ViewComponent implements a subset of this logic that leaves some gaps, i.e. https://github.com/ViewComponent/view_component/issues/2154 https://github.com/ViewComponent/view_component/issues/2128
This PR aims to bring the ViewComponent template selection logic in line with how Rails chooses a partial, and ensure that it won't drift in the future by using Rails' internal structures for the calculation.
1. I'm using `refine` to provide access to Rails' internal `@details` ivar from `LookupContext` that memoizes details about the rendering context for use in …
=> Refactor compiler to use ActionView's partial sorting algorithm

docs/CHANGELOG.md, docs/index.md
Add HomeStyler AI to the list of projects/companies that use ViewComponents.
Update the list of projects/companies that currently use ViewComponents.
Update the list directly.
Thanks for creating such an awesome library!
=> Add eagerworks to the list of projects/companies that use ViewComponents

docs/CHANGELOG.md, lib/view_component/test_helpers.rb, test/sandbox/test/rendering_test.rb
Update our test helpers to use newer Nokogiri HTML parser. Related: https://github.com/ViewComponent/view_component/pull/2209
I opted to update the class here directly for v4 instead of adding a configuration option, as I don't think we need to allow both cases. I also want to avoid adding unnecessary configuration.
=> BREAKING: Use Nokogiri::HTML5 instead of Nokogiri::HTML4

app/controllers/concerns/view_component/preview_actions.rb, docs/CHANGELOG.md, lib/view_component/base.rb, test/test_helper.rb, view_component.gemspec
This PR lands the least controversial bits of https://github.com/ViewComponent/view_component/pull/2202. We should revisit the other cases but for now, I think we can land these safely.
=> Remove respond_to? checks

.rubocop.yml, .standard.yml, docs/CHANGELOG.md, lib/view_component/inline_template.rb, lib/view_component/slot.rb, lib/view_component/slotable.rb, lib/view_component/test_helpers.rb, lib/view_component/translatable.rb, lib/view_component/use_helpers.rb, test/sandbox/test/rendering_test.rb
Remove unnecessary usage of `ruby2_keywords`.
I removed the usage wholesale as we do not support Ruby v2 in ViewComponent v4.
=> Remove unnecessary usage of ruby2_keywords.

docs/CHANGELOG.md, lib/view_component/base.rb, lib/view_component/configurable.rb, test/sandbox/test/base_test.rb, test/sandbox/test/rendering_test.rb
Adds a mechanism for inheriting config from a parent module. Since `Base` is generally used when referring to "global" config options, this doesn't do anything right now beyond exposing the ability to configure parent modules.
Modules can be configured by requiring and including `ViewComponent::Configurable`, which will expose a `config` accessor with a `view_component` configuration on the module. These will not interfere with existing configuration that might be granted to, e.g., a `Rails::Engine` by default.
This would give us a starting point to begin migrating options into engine-local config.
---
The separation between:
- module and/or Rails app-local config (this PR)
- exclusively Rails app-local config (`lib/view_component/engine.rb`)
- component-local config (#2230)
isn't perfect …
=> Delegate config to parent modules (no-op)

docs/CHANGELOG.md, lib/view_component/base.rb, lib/view_component/collection.rb
This PR looks to close https://github.com/ViewComponent/view_component/issues/1973 by removing our definition of `#format` methods, as:
1) @seanpdoyle [noted](https://github.com/ViewComponent/view_component/issues/1973#issuecomment-1889928719) they are optional
2) We were returning `nil` anyways. 
We can always revisit adding them back if needed, which I don't think would be a breaking change.
=> [v4] Remove unnecessary #format definitions, which returned nil

lib/view_component/base.rb
As noted in the code comment, this is no longer needed.
=> Remove unnecessary call to `view_renderer`

.github/workflows/lint.yml, docs/CONTRIBUTING.md, docs/guide/getting-started.md, lib/generators/view_component/component/USAGE, lib/view_component/base.rb, test/sandbox/config/application.rb, test/sandbox/config/environment.rb
This PR removes references to old Rails versions we no longer support.
=> Cleanup references to old Rails versions

lib/view_component/slotable.rb
After giving this a deep read, I'm not convinced we should change this behavior. I'm removing the TODO.
=> remove TODO for slot name collisions

docs/CHANGELOG.md, docs/api.md, docs/guide/instrumentation.md, lib/view_component/config.rb, lib/view_component/engine.rb, lib/view_component/instrumentation.rb, test/sandbox/config/environments/test.rb, test/sandbox/test/config_test.rb, test/sandbox/test/instrumentation_test.rb, test/sandbox/test/rendering_test.rb, test/test_engine/test/config_test.rb, test/test_helper.rb
This PR removes the final `# :nocov:` from the codebase by enabling instrumentation in the test suite.
The memory allocations test became flaky with instrumentation enabled, randomly adding three allocations:
```ruby
80 finish activesupport-8.0.2/lib/active_support/notifications/fanout.rb 133
160 dup activesupport-8.0.2/lib/active_support/notifications/instrumenter.rb 112
160 new view_component/test/sandbox/test/instrumentation_test.rb 9
```
This appeared to be a race condition with ActiveSupport Notifications, so I opted to disable them for the memory allocations test.
There was conflicting verbiage around the deprecation of this option. I've clarified it in https://github.com/ViewComponent/view_component/pull/2254 for release on the v3 series.
=> [v4] Remove final nocov

docs/CHANGELOG.md, docs/api.md, lib/view_component/config.rb, test/sandbox/test/rendering_test.rb
This option should have been documented as headed for removal as the deprecation warning already indicates.
=> clarify deprecation plan for use_deprecated_instrumentation_name

app/controllers/view_components_system_test_controller.rb, docs/CHANGELOG.md, docs/api.md, lib/view_component/errors.rb, lib/view_component/system_test_helpers.rb
Out of an abundance of caution, this PR changes `ViewComponentsSystemTestController` to only be loaded in the test environment.
=> ViewComponentsSystemTestController only exists in test env

docs/CHANGELOG.md, lib/view_component.rb, lib/view_component/base.rb, lib/view_component/collection.rb, lib/view_component/compiler.rb, lib/view_component/component_error.rb, lib/view_component/engine.rb, lib/view_component/inline_template.rb, lib/view_component/preview.rb, lib/view_component/slotable.rb, lib/view_component/slotable_default.rb, lib/view_component/template.rb, lib/view_component/translatable.rb, test/sandbox/spec/components/previews/preview_component_spec.rb, test/sandbox/test/components/described_class_test.rb, test/sandbox/test/components/my_component_test.rb, test/sandbox/test/components/nil_described_class_test.rb, test/sandbox/test/components/render_preview_test.rb, test/sandbox/test/inline_template_test.rb, test/sandbox/test/integration_test.rb, test/sandbox/test/rendering_test.rb, test/sandbox/test/slotable_test.rb, test/sandbox/test/translatable_test.rb, test/test_helper.rb
Rename internal methods to have `__vc_` prefix if they shouldn't be used by consumers. Make internal constants private. Make `Collection#components`, `Slotable#register_polymorphic_slot` private. Remove unused `ComponentError` class.
=> Rename private and internal methods to indicate they are not part of public API

Rakefile, docs/CHANGELOG.md
I'm not sure why, but these tests were not being run as part of our CI build. I think it's good to have some sort of compatibility tests with RSpec so I opted to keep them vs. removing them.
=> Run RSpec tests in CI

Gemfile.lock, lib/view_component/deprecation.rb, lib/view_component/version.rb
This PR starts to prepare us for the first alpha release of `v4` by establishing a new deprecation horizon and setting the version as `4.0.0.alpha1`.
=> Update deprecation horizon and version #

Rakefile, docs/CHANGELOG.md, lib/view_component/docs_builder_component.html.erb, lib/view_component/docs_builder_component.rb, test/docs/docs_rake_task_test.rb
Running `rake docs:build` after changes in #2230 resulted in some issues with HTML-escaped tags being generated, overriding existing working documentation. These changes mark output as HTML-safe so that docs are generated properly.
=> Fix generation of docs that was broken due to HTML safety issues

docs/CHANGELOG.md, lib/view_component/base.rb, lib/view_component/template.rb, test/sandbox/app/components/current_template_component.html.erb, test/sandbox/app/components/current_template_component.rb, test/sandbox/test/rendering_test.rb
Prior to the compiler changes in v4, we set @current_template to be the current instance of the component. Now, we set it to the current ViewComponent::Template. In the GitHub monolith, we reference @current_template when doing certain diagnostic operations. 
I added an accessor to make this less messy to use (and test) and exposed #path on template, which now allows for such diagnostic operations to reference the specific component template being rendered.
=> Add #current_template accessor and Template#path

test/sandbox/test/rendering_test.rb
With @camertron's change to remove the render compat patch, we were able to simplify our CI matrix to the point of no longer needing this conditional branching.
=> Simplify CI allocations test

test/sandbox/config/application.rb, test/sandbox/config/environments/test.rb, test/sandbox/test/components/render_preview_test.rb, test/sandbox/test/integration_test.rb
This PR adds additional test coverage for rendering previews from a custom preview path.
I was attempting to reproduce the issue in #2182. I could not, but figured it would be good to keep the test coverage around.
=> Add test coverage for custom preview paths

test/sandbox/app/components/unreferenced_component.html.erb, test/sandbox/app/components/unreferenced_component.rb, test/sandbox/config/environments/test.rb, test/sandbox/test/integration_test.rb, test/sandbox/test/rendering_test.rb
I've decided to prioritize testing code reloading, which has broken before, over testing compilation of an unreferenced component, which hasn't caught any regressions to my knowledge.
This resolves the last of the skips in the test suite.
=> Do not cache classes in test env

app/controllers/view_components_system_test_controller.rb, docs/CHANGELOG.md, lib/view_component/base.rb, test/sandbox/test/rendering_test.rb
Per @dmarcoux, inline_call components do not render template annotations due to their lack of template.
This change adds functionality to mimic Rails' built-in behavior for inline_call components.
Closes #1301
=> add template annotations for inline_call components

docs/CHANGELOG.md, lib/generators/view_component/component/component_generator.rb, lib/view_component/base.rb, lib/view_component/config.rb, test/test_helper.rb
`config.component_parent_class` is only used for generators. It should be in the `generate` namespace!
=> Move component_parent_class to generator configuration namespace

app/controllers/concerns/view_component/preview_actions.rb, docs/CHANGELOG.md, docs/api.md, docs/guide/previews.md, docs/guide/testing.md, lib/generators/view_component/preview/preview_generator.rb, lib/view_component/config.rb, lib/view_component/engine.rb, lib/view_component/preview.rb, lib/view_component/test_helpers.rb, test/sandbox/config/application.rb, test/sandbox/test/config_test.rb, test/sandbox/test/integration_test.rb, test/test_engine/test/config_test.rb, test/test_engine/test_helper.rb, test/test_helper.rb
This PR isolates the previews-related configuration into its own namespace for better organization and comprehension by consumers.
=> [v4] BREAKING: Move previews-related configuration to separate namespace

docs/CHANGELOG.md, lib/view_component/base.rb, test/sandbox/app/components/turbo_stream_component.html.erb, test/sandbox/app/components/turbo_stream_component.rb
We have code that includes `Turbo::StreamsHelper` in our components and calls `<%= turbo_stream.<verb> %>` in the frontend. This may not be a supported use-case in v4 but I think it's worth a call-out as a breaking change.
Alternatively, consider delegating `format` to helpers.
This PR demonstrates the breaking change by changing the existing turbo stream component.
=> v4 regression when using Turbo::StreamsHelper

docs/CHANGELOG.md, lib/view_component/slotable.rb, test/sandbox/test/rendering_test.rb
While profiling something unrelated I noticed a lot of unnecessary string allocations in Slotable#register_default_slots. How about this change to move it out of the `instance_methods` loop?
=> Reduce allocations in Slotable#register_default_slots

lib/view_component/base.rb, test/sandbox/test/rendering_test.rb
Speed up rendering when there are lots of calls to `#with_collection` for the same componen, for example when rendering a collection of items, where each item contains a collection of sub-items.
I focused on reducing redundant allocation of string objects. This is because rack-mini-profiler's flamegraph showed me lots of repeats of the same string interpolation.
The code setting the expected number of allocations will have to be updated to include values for all the relevant Ruby and Rails versions.
=> Reduce allocations in #with_collection

docs/resources.md
Add a blog to the docs showing a technique to scoped CSS within view components
I added a link to `docs/resources.md` file, under the heading 'Articles' that contain links to blogs and articles. The link added to the bottom of list maintaining the order.
Interesting blog on scoping CSS :)
=> Add link to Scoped CSS in Ruby blog post

test/sandbox/test/rendering_test.rb
Potential fix for [https://github.com/ViewComponent/view_component/security/code-scanning/14](https://github.com/ViewComponent/view_component/security/code-scanning/14)
To fix the issue, the `.` in the regular expression should be escaped to ensure it matches a literal dot rather than any character. Specifically, the pattern `%r{http://assets.example.com/assets/application-\w+.css}` should be updated to `%r{http://assets\.example\.com/assets/application-\w+\.css}`. This change ensures that the regular expression matches only the intended domain and path.
The fix will be applied to line 375 in the file `test/sandbox/test/rendering_test.rb`.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Potential fix for code scanning alert no. 14: Incomplete regular expression for hostnames

docs/CHANGELOG.md, view_component.gemspec
there's no `lib/rails` folder but there is a `lib/generators` folder, I believe this is a configuration bug that was introduced during a v4-related refactoring?
Attempting to address: https://github.com/ViewComponent/view_component/issues/2394
I looked into the expected convention for rails generators, noticed that the `lib/generators` folder was missing in the install folder of the gem on my local machine.
I'm hoping this is a simple typo / oversight, which I believe a maintainer should be able to quickly figure out from this PR! 😅 
I am not entirely sure how to write a spec for this, but perhaps that's not necessary for a gemspec typo?
=> Fix: missing generators in gemfiles

.github/workflows/push_gem.yml, docs/CHANGELOG.md, docs/CONTRIBUTING.md, script/publish, script/release
Close #2224
Setting up Trusted Publishing, to improve software supply chain safety.
- [RubyGems' blog](https://blog.rubygems.org/2023/12/14/trusted-publishing.html)
- [RubyGems' guide](https://guides.rubygems.org/trusted-publishing/)
I added a Trusted Publisher on RubyGems: https://rubygems.org/gems/view_component/trusted_publishers (access to this link is limited to maintainers).
Whenever we push a new tag starting with `v`, a specific workflow (`push_gem`) runs in Github Actions and takes care of publishing the gem to RubyGems.
As advised by RubyGems, this new workflow runs in a [dedicated `release` environment](https://github.com/ViewComponent/view_component/settings/environments/7795049317/edit), limited to maintainers.
=> Setup Trusted Publishing

docs/CHANGELOG.md, lib/view_component/base.rb, test/sandbox/app/components/partial_with_yield_component.html.erb, test/sandbox/app/components/partial_with_yield_component.rb, test/sandbox/app/views/shared/_yielding_partial.html.erb, test/sandbox/test/rendering_test.rb
Fixes https://github.com/ViewComponent/view_component/issues/2423
`ViewComponent::Base` retains a reference to the view context's output buffer. When component templates are evaluated, they do so inside the context of `ViewComponent::Base`, and thus append to the retained `@output_buffer` instance. However, Rails creates a new output buffer when rendering partials, and temporarily reassigns its own `@output_buffer` instance variable. When rendering partials inside a view component, `ViewComponent::Base` forwards the block on to `view_context.render`, but since the block was created inside `ViewComponent::Base`, that's where it will be evaluated when called. This means the block will append to the original `@output_buffer` and not to the new one Rails creates for the partial. To mitigate …
=> Fix double rendering issue for partials that yield

docs/CHANGELOG.md, docs/index.md
_Most_ of Carwow's code is not open source, so I'm not sure I can link to code examples of the usage.
However, the Carwow styleguide - used throughout the website - is publically accessible, and gives some clues about how View Components are used! e.g. https://styleguide.carwow.co.uk/inspect/award_badge/default
=> Add Carwow to "Who uses ViewComponent?"
