README.md

In the interest of guiding our development of this gem, this PR adds a simple note about how we strive to design for the least surprise, specifically with existing users of Rails in mind.

add note about design philosophy

---

Gemfile.lock
lib/action_view/component/base.rb
test/action_view/integration_test.rb
test/app/components/issues/badge.html.erb
test/app/components/issues/badge.rb
test/app/lib/primer/state.html.erb
test/app/lib/primer/state.rb
test/app/views/application/content.html.erb
test/config/routes.rb

This PR attempts to fix https://github.com/github/actionview-component/issues/50, where nested content was not rendering properly in `v1.3.0`.

Fix nested content rendering bug

---

lib/action_view/component/base.rb

This makes it easier to work with in a debugger

Provide file and line context for class_eval

---

lib/action_view/component/base.rb
test/action_view/component_test.rb
test/app/components/path_component_container.html.erb
test/app/components/path_component_container.rb

This PR makes `controller` public. 
Thanks to @afuno @koenhandekyn and others for report, and to @michaelem for providing a failing test!

make `controller` public

---

lib/action_view/component/base.rb
test/action_view/component_test.rb
test/app/components/no_format_component.erb
test/app/components/no_format_component.rb

@koenhandekyn this should address #78 ❤️

View template extensions

---

lib/action_view/component/base.rb

This PR does some light refactoring ahead of cutting another release.

Some light refactors

---

lib/action_view/component/base.rb
test/action_view/integration_test.rb
test/app/components/cache_if_component.html.erb
test/app/components/cache_if_component.rb
test/app/views/application/cached.html.erb
test/config/routes.rb

This PR introduces support for `cache_if` inside components.

Add support for `cache_if` in components

---

Gemfile.lock
actionview-component.gemspec
lib/action_view/component/base.rb
test/action_view/better_html_test.rb
test/config/application.rb

This is a temporary patch to enable compatibility
with Shopify/better_html.
cc @vinistock

Patch in support for better_html

---

test/action_view/component_test.rb
test/app/components/asset_component.html.erb
test/app/components/asset_component.rb
test/config/application.rb

@joelhawksley had to recreate the PR after closing the other one.
This just has the test and config value

Add test for helpers.asset_url

---

README.md

This pull request adds documentation for the conditional rendering functionality introduced in https://github.com/github/actionview-component/pull/182.
(Sorry about the whitespace change, I missed that when staging 😬)

Add conditional rendering documentation to README

---

test/action_view/integration_test.rb
test/app/components/cache_if_component.html.erb
test/app/components/cache_if_component.rb
test/app/views/application/cached.html.erb

WIthout version test will not fail If cache doesn't work

Fix cache test

---

.github/ISSUE_TEMPLATE
.github/PULL_REQUEST_TEMPLATE
CONTRIBUTING.md
README.md

This PR tidies up our contributing guides and adds a contributors section to the README.

Clean up contributing info

---

CHANGELOG.md
lib/rails/generators/rspec/templates/component_spec.rb.tt
lib/rails/generators/test_unit/templates/component_test.rb.tt
test/view_component/test_unit_generator_test.rb

Thanks for the report @bunnymatic! <3
[Fixes: #243]

placeholder test should use correct syntax

---

docs/case-studies/jellyswitch.md

Bootstrap component case study

---

Gemfile.lock
actionview-component.gemspec

This PR updates our `gemspec` to address some small warnings when building the gem.

fix gem warnings

---

CHANGELOG.md
Gemfile.lock
actionview-component.gemspec
lib/view_component/version.rb

Note: This is our last release in the `actionview-component` namespace ahead of `v2.0.0`. See you in `view_component` ❤️

release v1.17.0

---

README.md

The contributors table broke during some merges, this fixes it 👍

Fix issues with README.md

---

README.md

Add documents about `helpers` proxy.
I've got the sample code and instructions from #105.

Documents about helpers proxy

---

CHANGELOG.md
README.md
lib/view_component/base.rb
test/app/components/sidecar_directory_component.rb
test/app/components/sidecar_directory_component/sidecar_directory_component.html.erb
test/app/components/template_and_sidecar_directory_template_component.html.erb
test/app/components/template_and_sidecar_directory_template_component.rb
test/app/components/template_and_sidecar_directory_template_component/template_and_sidecar_directory_template_component.html.erb
test/view_component/view_component_test.rb

Simple implementation of option 2 from #331

Supporting sidecar view directory

---

lib/view_component/base.rb
test/config/environments/test.rb

See https://github.com/rails/rails/pull/39204
This change enables our tests against Rails `master` to pass ❤️.

use new name for template annotations feature

---

.gitignore
CONTRIBUTING.md
Gemfile.lock
coverage/coverage.txt
test/app/components/default_inline_and_variant_template_component.rb
test/app/components/default_template_and_inline_default_template_component.rb
test/app/components/inline_variant_component.rb
test/app/components/missing_default_collection_parameter_component.rb
test/app/components/variant_template_and_inline_variant_template_component.rb
test/config/boot.rb
test/test_helper.rb
view_component.gemspec

This PR adds `simplecov` to workflow for building ViewComponent.
It:
1) Removes some untested code.
2) Adds a minimum coverage level of `98`. I'd love to get this to 100% if possible.
3) Checks in `coverage.txt` so we can track code coverage across PRs 🎊

Add simplecov

---

CHANGELOG.md
Gemfile.lock
lib/view_component/version.rb

* Fix bug where previews didn't work when monkey patch was disabled.

Release 2.18.1

---

README.md

This PR starts to update our Slots documentation based on feedback from my colleague @natashaU ❤️

update Slots README based on feedback from @natashau

---

.github/stale.yml

Migrates from `wontfix` to `stale` label

Update stale.yml to use stale label instead of wontfix

---

Gemfile.lock

Per https://github.com/github/view_component/issues/461, let's see if something's changed in Rails `master` that breaks collection rendering.
cc @fullpointer

update rails version

---

CONTRIBUTING.md

This PR updates our contributing guidelines
to match the Primer ViewComponents guide.

clean up contributing directions

---

CHANGELOG.md
lib/view_component/version.rb

update to v2.19.0
cc/ @joelhawksley @aellispierce

update to v2.19.0

---

CHANGELOG.md
README.md

Adds documentation for webpack configuration when using Stimulus controllers.

Add documentation for webpack configuration when using Stimulus controllers.

---

CHANGELOG.md
lib/view_component/version.rb

update to v2.19.1
cc/ @joelhawksley @aellispierce

Update gem to v2.19.1

---

Gemfile.lock
lib/view_component/base.rb

This PR updates our Rails `master` dependency, removing an accommodation we had for template annotations that is no longer necessary 🎊

Update to work with latest Rails master

---

CHANGELOG.md
lib/view_component/version.rb

Update gem release to version 2.20.0
cc/ @joelhawksley @aellispierce

Update gem to v2.20.0

---

CHANGELOG.md
lib/view_component/version.rb

Gem Upgrade 2.21.0
cc/ @joelhawksley @aellispierce

Upgrade gem version to v2.21.0

---

docs/index.md

This PR adds a section on known issues with the library and a simple heading to the top of the guide.

Docs cleanup

---

docs/index.md

This PR fixes indentation and code identifier in the `docs/index.md`.

Improve docs

---

CHANGELOG.md
Gemfile.lock
lib/view_component/version.rb

* Fixed out-of-order rendering bug in `ActionView::SlotableV2`
*Blake Williams*

Bump version to 2.23.1

---

.github/workflows/ci.yml
CHANGELOG.md
lib/view_component/collection.rb
test/app/controllers/integration_examples_controller.rb
test/config/routes.rb
test/view_component/integration_test.rb

Fixes https://github.com/github/view_component/issues/549.

Fix bug rendering component collections from controllers

---

CHANGELOG.md

I'd love to automate more of our release process 😂

Add version header to changelog

---

docs/index.md

Minor style change :fireworks:

Minor style change in docs/index.md

---

.github/workflows/ci.yml
Gemfile

rails/rails has updated the default branch to be main - https://twitter.com/dhh/status/1350091751789375490
I do believe this change will bust the cache in CI but I think that should be a one time hit.

Use rails@main in CI matrix

---

CONTRIBUTING.md
script/release-branch

Script will:
1. Ask for new version
1. Creates a new branch `release-v$VERSION`
1. Updates `lib/view_component/version.rb`
1. Updates `CHANGELOG.md`
1. Updates `Gemfile.lock` (running `bundle`)
1. Commits and pushes changes

Add script to automate release branches

---

docs/index.md

Fixes #622 (the code samples for that section of the docs raised errors)

Fix sample code for Delegate slots

---

.github/workflows/ci.yml

Closes https://github.com/github/view_component/issues/525
Set up a new step in the CI pipeline to:
1. Clone https://github.com/primer/view_components
2. Make it use the current VC commit
3. Run its tests

Run PVC tests as part of CI

---

CHANGELOG.md
lib/rails/generators/erb/component_generator.rb
test/generators/component_generator_test.rb
test/generators/erb_generator_test.rb

Fix destination problem when generating an ERB component with `--inline` flag

---

docs/index.md

The original code didn't work well with sidecar components.

Make the components.js example work with Sidecar directories

---

docs/index.md

This PR adds a direct mention of the VC storybook project to the documentation.

add note about VC storybook

---

test/app/components/container_component.rb
test/app/components/inline_inherited_component.rb
test/app/components/slim_html_formatted_slot_component.rb
test/app/components/slim_with_unsafe_html_component.rb
test/view_component/view_component_test.rb

Updated the component names according to zeitwerk errors. Checked it locally using `zeitwerk:check`
This was breaking builds running against rails main

update components to match zeitwerk expectation

---

lib/view_component/compiler.rb
lib/view_component/slotable.rb
test/view_component/test_unit_generator_test.rb
test/view_component/view_component_test.rb

Just a few things I bumped into while working on translations.

A few minor fixes

---

docs/index.md

This is a story about why we decided to use View Component and how we integrated it.

Added a link to article introducing ViewComponent

---

docs/index.md

adds a small note about common cases for ViewComponents

---

docs/slots_v1.md

After reviewing #805 I found another similar broken link.

Update "Slots v2" broken link in docs

---

docs/guide/testing.md
docs/motivation.md

Some small documentation changes ❤️

add testing note, use `markup` instead of `HTML`

---

docs/guide/testing.md

- Update RSpec configuration snippet to include Capybara helpers
- Provide an example spec

Update RSpec guide

---

lib/view_component/base.rb

Remove code duplication in ViewComponent::Base.

Remove code duplication

---

docs/_config.yml

Keeping the defaults from Just the Docs:
https://github.com/pmarsceill/just-the-docs/blob/e8424986370bef104e680e1443a83e475d2fead7/docs/search.md
Closes #864
Preview:

Enable search for docs site

---

CHANGELOG.md
Gemfile.lock
lib/view_component/version.rb

Release 2.31.0

---

CHANGELOG.md
Gemfile.lock
lib/view_component/version.rb

release 2.31.1

---

CHANGELOG.md
docs/guide/slots.md
lib/view_component/slotable_v2.rb
test/app/components/slots_v2_block_component.html.erb
test/app/components/title_wrapper_component.html.erb

fix slot examples using incorrect syntax 

---

docs/CHANGELOG.md
docs/CONTRIBUTING.md

Welcome to the Triage team, @boardfish!

add @boardfish to Triage

---

docs/CHANGELOG.md
lib/view_component/engine.rb
test/view_component/preview_helper_test.rb

This PR is a couple small cleanups around https://github.com/github/view_component/pull/667 ahead of shipping the next release ❤️

Preview source code items

---

app/controllers/view_components_controller.rb
docs/CHANGELOG.md
docs/CONTRIBUTING.md
lib/view_component/base.rb
lib/view_component/collection.rb
lib/view_component/compiler.rb
lib/view_component/content_areas.rb
lib/view_component/preview.rb
lib/view_component/slot_v2.rb
lib/view_component/slotable_v2.rb
lib/view_component/with_content_helper.rb
test/view_component/base_test.rb
test/view_component/slotable_v2_test.rb
test/view_component/view_component_test.rb

This PR updates our error messages to follow a more consistent format and to provide suggested resolutions when possible.

Update error messaging to be more descriptive and consistent

---

.github/workflows/ci.yml
docs/CHANGELOG.md
performance/components/inline_component.rb

@andrewjtait recently pointed out that our benchmarks were broken.
In order to prevent this from happening again, let's run them in CI.

Run benchmarks in CI

---

docs/CHANGELOG.md
docs/guide/slots.md

Co-authored-by: Blake Williams <blakewilliams@github.com>

clarify slots example in docs to reduce naming confusion

---

docs/api.md

This updates the documentation to reflect the changes made in #1030 (see 9346c71)

Update API docs

---

.github/workflows/ci.yml

Just noticed that in my previous PR... Whoopsie! :smile:

Fix typo in error message from docs_api CI job

---

docs/CHANGELOG.md
docs/index.md
lib/view_component/engine.rb
lib/view_component/rails/tasks/view_component.rake
test/view_component/tasks_test.rb

Add `app/components` to `rails stats` task.
Inspiration from https://github.com/rspec/rspec-rails/blob/main/lib/rspec/rails/tasks/rspec.rake.
Not really sure what could I add for test coverage.

feat: add components to rails stats task

---

docs/CHANGELOG.md
docs/index.md
lib/view_component/base.rb
test/sandbox/app/components/collection_iteration_extend_component.rb
test/sandbox/app/components/collection_iteration_extend_override_component.html.erb
test/sandbox/app/components/collection_iteration_extend_override_component.rb
test/view_component/view_component_test.rb

Fix with_collection_parameter to be inherited from parent component

---

docs/CHANGELOG.md
docs/api.md
docs/guide/generators.md
lib/rails/generators/component/component_generator.rb
lib/view_component/base.rb
test/generators/component_generator_test.rb
test/test_helper.rb

* Add `--parent` generator option to specify the parent class.
* Add config option `config.view_component.component_parent_class` to change it project-wide.
* Add tests
Close #1067

Add parent option

---

docs/CHANGELOG.md
docs/index.md

This PR adds a section to list who is using ViewComponent. Please feel free to add your team to the list! ❤️

add users of ViewComponent to docs

---

docs/CHANGELOG.md
docs/viewcomponents-in-practice.md

This PR fleshes out the ViewComponents in practice docs to include answers to common questions we get internally.

Flesh out ViewComponents in practice

---

docs/CHANGELOG.md
docs/frequently-asked-questions.md
docs/viewcomponents-in-practice.md

Add more to ViewComponents in practice

---

docs/index.md

Adds https://cults3d.com to the list of proud users. We are one of the top 7k sites in the world, and I am glad ViewComponents helps us handle the complexity of our views.
Two small fixes in the docs as well:
- Fix link to edit the documentation index
- Place the document path inside the file as a comment, as it is done elsewhere in the documentation

Add Cults to the list of proud users 💜

---

docs/CHANGELOG.md
test/test_helper.rb

Fixes comment typo

---

.github/CODEOWNERS
docs/CHANGELOG.md
docs/CONTRIBUTING.md

Add @dylanatsmith as codeowner of the ViewComponent logo and member of committers team.

---

docs/CHANGELOG.md
docs/_config.yml

Add Github repo link to docs website header

---

docs/CHANGELOG.md
docs/api.md
lib/view_component/base.rb

Co-authored-by: Blake Williams <blakewilliams@github.com>
Co-authored-by: Cameron Dutro <camertron@github.com>

Rename internal accessor to use private naming.

---

docs/CHANGELOG.md
docs/CONTRIBUTING.md

See https://github.com/github/view_component/pull/1153#issuecomment-976857701

add @yhirano55 to `triage` team

---

docs/CHANGELOG.md
docs/CONTRIBUTING.md

Simon has shown that he can be trusted as a committer to ViewComponent ❤️

Make @boardfish a committer

---

docs/CHANGELOG.md
docs/index.md

Added myself to `docs/index.md` and sorted the existing list of contributors alphabetically on handle.

Add @boardfish to docs index

---

docs/CHANGELOG.md
test/sandbox/app/components/lambda_slot_passthrough_component.html.erb
test/sandbox/app/components/lambda_slot_passthrough_component.rb
test/sandbox/test/components/previews/lambda_slot_passthrough_component_preview.rb
test/sandbox/test/components/previews/lambda_slot_passthrough_component_preview/default.html.erb
test/view_component/integration_test.rb

Closes #1133 
I couldn't replicate @mbajur's original issue, but we now have a passing test to ensure it doesn't become a problem.

Add test for a lambda slot with a block and no other arguments

---

docs/CHANGELOG.md
docs/index.md
lib/view_component/collection.rb
test/view_component/collection_test.rb

Despite the name `ViewComponent::Collection`, is a thing that renders a collection, rather than being a collection itself. This is a bit confusing and prevents some use cases were we need to operate on the collection in more ways than just rendering them.
I think my use case (see background below) is quite unique. However I do still believe that it could be useful to be able to do more with collections, than to render them 😄  
My current use case is that I have users that has some set of data and they should be able to select how this data is presented. This will be done through selecting a template implemented using a view component that gets instantiated with the users data. In order to be sure that the view component (template) can render I've added validations on them. Something like: …

Make ViewComponent::Collection a collection

---

.github/workflows/ci.yml
docs/CHANGELOG.md

This closes https://github.com/github/view_component/issues/1223 as suggested by https://github.com/github/view_component/issues/1223#issuecomment-1003016691
This also bumps all Rails versions to the latest patch release for each supported minor version.

Fix ruby 3.0 CI

---

docs/CHANGELOG.md
docs/index.md

Add `Wecasa` to the **Who uses ViewComponent?** list.

:wrench: Add "Wecasa" to "Who uses ViewComponent?" section

---

docs/CHANGELOG.md
docs/guide/collections.md
docs/index.md

Small improvements to Guide>Collections>"Collection iteration"
* Corrects a typo calling the iteration variable a counter.
* Clarifies iteration capabilities.

docs: iteration variable clarification

---

docs/CHANGELOG.md
docs/index.md

At Shogun, we also use ViewComponent for our Admin UI

Add Shogun As One of the ViewComponent Users

---

.github/styles/Microsoft/Avoid.yml
.github/styles/Microsoft/Contractions.yml
.github/styles/Microsoft/FirstPerson.yml
docs/CHANGELOG.md
docs/CONTRIBUTING.md

Brings in the latest changes from `errata-ai/Microsoft`, including errata-ai/Microsoft#40, which directly closes #1213.

Update Microsoft Vale styles

---

docs/CHANGELOG.md
docs/index.md

Add Cometeer and Framework to users list

---

docs/CHANGELOG.md
docs/logo.md

Adds CMYK value for ViewComponent Red to /logo

Add CMYK values for ViewComponent Red

---

docs/CHANGELOG.md
lib/view_component/version.rb

release 2.52.0

---

docs/CHANGELOG.md

Adds a quick blurb to the top of CHANGELOG.md explaining how it's organized.

Add explainer blurb to the top of the CHANGELOG

---

docs/CHANGELOG.md
docs/index.md

Add Mission Met to list of companies that use ViewComponent!
Add Mission Met to list of companies that use ViewComponent!
Thanks for all your work!

Add Mission Met to the list of companies that use ViewComponent

---

docs/CHANGELOG.md
docs/index.md

Add Within3 to list of companies that use ViewComponent 😄

Add Within3 to list of companies using VC

---

docs/index.md

Add Nikola Motor to list of orgs using VC
Keyboard... it was faster than text-to-speech

Add Nikola Motor to list of using orgs

---

docs/CHANGELOG.md
docs/index.md

Add [HappyCo](https://happy.co) to the list of companies using ViewComponent. Thanks for considering!
Opening a PR to the repo is the current recommended way to add to the list of companies.
This maintains alphabetical ordering.

Add HappyCo to the list of companies using ViewComponent

---

Gemfile.lock
docs/CHANGELOG.md
docs/guide/slots.md
lib/view_component/polymorphic_slots.rb
test/sandbox/app/components/polymorphic_slot_component.html.erb
test/sandbox/test/slotable_v2_test.rb

Add a `slot?` method for polymorphic slots. Fixes #1436.
Copied the implementation used for normal slots.
I haven't written tests because I haven't had time to work out how this project has set them up, but @Spone has said they will help.

Add predicate method to polymorphic slots

---

docs/CHANGELOG.md
docs/index.md

We started using ViewComponent and love it 😍

Add wip.co to list of ViewComponent users

---

.github/ISSUE_TEMPLATE/config.yml
docs/CHANGELOG.md
docs/CONTRIBUTING.md
docs/_config.yml
docs/adrs/0004-slots-separate-getter-setter.md
docs/compatibility.md
docs/guide/collections.md
docs/guide/slots.md
docs/index.md
docs/known_issues.md
docs/slots_v1.md
script/release
script/replicate-bug

Closes #1424
This PR updates our docs ahead of moving ViewComponent to its own organization on GitHub ❤️

Move ViewComponent to separate GitHub organization

---

docs/CHANGELOG.md
docs/index.md

Adding Aluuno to the list of companies using ViewComponent

Adding Aluuno to the list of companies

---

CHANGELOG.md
docs/CHANGELOG.md

Link to changelog instead of symlink

---

docs/CHANGELOG.md
docs/index.md

Adding Yobbers to the list of companies using ViewComponent.

Add Yobbers to list of companies using ViewComponent

---

docs/CHANGELOG.md
lib/view_component/engine.rb

Fix show_previews regression introduced in 2.73.0

---

Gemfile.lock
docs/CHANGELOG.md
docs/_data/library.yml
lib/view_component/version.rb

release 2.74.1

---

Gemfile.lock
docs/CHANGELOG.md
docs/_data/library.yml
lib/view_component/version.rb

release 2.75.0

---

docs/CHANGELOG.md
docs/guide/slots.md
docs/known_issues.md

The codebase contains a few Vale issues that always make it look like CI is failing on my branches 😓 
Re-worded a few things, turned off Vale for the "lazily" violation since that's a well-known industry term.

Fix Vale linting issues

---

Gemfile.lock
docs/CHANGELOG.md
docs/_data/library.yml
lib/view_component/version.rb

release 2.77.0

---

Gemfile.lock
docs/CHANGELOG.md
docs/_data/library.yml
lib/view_component/version.rb

release 2.78.0

---

Gemfile.lock
docs/CHANGELOG.md
docs/_data/library.yml
lib/view_component/version.rb

release 2.79.0

---

Gemfile.lock
docs/CHANGELOG.md
docs/_data/library.yml
lib/view_component/version.rb

release 2.80.0

---

Gemfile.lock
docs/CHANGELOG.md
docs/_data/library.yml
lib/view_component/version.rb

release 2.81.0

---

Gemfile.lock
docs/CHANGELOG.md
docs/_data/library.yml
lib/view_component/version.rb

release 2.82.0

---

docs/CHANGELOG.md
docs/index.md

Add [Mon Ami](https://www.monami.io) to the list of companies that use ViewComponent. Thanks for all of your effort in maintaining this project 🙏

Add Mon Ami to list of View Component users

---

docs/CHANGELOG.md
docs/known_issues.md

I think it helps people when they know what the compatibility issues between `form_for` and ViewComponents actually mean and what options they have.
#241 
I wanted to keep the section small, but mention all options known so far.
It does not seek to create a dedicated page on this particular topic, like #946 tried.

Update section on form_for compatibility

---

docs/index.md

Add eagerworks to the list of projects/companies that use ViewComponents.
Update the list of projects/companies that currently use ViewComponents.
Update the list directly.
Thanks for creating such an awesome library!

Update index.md adding eagerworks to the list

---

docs/index.md

Adding GetBlock, an RPC provider to the list of users.

Add GetBlock to the list of users

---

docs/adrs/0004-slots-separate-getter-setter.md

This link was pointing to a 404 since the file has been removed from `main`.

Point link in ADR 0004 to the right version of the file

---

docs/CHANGELOG.md
docs/known_issues.md
test/sandbox/test/rendering_test.rb

Add capture_compatibility_patch_enabled as option in known_issues.md

---

Gemfile.lock
docs/CHANGELOG.md
docs/_data/library.yml
lib/view_component/version.rb
test/sandbox/test/rendering_test.rb

👋🏻 We've made it! I'll ship this on Monday at RailsConf 🎊 
[Closes #1629]

release v3.0.0

---

docs/CHANGELOG.md
docs/index.md

We just started implementing our first few components over the past months and we love it!

Add flightlogger to "Who uses view components"

---

Gemfile.lock
docs/CHANGELOG.md
docs/_data/library.yml
lib/view_component/version.rb

* Check `defined?(Rails) && Rails.application` before using `ViewComponent::Base.config.view_component_path`.
*Donapieppo*
* Allow customization of polymorphic slot setters.
*Cameron Dutro*
* Fix duplication in configuration docs.
*Tom Chen*
* Fix helpers not reloading in development.
*Jonathan del Strother*
* Add `SECURITY.md`.
*Joel Hawksley*
* Add Ophelos to list of companies using ViewComponent.
*Graham Rogers*
* Add FlightLogger to list of companies using ViewComponent.
*Joseph Carpenter*
* Fix coverage reports overwriting each other when running locally.
*Jonathan del Strother*
* Add @reeganviljoen to triage team.
*Reegan Viljoen*

release 3.1.0

---

docs/CHANGELOG.md
docs/guide/testing.md

The changed example does not work without added line
It's a little docs issue.
I want every example in the documentation to work.

Add one more require to docs

---

docs/index.md

Using it for all my projects these days 👍

Add "Room AI" to list of users

---

docs/CHANGELOG.md
docs/guide/templates.md
lib/view_component/base.rb
lib/view_component/inline_template.rb
lib/view_component/rails/tasks/view_component.rake
test/sandbox/test/inline_template_test.rb

I think it's time to include this module by default ❤️ 
I also included a fix to ignore coverage of a minor rake task that has been flaky in CI.

Include InlineTemplate by default in Base

---

docs/index.md

Add a product that is using ViewComponent in production

Add Causey to Projects List

---

Gemfile.lock
docs/CHANGELOG.md
docs/_data/library.yml
lib/view_component/version.rb

release 3.4.0

---

docs/CHANGELOG.md
docs/index.md

We've been using ViewComponent since June 2022 and Lookbook since October 2022 ❤️

Add CharlieHR to the list of users

---

Gemfile.lock
docs/CHANGELOG.md
docs/_data/library.yml
docs/guide/templates.md
lib/view_component/base.rb
lib/view_component/version.rb
test/sandbox/app/components/inline_level1_component.rb
test/sandbox/app/components/inline_level2_component.rb
test/sandbox/app/components/inline_level3_component.rb

release 3.5.0

---

docs/CHANGELOG.md
docs/index.md

We just reached 100+ components and we love it :heart_eyes:.

Add SearchApi to the list of users

---

docs/CHANGELOG.md
docs/index.md

Add PeopleForce to the list of companies using ViewComponent.

Add PeopleForce to the list of companies using ViewComponent

---

Gemfile.lock
docs/CHANGELOG.md
docs/_data/library.yml
lib/view_component/version.rb
test/sandbox/test/generators/preview_generator_test.rb

release 3.6.0

---

docs/CHANGELOG.md
docs/guide/templates.md

Clarify interpolation behavior in inline templates
Close #1869

Add docs about inline templates interpolation

---

.github/workflows/ci.yml
.github/workflows/lint.yml
Appraisals
docs/CHANGELOG.md
gemfiles/rails_6.0.gemfile
gemfiles/rails_7.0.gemfile
gemfiles/rails_7.1.gemfile
gemfiles/rails_head.gemfile

Support Rails 7.1

---

Gemfile.lock
docs/CHANGELOG.md
docs/_data/library.yml
lib/view_component/version.rb

release 3.7.0

---

Gemfile.lock
docs/CHANGELOG.md
docs/_data/library.yml
lib/view_component/version.rb

release 3.8.0

---

Gemfile.lock
docs/CHANGELOG.md
docs/_data/library.yml
lib/view_component/version.rb

release 3.9.0

---

docs/CHANGELOG.md
docs/index.md

Add Keenly to users list and an accompanying changelog update.

Add Keenly to users list

---

docs/CHANGELOG.md
docs/index.md

Providing a better description of the project.
This will also help us with better ranking.
Thank you!

Update Avo name and link

---

docs/resources.md

Added the article [Quicktips for ViewComponent with Tailwind CSS/Hotwire ](https://railsdesigner.com/viewcomponents-and-tailwindcss/) to the resources page. It lists some tips/best practices around using Tailwind CSS and Hotwire with ViewComponent.

Added article to resources pages

---

Gemfile.lock
docs/CHANGELOG.md
docs/_data/library.yml
lib/view_component/version.rb

release 3.12.0

---

Gemfile.lock
docs/CHANGELOG.md
docs/_data/library.yml
lib/view_component/version.rb

release 3.12.1

---

docs/guide/previews.md
docs/resources.md

Update links to lookbook to point to the project website, rather than an outdated Github repository URL.

Update links to lookbook

---

docs/index.md

👋🏻 Thanks for the great project!
We're also using ViewComponents over here and ❤️ them.

docs/index: add Workbrew.

---

docs/index.md

View Components is one of our core gems in every Rails application we work on, both for our clients and for our own applications. Thanks for all the work!

Add "DotRuby" to list of users

---

docs/index.md

We are very proud to be on the users list as we have been using Components for several months, and it really help us :)

Add Bump.sh to the list of users

---

docs/CHANGELOG.md
docs/guide/getting-started.md

Add documentation on rendering ViewComponents outside of the view context

---

docs/CHANGELOG.md
docs/index.md

Add Kicksite to "Who uses ViewComponent?"  section

---

.github/workflows/ci.yml

This PR updates our CI configuration to use the latest upload/download actions for artifacts.
I jumped straight to the latest version and made sure CI passed.
No

use latest upload/download actions

---

docs/CHANGELOG.md
docs/index.md

Adds [Niva](https://www.niva.co/) to companies who use `ViewComponent`! ❤️

📝 Add Niva to companies who use `ViewComponent`

---

Gemfile.lock
docs/CHANGELOG.md
docs/_data/library.yml
lib/view_component/version.rb

release 3.19.0

---

docs/index.md

We have been using ViewComponent for a while now at [Defacto](https://www.defacto.nl).
Would like to say thank you an add our website to the list of "Who uses ViewComponent?".
Cheers, Matthijs

Add Defacto to Who uses ViewComponent list

---

docs/CHANGELOG.md
docs/index.md

Would like to say thank you an add our website to the list of "Who uses ViewComponent?".
With respect, Lyams

Add FreeATS to list of companies using ViewComponent 

---

docs/index.md

Add a company I work at to the list of companies!
Update the PR!
Spring is a company working to make it easy for projects and funds to raise funds, manage your cap table, run KYC and AML check on your investors. Currently working to build an exchange for unlisted companies, using blockchain technology. 
More info here: https://infra.spring.net/

Add Spring to list of companies that use ViewComponent

---

docs/index.md

Add Web3 Jobs to docs index.md

---

test/sandbox/test/rendering_test.rb

update allocation counts

---

test/sandbox/test/view_component_system_test.rb
test/test_helper.rb

Thanks @rmacklin! (https://github.com/ViewComponent/view_component/pull/2226#discussion_r1994363337)

register driver with unique name

---

docs/CHANGELOG.md
docs/api.md
lib/view_component/engine.rb
lib/view_component/errors.rb
lib/view_component/rails/tasks/view_component.rake
lib/view_component/slot.rb
lib/view_component/test_helpers.rb
test/sandbox/test/components/described_class_test.rb
test/sandbox/test/components/nil_described_class_test.rb
test/sandbox/test/rendering_test.rb

This PR removes several unnecessary `nocov`s where we had test coverage and adds coverage for a case where it really should have been written in the first place!

remove unnecessary nocov

---

docs/CHANGELOG.md
docs/CONTRIBUTING.md
docs/guide/generators.md
lib/generators/view_component/abstract_generator.rb
lib/generators/view_component/component/component_generator.rb
lib/generators/view_component/component/templates/component.rb.tt
lib/generators/view_component/erb/erb_generator.rb
test/sandbox/test/generators/component_generator_test.rb
test/sandbox/test/generators/erb_generator_test.rb
test/sandbox/test/generators/haml_generator_test.rb
test/sandbox/test/generators/slim_generator_test.rb
test/sandbox/test/generators/tailwindcss_generator_test.rb

Closes https://github.com/ViewComponent/view_component/issues/1792

--inline generator option now generates inline template

---

Appraisals
Gemfile
Gemfile.lock
gemfiles/rails_main.gemfile

Per https://github.com/rack/rack/pull/2327, this _should_ fix our broken CI for `v4`.

try pinning rack main to fix 3.5 rails main ci

---

docs/known_issues.md

Closes https://github.com/ViewComponent/view_component/issues/2032

[V4] document active scaffold incompatibility

---

test/sandbox/test/rendering_test.rb

Test case capturing @p8's use case in https://github.com/ViewComponent/view_component/issues/1523.

add test case for compatibility with custom AV::Base sublasses

---

view_component.gemspec

Closes https://github.com/ViewComponent/view_component/issues/2305

do not lock concurrent-ruby in gemspec

---

Gemfile.lock
docs/CHANGELOG.md
docs/_data/library.yml
lib/view_component/version.rb

Assuming all is stable and quiet, we'll ship this next Wednesday, July 30 🎊

release v4

---

docs/index.md

Add a new company that is using view components.

Add company using view components.
